// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// VCS coverage exclude_file
module mems_256x11(	// src/main/scala/multi_sync_mem.scala:28:47
  input  [7:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [10:0] R0_data,
  input  [7:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [10:0] W0_data
);

  reg [10:0] Memory[0:255];	// src/main/scala/multi_sync_mem.scala:28:47
  reg        _R0_en_d0;	// src/main/scala/multi_sync_mem.scala:28:47
  reg [7:0]  _R0_addr_d0;	// src/main/scala/multi_sync_mem.scala:28:47
  always @(posedge R0_clk) begin	// src/main/scala/multi_sync_mem.scala:28:47
    _R0_en_d0 <= R0_en;	// src/main/scala/multi_sync_mem.scala:28:47
    _R0_addr_d0 <= R0_addr;	// src/main/scala/multi_sync_mem.scala:28:47
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/multi_sync_mem.scala:28:47
    if (W0_en & 1'h1)	// src/main/scala/multi_sync_mem.scala:28:47
      Memory[W0_addr] <= W0_data;	// src/main/scala/multi_sync_mem.scala:28:47
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/multi_sync_mem.scala:28:47
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/multi_sync_mem.scala:28:47
      reg [31:0] _RANDOM;	// src/main/scala/multi_sync_mem.scala:28:47
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/multi_sync_mem.scala:28:47
    initial begin	// src/main/scala/multi_sync_mem.scala:28:47
      `INIT_RANDOM_PROLOG_	// src/main/scala/multi_sync_mem.scala:28:47
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/multi_sync_mem.scala:28:47
        for (logic [8:0] i = 9'h0; i < 9'h100; i += 9'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/multi_sync_mem.scala:28:47
          Memory[i[7:0]] = _RANDOM_MEM[10:0];	// src/main/scala/multi_sync_mem.scala:28:47
        end	// src/main/scala/multi_sync_mem.scala:28:47
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/multi_sync_mem.scala:28:47
        _RANDOM = {`RANDOM};	// src/main/scala/multi_sync_mem.scala:28:47
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/multi_sync_mem.scala:28:47
        _R0_addr_d0 = _RANDOM[8:1];	// src/main/scala/multi_sync_mem.scala:28:47
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 11'bx;	// src/main/scala/multi_sync_mem.scala:28:47
endmodule

module MultiMemory(	// src/main/scala/multi_sync_mem.scala:17:7
  input         clock,	// src/main/scala/multi_sync_mem.scala:17:7
  input  [7:0]  io_rdAddr_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_8,	// src/main/scala/multi_sync_mem.scala:18:14
  output [10:0] io_rdData_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input  [7:0]  io_wrAddr_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input  [10:0] io_wrData_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input         io_wrEna_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_8,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_8	// src/main/scala/multi_sync_mem.scala:18:14
);

  mems_256x11 mems_0_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_0),
    .R0_en   (io_rdEna_0),
    .R0_clk  (clock),
    .R0_data (io_rdData_0),
    .W0_addr (io_wrAddr_0),
    .W0_en   (io_wrEna_0),
    .W0_clk  (clock),
    .W0_data (io_wrData_0)
  );
  mems_256x11 mems_1_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_1),
    .R0_en   (io_rdEna_1),
    .R0_clk  (clock),
    .R0_data (io_rdData_1),
    .W0_addr (io_wrAddr_1),
    .W0_en   (io_wrEna_1),
    .W0_clk  (clock),
    .W0_data (io_wrData_1)
  );
  mems_256x11 mems_2_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_2),
    .R0_en   (io_rdEna_2),
    .R0_clk  (clock),
    .R0_data (io_rdData_2),
    .W0_addr (io_wrAddr_2),
    .W0_en   (io_wrEna_2),
    .W0_clk  (clock),
    .W0_data (io_wrData_2)
  );
  mems_256x11 mems_3_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_3),
    .R0_en   (io_rdEna_3),
    .R0_clk  (clock),
    .R0_data (io_rdData_3),
    .W0_addr (io_wrAddr_3),
    .W0_en   (io_wrEna_3),
    .W0_clk  (clock),
    .W0_data (io_wrData_3)
  );
  mems_256x11 mems_4_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_4),
    .R0_en   (io_rdEna_4),
    .R0_clk  (clock),
    .R0_data (io_rdData_4),
    .W0_addr (io_wrAddr_4),
    .W0_en   (io_wrEna_4),
    .W0_clk  (clock),
    .W0_data (io_wrData_4)
  );
  mems_256x11 mems_5_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_5),
    .R0_en   (io_rdEna_5),
    .R0_clk  (clock),
    .R0_data (io_rdData_5),
    .W0_addr (io_wrAddr_5),
    .W0_en   (io_wrEna_5),
    .W0_clk  (clock),
    .W0_data (io_wrData_5)
  );
  mems_256x11 mems_6_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_6),
    .R0_en   (io_rdEna_6),
    .R0_clk  (clock),
    .R0_data (io_rdData_6),
    .W0_addr (io_wrAddr_6),
    .W0_en   (io_wrEna_6),
    .W0_clk  (clock),
    .W0_data (io_wrData_6)
  );
  mems_256x11 mems_7_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_7),
    .R0_en   (io_rdEna_7),
    .R0_clk  (clock),
    .R0_data (io_rdData_7),
    .W0_addr (io_wrAddr_7),
    .W0_en   (io_wrEna_7),
    .W0_clk  (clock),
    .W0_data (io_wrData_7)
  );
  mems_256x11 mems_8_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_8),
    .R0_en   (io_rdEna_8),
    .R0_clk  (clock),
    .R0_data (io_rdData_8),
    .W0_addr (io_wrAddr_8),
    .W0_en   (io_wrEna_8),
    .W0_clk  (clock),
    .W0_data (io_wrData_8)
  );
endmodule

module AEQ(	// src/main/scala/aeq.scala:45:7
  input        clock,	// src/main/scala/aeq.scala:45:7
               reset,	// src/main/scala/aeq.scala:45:7
               io_writeEnable_0,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_1,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_2,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_3,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_4,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_5,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_6,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_7,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_8,	// src/main/scala/aeq.scala:46:14
               io_readEnable,	// src/main/scala/aeq.scala:46:14
  input  [8:0] io_writeData_0,	// src/main/scala/aeq.scala:46:14
               io_writeData_1,	// src/main/scala/aeq.scala:46:14
               io_writeData_2,	// src/main/scala/aeq.scala:46:14
               io_writeData_3,	// src/main/scala/aeq.scala:46:14
               io_writeData_4,	// src/main/scala/aeq.scala:46:14
               io_writeData_5,	// src/main/scala/aeq.scala:46:14
               io_writeData_6,	// src/main/scala/aeq.scala:46:14
               io_writeData_7,	// src/main/scala/aeq.scala:46:14
               io_writeData_8,	// src/main/scala/aeq.scala:46:14
  output [8:0] io_readData_0,	// src/main/scala/aeq.scala:46:14
               io_readData_1,	// src/main/scala/aeq.scala:46:14
               io_readData_2,	// src/main/scala/aeq.scala:46:14
               io_readData_3,	// src/main/scala/aeq.scala:46:14
               io_readData_4,	// src/main/scala/aeq.scala:46:14
               io_readData_5,	// src/main/scala/aeq.scala:46:14
               io_readData_6,	// src/main/scala/aeq.scala:46:14
               io_readData_7,	// src/main/scala/aeq.scala:46:14
               io_readData_8	// src/main/scala/aeq.scala:46:14
);

  wire [10:0] _multiMem_io_rdData_0;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_1;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_2;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_3;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_4;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_5;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_6;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_7;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_8;	// src/main/scala/aeq.scala:53:24
  reg  [7:0]  writeCounters_0;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_1;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_2;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_3;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_4;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_5;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_6;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_7;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_8;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  readCounter;	// src/main/scala/aeq.scala:56:28
  wire [7:0]  _GEN = io_readEnable ? readCounter : 8'h0;	// src/main/scala/aeq.scala:55:38, :56:28, :63:22, :70:23, :73:29
  always @(posedge clock) begin	// src/main/scala/aeq.scala:45:7
    if (reset) begin	// src/main/scala/aeq.scala:45:7
      writeCounters_0 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_1 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_2 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_3 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_4 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_5 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_6 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_7 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_8 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      readCounter <= 8'h0;	// src/main/scala/aeq.scala:55:38, :56:28
    end
    else begin	// src/main/scala/aeq.scala:45:7
      if (io_writeEnable_0)	// src/main/scala/aeq.scala:46:14
        writeCounters_0 <= writeCounters_0 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_1)	// src/main/scala/aeq.scala:46:14
        writeCounters_1 <= writeCounters_1 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_2)	// src/main/scala/aeq.scala:46:14
        writeCounters_2 <= writeCounters_2 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_3)	// src/main/scala/aeq.scala:46:14
        writeCounters_3 <= writeCounters_3 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_4)	// src/main/scala/aeq.scala:46:14
        writeCounters_4 <= writeCounters_4 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_5)	// src/main/scala/aeq.scala:46:14
        writeCounters_5 <= writeCounters_5 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_6)	// src/main/scala/aeq.scala:46:14
        writeCounters_6 <= writeCounters_6 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_7)	// src/main/scala/aeq.scala:46:14
        writeCounters_7 <= writeCounters_7 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_8)	// src/main/scala/aeq.scala:46:14
        writeCounters_8 <= writeCounters_8 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_readEnable)	// src/main/scala/aeq.scala:46:14
        readCounter <= readCounter + 8'h1;	// src/main/scala/aeq.scala:56:28, :76:32
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/aeq.scala:45:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/aeq.scala:45:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/aeq.scala:45:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/aeq.scala:45:7
      automatic logic [31:0] _RANDOM[0:2];	// src/main/scala/aeq.scala:45:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/aeq.scala:45:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/aeq.scala:45:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/aeq.scala:45:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/aeq.scala:45:7
        end	// src/main/scala/aeq.scala:45:7
        writeCounters_0 = _RANDOM[2'h0][7:0];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_1 = _RANDOM[2'h0][15:8];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_2 = _RANDOM[2'h0][23:16];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_3 = _RANDOM[2'h0][31:24];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_4 = _RANDOM[2'h1][7:0];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_5 = _RANDOM[2'h1][15:8];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_6 = _RANDOM[2'h1][23:16];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_7 = _RANDOM[2'h1][31:24];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_8 = _RANDOM[2'h2][7:0];	// src/main/scala/aeq.scala:45:7, :55:30
        readCounter = _RANDOM[2'h2][15:8];	// src/main/scala/aeq.scala:45:7, :55:30, :56:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/aeq.scala:45:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/aeq.scala:45:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MultiMemory multiMem (	// src/main/scala/aeq.scala:53:24
    .clock       (clock),
    .io_rdAddr_0 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_1 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_2 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_3 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_4 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_5 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_6 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_7 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_8 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdData_0 (_multiMem_io_rdData_0),
    .io_rdData_1 (_multiMem_io_rdData_1),
    .io_rdData_2 (_multiMem_io_rdData_2),
    .io_rdData_3 (_multiMem_io_rdData_3),
    .io_rdData_4 (_multiMem_io_rdData_4),
    .io_rdData_5 (_multiMem_io_rdData_5),
    .io_rdData_6 (_multiMem_io_rdData_6),
    .io_rdData_7 (_multiMem_io_rdData_7),
    .io_rdData_8 (_multiMem_io_rdData_8),
    .io_wrAddr_0 (io_writeEnable_0 ? writeCounters_0 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_1 (io_writeEnable_1 ? writeCounters_1 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_2 (io_writeEnable_2 ? writeCounters_2 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_3 (io_writeEnable_3 ? writeCounters_3 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_4 (io_writeEnable_4 ? writeCounters_4 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_5 (io_writeEnable_5 ? writeCounters_5 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_6 (io_writeEnable_6 ? writeCounters_6 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_7 (io_writeEnable_7 ? writeCounters_7 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_8 (io_writeEnable_8 ? writeCounters_8 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrData_0 (io_writeEnable_0 ? {&writeCounters_0, io_writeData_0, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_1 (io_writeEnable_1 ? {&writeCounters_1, io_writeData_1, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_2 (io_writeEnable_2 ? {&writeCounters_2, io_writeData_2, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_3 (io_writeEnable_3 ? {&writeCounters_3, io_writeData_3, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_4 (io_writeEnable_4 ? {&writeCounters_4, io_writeData_4, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_5 (io_writeEnable_5 ? {&writeCounters_5, io_writeData_5, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_6 (io_writeEnable_6 ? {&writeCounters_6, io_writeData_6, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_7 (io_writeEnable_7 ? {&writeCounters_7, io_writeData_7, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_8 (io_writeEnable_8 ? {&writeCounters_8, io_writeData_8, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrEna_0  (io_writeEnable_0),
    .io_wrEna_1  (io_writeEnable_1),
    .io_wrEna_2  (io_writeEnable_2),
    .io_wrEna_3  (io_writeEnable_3),
    .io_wrEna_4  (io_writeEnable_4),
    .io_wrEna_5  (io_writeEnable_5),
    .io_wrEna_6  (io_writeEnable_6),
    .io_wrEna_7  (io_writeEnable_7),
    .io_wrEna_8  (io_writeEnable_8),
    .io_rdEna_0  (io_readEnable),
    .io_rdEna_1  (io_readEnable),
    .io_rdEna_2  (io_readEnable),
    .io_rdEna_3  (io_readEnable),
    .io_rdEna_4  (io_readEnable),
    .io_rdEna_5  (io_readEnable),
    .io_rdEna_6  (io_readEnable),
    .io_rdEna_7  (io_readEnable),
    .io_rdEna_8  (io_readEnable)
  );
  assign io_readData_0 = _multiMem_io_rdData_0[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_1 = _multiMem_io_rdData_1[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_2 = _multiMem_io_rdData_2[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_3 = _multiMem_io_rdData_3[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_4 = _multiMem_io_rdData_4[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_5 = _multiMem_io_rdData_5[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_6 = _multiMem_io_rdData_6[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_7 = _multiMem_io_rdData_7[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_8 = _multiMem_io_rdData_8[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
endmodule

// VCS coverage exclude_file
module mems_256x9(	// src/main/scala/multi_sync_mem.scala:28:47
  input  [7:0] R0_addr,
  input        R0_en,
               R0_clk,
  output [8:0] R0_data,
  input  [7:0] W0_addr,
  input        W0_en,
               W0_clk,
  input  [8:0] W0_data
);

  reg [8:0] Memory[0:255];	// src/main/scala/multi_sync_mem.scala:28:47
  reg       _R0_en_d0;	// src/main/scala/multi_sync_mem.scala:28:47
  reg [7:0] _R0_addr_d0;	// src/main/scala/multi_sync_mem.scala:28:47
  always @(posedge R0_clk) begin	// src/main/scala/multi_sync_mem.scala:28:47
    _R0_en_d0 <= R0_en;	// src/main/scala/multi_sync_mem.scala:28:47
    _R0_addr_d0 <= R0_addr;	// src/main/scala/multi_sync_mem.scala:28:47
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/multi_sync_mem.scala:28:47
    if (W0_en & 1'h1)	// src/main/scala/multi_sync_mem.scala:28:47
      Memory[W0_addr] <= W0_data;	// src/main/scala/multi_sync_mem.scala:28:47
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/multi_sync_mem.scala:28:47
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/multi_sync_mem.scala:28:47
      reg [31:0] _RANDOM;	// src/main/scala/multi_sync_mem.scala:28:47
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/multi_sync_mem.scala:28:47
    initial begin	// src/main/scala/multi_sync_mem.scala:28:47
      `INIT_RANDOM_PROLOG_	// src/main/scala/multi_sync_mem.scala:28:47
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/multi_sync_mem.scala:28:47
        for (logic [8:0] i = 9'h0; i < 9'h100; i += 9'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/multi_sync_mem.scala:28:47
          Memory[i[7:0]] = _RANDOM_MEM[8:0];	// src/main/scala/multi_sync_mem.scala:28:47
        end	// src/main/scala/multi_sync_mem.scala:28:47
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/multi_sync_mem.scala:28:47
        _RANDOM = {`RANDOM};	// src/main/scala/multi_sync_mem.scala:28:47
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/multi_sync_mem.scala:28:47
        _R0_addr_d0 = _RANDOM[8:1];	// src/main/scala/multi_sync_mem.scala:28:47
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 9'bx;	// src/main/scala/multi_sync_mem.scala:28:47
endmodule

module MultiMemory_1(	// src/main/scala/multi_sync_mem.scala:17:7
  input        clock,	// src/main/scala/multi_sync_mem.scala:17:7
  input  [7:0] io_rdAddr_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_8,	// src/main/scala/multi_sync_mem.scala:18:14
  output [8:0] io_rdData_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input  [7:0] io_wrAddr_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input  [8:0] io_wrData_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input        io_wrEna_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_8,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_8	// src/main/scala/multi_sync_mem.scala:18:14
);

  mems_256x9 mems_0_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_0),
    .R0_en   (io_rdEna_0),
    .R0_clk  (clock),
    .R0_data (io_rdData_0),
    .W0_addr (io_wrAddr_0),
    .W0_en   (io_wrEna_0),
    .W0_clk  (clock),
    .W0_data (io_wrData_0)
  );
  mems_256x9 mems_1_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_1),
    .R0_en   (io_rdEna_1),
    .R0_clk  (clock),
    .R0_data (io_rdData_1),
    .W0_addr (io_wrAddr_1),
    .W0_en   (io_wrEna_1),
    .W0_clk  (clock),
    .W0_data (io_wrData_1)
  );
  mems_256x9 mems_2_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_2),
    .R0_en   (io_rdEna_2),
    .R0_clk  (clock),
    .R0_data (io_rdData_2),
    .W0_addr (io_wrAddr_2),
    .W0_en   (io_wrEna_2),
    .W0_clk  (clock),
    .W0_data (io_wrData_2)
  );
  mems_256x9 mems_3_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_3),
    .R0_en   (io_rdEna_3),
    .R0_clk  (clock),
    .R0_data (io_rdData_3),
    .W0_addr (io_wrAddr_3),
    .W0_en   (io_wrEna_3),
    .W0_clk  (clock),
    .W0_data (io_wrData_3)
  );
  mems_256x9 mems_4_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_4),
    .R0_en   (io_rdEna_4),
    .R0_clk  (clock),
    .R0_data (io_rdData_4),
    .W0_addr (io_wrAddr_4),
    .W0_en   (io_wrEna_4),
    .W0_clk  (clock),
    .W0_data (io_wrData_4)
  );
  mems_256x9 mems_5_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_5),
    .R0_en   (io_rdEna_5),
    .R0_clk  (clock),
    .R0_data (io_rdData_5),
    .W0_addr (io_wrAddr_5),
    .W0_en   (io_wrEna_5),
    .W0_clk  (clock),
    .W0_data (io_wrData_5)
  );
  mems_256x9 mems_6_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_6),
    .R0_en   (io_rdEna_6),
    .R0_clk  (clock),
    .R0_data (io_rdData_6),
    .W0_addr (io_wrAddr_6),
    .W0_en   (io_wrEna_6),
    .W0_clk  (clock),
    .W0_data (io_wrData_6)
  );
  mems_256x9 mems_7_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_7),
    .R0_en   (io_rdEna_7),
    .R0_clk  (clock),
    .R0_data (io_rdData_7),
    .W0_addr (io_wrAddr_7),
    .W0_en   (io_wrEna_7),
    .W0_clk  (clock),
    .W0_data (io_wrData_7)
  );
  mems_256x9 mems_8_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_8),
    .R0_en   (io_rdEna_8),
    .R0_clk  (clock),
    .R0_data (io_rdData_8),
    .W0_addr (io_wrAddr_8),
    .W0_en   (io_wrEna_8),
    .W0_clk  (clock),
    .W0_data (io_wrData_8)
  );
endmodule

module mempot(	// src/main/scala/mempot.scala:43:7
  input        clock,	// src/main/scala/mempot.scala:43:7
               io_wr_enable_0,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_1,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_2,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_3,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_4,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_5,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_6,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_7,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_8,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_0,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_1,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_2,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_3,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_4,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_5,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_6,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_7,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_8,	// src/main/scala/mempot.scala:44:14
  input  [7:0] io_addr_r_0,	// src/main/scala/mempot.scala:44:14
               io_addr_r_1,	// src/main/scala/mempot.scala:44:14
               io_addr_r_2,	// src/main/scala/mempot.scala:44:14
               io_addr_r_3,	// src/main/scala/mempot.scala:44:14
               io_addr_r_4,	// src/main/scala/mempot.scala:44:14
               io_addr_r_5,	// src/main/scala/mempot.scala:44:14
               io_addr_r_6,	// src/main/scala/mempot.scala:44:14
               io_addr_r_7,	// src/main/scala/mempot.scala:44:14
               io_addr_r_8,	// src/main/scala/mempot.scala:44:14
               io_addr_w_0,	// src/main/scala/mempot.scala:44:14
               io_addr_w_1,	// src/main/scala/mempot.scala:44:14
               io_addr_w_2,	// src/main/scala/mempot.scala:44:14
               io_addr_w_3,	// src/main/scala/mempot.scala:44:14
               io_addr_w_4,	// src/main/scala/mempot.scala:44:14
               io_addr_w_5,	// src/main/scala/mempot.scala:44:14
               io_addr_w_6,	// src/main/scala/mempot.scala:44:14
               io_addr_w_7,	// src/main/scala/mempot.scala:44:14
               io_addr_w_8,	// src/main/scala/mempot.scala:44:14
  input  [8:0] io_din_0,	// src/main/scala/mempot.scala:44:14
               io_din_1,	// src/main/scala/mempot.scala:44:14
               io_din_2,	// src/main/scala/mempot.scala:44:14
               io_din_3,	// src/main/scala/mempot.scala:44:14
               io_din_4,	// src/main/scala/mempot.scala:44:14
               io_din_5,	// src/main/scala/mempot.scala:44:14
               io_din_6,	// src/main/scala/mempot.scala:44:14
               io_din_7,	// src/main/scala/mempot.scala:44:14
               io_din_8,	// src/main/scala/mempot.scala:44:14
  output [8:0] io_dout_0,	// src/main/scala/mempot.scala:44:14
               io_dout_1,	// src/main/scala/mempot.scala:44:14
               io_dout_2,	// src/main/scala/mempot.scala:44:14
               io_dout_3,	// src/main/scala/mempot.scala:44:14
               io_dout_4,	// src/main/scala/mempot.scala:44:14
               io_dout_5,	// src/main/scala/mempot.scala:44:14
               io_dout_6,	// src/main/scala/mempot.scala:44:14
               io_dout_7,	// src/main/scala/mempot.scala:44:14
               io_dout_8	// src/main/scala/mempot.scala:44:14
);

  wire _GEN = ~io_rd_enable_0 & io_wr_enable_0;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_0 = ~io_rd_enable_1 & io_wr_enable_1;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_1 = ~io_rd_enable_2 & io_wr_enable_2;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_2 = ~io_rd_enable_3 & io_wr_enable_3;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_3 = ~io_rd_enable_4 & io_wr_enable_4;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_4 = ~io_rd_enable_5 & io_wr_enable_5;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_5 = ~io_rd_enable_6 & io_wr_enable_6;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_6 = ~io_rd_enable_7 & io_wr_enable_7;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_7 = ~io_rd_enable_8 & io_wr_enable_8;	// src/main/scala/mempot.scala:72:{11,28}
  MultiMemory_1 multiMem (	// src/main/scala/mempot.scala:55:24
    .clock       (clock),
    .io_rdAddr_0 (io_rd_enable_0 ? io_addr_r_0 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_1 (io_rd_enable_1 ? io_addr_r_1 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_2 (io_rd_enable_2 ? io_addr_r_2 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_3 (io_rd_enable_3 ? io_addr_r_3 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_4 (io_rd_enable_4 ? io_addr_r_4 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_5 (io_rd_enable_5 ? io_addr_r_5 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_6 (io_rd_enable_6 ? io_addr_r_6 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_7 (io_rd_enable_7 ? io_addr_r_7 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_8 (io_rd_enable_8 ? io_addr_r_8 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdData_0 (io_dout_0),
    .io_rdData_1 (io_dout_1),
    .io_rdData_2 (io_dout_2),
    .io_rdData_3 (io_dout_3),
    .io_rdData_4 (io_dout_4),
    .io_rdData_5 (io_dout_5),
    .io_rdData_6 (io_dout_6),
    .io_rdData_7 (io_dout_7),
    .io_rdData_8 (io_dout_8),
    .io_wrAddr_0 (_GEN ? io_addr_w_0 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_1 (_GEN_0 ? io_addr_w_1 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_2 (_GEN_1 ? io_addr_w_2 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_3 (_GEN_2 ? io_addr_w_3 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_4 (_GEN_3 ? io_addr_w_4 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_5 (_GEN_4 ? io_addr_w_5 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_6 (_GEN_5 ? io_addr_w_6 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_7 (_GEN_6 ? io_addr_w_7 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_8 (_GEN_7 ? io_addr_w_8 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrData_0 (_GEN ? io_din_0 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_1 (_GEN_0 ? io_din_1 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_2 (_GEN_1 ? io_din_2 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_3 (_GEN_2 ? io_din_3 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_4 (_GEN_3 ? io_din_4 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_5 (_GEN_4 ? io_din_5 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_6 (_GEN_5 ? io_din_6 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_7 (_GEN_6 ? io_din_7 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_8 (_GEN_7 ? io_din_8 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrEna_0  (_GEN & io_wr_enable_0),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_1  (_GEN_0 & io_wr_enable_1),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_2  (_GEN_1 & io_wr_enable_2),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_3  (_GEN_2 & io_wr_enable_3),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_4  (_GEN_3 & io_wr_enable_4),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_5  (_GEN_4 & io_wr_enable_5),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_6  (_GEN_5 & io_wr_enable_6),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_7  (_GEN_6 & io_wr_enable_7),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_8  (_GEN_7 & io_wr_enable_8),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_rdEna_0  (io_rd_enable_0),
    .io_rdEna_1  (io_rd_enable_1),
    .io_rdEna_2  (io_rd_enable_2),
    .io_rdEna_3  (io_rd_enable_3),
    .io_rdEna_4  (io_rd_enable_4),
    .io_rdEna_5  (io_rd_enable_5),
    .io_rdEna_6  (io_rd_enable_6),
    .io_rdEna_7  (io_rd_enable_7),
    .io_rdEna_8  (io_rd_enable_8)
  );
endmodule

module conv(	// src/main/scala/conv.scala:15:7
  input        clock,	// src/main/scala/conv.scala:15:7
               reset,	// src/main/scala/conv.scala:15:7
               io_wr_enable_aeq_0,	// src/main/scala/conv.scala:16:14
               io_wr_enable_aeq_1,	// src/main/scala/conv.scala:16:14
               io_wr_enable_aeq_2,	// src/main/scala/conv.scala:16:14
               io_wr_enable_aeq_3,	// src/main/scala/conv.scala:16:14
               io_wr_enable_aeq_4,	// src/main/scala/conv.scala:16:14
               io_wr_enable_aeq_5,	// src/main/scala/conv.scala:16:14
               io_wr_enable_aeq_6,	// src/main/scala/conv.scala:16:14
               io_wr_enable_aeq_7,	// src/main/scala/conv.scala:16:14
               io_wr_enable_aeq_8,	// src/main/scala/conv.scala:16:14
               io_rd_enable_aeq,	// src/main/scala/conv.scala:16:14
  input  [8:0] io_writeData_aeq_0,	// src/main/scala/conv.scala:16:14
               io_writeData_aeq_1,	// src/main/scala/conv.scala:16:14
               io_writeData_aeq_2,	// src/main/scala/conv.scala:16:14
               io_writeData_aeq_3,	// src/main/scala/conv.scala:16:14
               io_writeData_aeq_4,	// src/main/scala/conv.scala:16:14
               io_writeData_aeq_5,	// src/main/scala/conv.scala:16:14
               io_writeData_aeq_6,	// src/main/scala/conv.scala:16:14
               io_writeData_aeq_7,	// src/main/scala/conv.scala:16:14
               io_writeData_aeq_8,	// src/main/scala/conv.scala:16:14
  output [8:0] io_readData_aeq_0,	// src/main/scala/conv.scala:16:14
               io_readData_aeq_1,	// src/main/scala/conv.scala:16:14
               io_readData_aeq_2,	// src/main/scala/conv.scala:16:14
               io_readData_aeq_3,	// src/main/scala/conv.scala:16:14
               io_readData_aeq_4,	// src/main/scala/conv.scala:16:14
               io_readData_aeq_5,	// src/main/scala/conv.scala:16:14
               io_readData_aeq_6,	// src/main/scala/conv.scala:16:14
               io_readData_aeq_7,	// src/main/scala/conv.scala:16:14
               io_readData_aeq_8,	// src/main/scala/conv.scala:16:14
  input        io_wr_enable_mempot_0,	// src/main/scala/conv.scala:16:14
               io_wr_enable_mempot_1,	// src/main/scala/conv.scala:16:14
               io_wr_enable_mempot_2,	// src/main/scala/conv.scala:16:14
               io_wr_enable_mempot_3,	// src/main/scala/conv.scala:16:14
               io_wr_enable_mempot_4,	// src/main/scala/conv.scala:16:14
               io_wr_enable_mempot_5,	// src/main/scala/conv.scala:16:14
               io_wr_enable_mempot_6,	// src/main/scala/conv.scala:16:14
               io_wr_enable_mempot_7,	// src/main/scala/conv.scala:16:14
               io_wr_enable_mempot_8,	// src/main/scala/conv.scala:16:14
               io_rd_enable_mempot_0,	// src/main/scala/conv.scala:16:14
               io_rd_enable_mempot_1,	// src/main/scala/conv.scala:16:14
               io_rd_enable_mempot_2,	// src/main/scala/conv.scala:16:14
               io_rd_enable_mempot_3,	// src/main/scala/conv.scala:16:14
               io_rd_enable_mempot_4,	// src/main/scala/conv.scala:16:14
               io_rd_enable_mempot_5,	// src/main/scala/conv.scala:16:14
               io_rd_enable_mempot_6,	// src/main/scala/conv.scala:16:14
               io_rd_enable_mempot_7,	// src/main/scala/conv.scala:16:14
               io_rd_enable_mempot_8,	// src/main/scala/conv.scala:16:14
  input  [7:0] io_addr_r_mempot_0,	// src/main/scala/conv.scala:16:14
               io_addr_r_mempot_1,	// src/main/scala/conv.scala:16:14
               io_addr_r_mempot_2,	// src/main/scala/conv.scala:16:14
               io_addr_r_mempot_3,	// src/main/scala/conv.scala:16:14
               io_addr_r_mempot_4,	// src/main/scala/conv.scala:16:14
               io_addr_r_mempot_5,	// src/main/scala/conv.scala:16:14
               io_addr_r_mempot_6,	// src/main/scala/conv.scala:16:14
               io_addr_r_mempot_7,	// src/main/scala/conv.scala:16:14
               io_addr_r_mempot_8,	// src/main/scala/conv.scala:16:14
               io_addr_w_mempot_0,	// src/main/scala/conv.scala:16:14
               io_addr_w_mempot_1,	// src/main/scala/conv.scala:16:14
               io_addr_w_mempot_2,	// src/main/scala/conv.scala:16:14
               io_addr_w_mempot_3,	// src/main/scala/conv.scala:16:14
               io_addr_w_mempot_4,	// src/main/scala/conv.scala:16:14
               io_addr_w_mempot_5,	// src/main/scala/conv.scala:16:14
               io_addr_w_mempot_6,	// src/main/scala/conv.scala:16:14
               io_addr_w_mempot_7,	// src/main/scala/conv.scala:16:14
               io_addr_w_mempot_8,	// src/main/scala/conv.scala:16:14
  input  [8:0] io_din_mempot_0,	// src/main/scala/conv.scala:16:14
               io_din_mempot_1,	// src/main/scala/conv.scala:16:14
               io_din_mempot_2,	// src/main/scala/conv.scala:16:14
               io_din_mempot_3,	// src/main/scala/conv.scala:16:14
               io_din_mempot_4,	// src/main/scala/conv.scala:16:14
               io_din_mempot_5,	// src/main/scala/conv.scala:16:14
               io_din_mempot_6,	// src/main/scala/conv.scala:16:14
               io_din_mempot_7,	// src/main/scala/conv.scala:16:14
               io_din_mempot_8,	// src/main/scala/conv.scala:16:14
  output [8:0] io_dout_mempot_0,	// src/main/scala/conv.scala:16:14
               io_dout_mempot_1,	// src/main/scala/conv.scala:16:14
               io_dout_mempot_2,	// src/main/scala/conv.scala:16:14
               io_dout_mempot_3,	// src/main/scala/conv.scala:16:14
               io_dout_mempot_4,	// src/main/scala/conv.scala:16:14
               io_dout_mempot_5,	// src/main/scala/conv.scala:16:14
               io_dout_mempot_6,	// src/main/scala/conv.scala:16:14
               io_dout_mempot_7,	// src/main/scala/conv.scala:16:14
               io_dout_mempot_8,	// src/main/scala/conv.scala:16:14
  input  [7:0] io_bias_0,	// src/main/scala/conv.scala:16:14
               io_bias_1,	// src/main/scala/conv.scala:16:14
               io_bias_2,	// src/main/scala/conv.scala:16:14
               io_bias_3,	// src/main/scala/conv.scala:16:14
               io_bias_4,	// src/main/scala/conv.scala:16:14
               io_bias_5,	// src/main/scala/conv.scala:16:14
               io_bias_6,	// src/main/scala/conv.scala:16:14
               io_bias_7,	// src/main/scala/conv.scala:16:14
               io_bias_8,	// src/main/scala/conv.scala:16:14
               io_V_t,	// src/main/scala/conv.scala:16:14
  input        io_thresh_enab,	// src/main/scala/conv.scala:16:14
               io_conv_enab,	// src/main/scala/conv.scala:16:14
  input  [7:0] io_kernel_0,	// src/main/scala/conv.scala:16:14
               io_kernel_1,	// src/main/scala/conv.scala:16:14
               io_kernel_2,	// src/main/scala/conv.scala:16:14
               io_kernel_3,	// src/main/scala/conv.scala:16:14
               io_kernel_4,	// src/main/scala/conv.scala:16:14
               io_kernel_5,	// src/main/scala/conv.scala:16:14
               io_kernel_6,	// src/main/scala/conv.scala:16:14
               io_kernel_7,	// src/main/scala/conv.scala:16:14
               io_kernel_8	// src/main/scala/conv.scala:16:14
);

  wire [8:0]       _mempotMem_io_dout_0;	// src/main/scala/conv.scala:40:25
  wire [8:0]       _mempotMem_io_dout_1;	// src/main/scala/conv.scala:40:25
  wire [8:0]       _mempotMem_io_dout_2;	// src/main/scala/conv.scala:40:25
  wire [8:0]       _mempotMem_io_dout_3;	// src/main/scala/conv.scala:40:25
  wire [8:0]       _mempotMem_io_dout_4;	// src/main/scala/conv.scala:40:25
  wire [8:0]       _mempotMem_io_dout_5;	// src/main/scala/conv.scala:40:25
  wire [8:0]       _mempotMem_io_dout_6;	// src/main/scala/conv.scala:40:25
  wire [8:0]       _mempotMem_io_dout_7;	// src/main/scala/conv.scala:40:25
  wire [8:0]       _mempotMem_io_dout_8;	// src/main/scala/conv.scala:40:25
  wire [8:0]       _aeqMem_io_readData_0;	// src/main/scala/conv.scala:39:22
  wire             _GEN = io_thresh_enab & ~io_conv_enab;	// src/main/scala/conv.scala:63:{48,51}
  reg  [7:0]       counter;	// src/main/scala/chisel3/util/Counter.scala:61:40
  wire             wrap = _GEN & (&counter);	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24, :117:24, :118:{16,23}, src/main/scala/conv.scala:63:48
  wire [7:0]       _dout_0_T = _mempotMem_io_dout_0[7:0] + io_bias_0;	// src/main/scala/conv.scala:40:25, :72:25
  wire             _GEN_0 = ~wrap | io_wr_enable_mempot_0;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:47:26, :65:14, :74:30
  wire [8:0]       _GEN_1 =
    wrap ? io_din_mempot_0 : _dout_0_T > io_V_t ? 9'h100 : {1'h0, _dout_0_T};	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:15:7, :51:20, :65:14, :72:25, :74:{20,30}, :76:29, :79:29
  wire [7:0]       _dout_1_T = _mempotMem_io_dout_1[7:0] + io_bias_1;	// src/main/scala/conv.scala:40:25, :72:25
  wire             _GEN_2 = ~wrap | io_wr_enable_mempot_1;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:47:26, :65:14, :74:30
  wire [8:0]       _GEN_3 =
    wrap ? io_din_mempot_1 : _dout_1_T > io_V_t ? 9'h100 : {1'h0, _dout_1_T};	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:15:7, :51:20, :65:14, :72:25, :74:{20,30}, :76:29, :79:29
  wire [7:0]       _dout_2_T = _mempotMem_io_dout_2[7:0] + io_bias_2;	// src/main/scala/conv.scala:40:25, :72:25
  wire             _GEN_4 = ~wrap | io_wr_enable_mempot_2;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:47:26, :65:14, :74:30
  wire [8:0]       _GEN_5 =
    wrap ? io_din_mempot_2 : _dout_2_T > io_V_t ? 9'h100 : {1'h0, _dout_2_T};	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:15:7, :51:20, :65:14, :72:25, :74:{20,30}, :76:29, :79:29
  wire [7:0]       _dout_3_T = _mempotMem_io_dout_3[7:0] + io_bias_3;	// src/main/scala/conv.scala:40:25, :72:25
  wire             _GEN_6 = ~wrap | io_wr_enable_mempot_3;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:47:26, :65:14, :74:30
  wire [8:0]       _GEN_7 =
    wrap ? io_din_mempot_3 : _dout_3_T > io_V_t ? 9'h100 : {1'h0, _dout_3_T};	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:15:7, :51:20, :65:14, :72:25, :74:{20,30}, :76:29, :79:29
  wire [7:0]       _dout_4_T = _mempotMem_io_dout_4[7:0] + io_bias_4;	// src/main/scala/conv.scala:40:25, :72:25
  wire             _GEN_8 = ~wrap | io_wr_enable_mempot_4;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:47:26, :65:14, :74:30
  wire [8:0]       _GEN_9 =
    wrap ? io_din_mempot_4 : _dout_4_T > io_V_t ? 9'h100 : {1'h0, _dout_4_T};	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:15:7, :51:20, :65:14, :72:25, :74:{20,30}, :76:29, :79:29
  wire [7:0]       _dout_5_T = _mempotMem_io_dout_5[7:0] + io_bias_5;	// src/main/scala/conv.scala:40:25, :72:25
  wire             _GEN_10 = ~wrap | io_wr_enable_mempot_5;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:47:26, :65:14, :74:30
  wire [8:0]       _GEN_11 =
    wrap ? io_din_mempot_5 : _dout_5_T > io_V_t ? 9'h100 : {1'h0, _dout_5_T};	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:15:7, :51:20, :65:14, :72:25, :74:{20,30}, :76:29, :79:29
  wire [7:0]       _dout_6_T = _mempotMem_io_dout_6[7:0] + io_bias_6;	// src/main/scala/conv.scala:40:25, :72:25
  wire             _GEN_12 = ~wrap | io_wr_enable_mempot_6;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:47:26, :65:14, :74:30
  wire [8:0]       _GEN_13 =
    wrap ? io_din_mempot_6 : _dout_6_T > io_V_t ? 9'h100 : {1'h0, _dout_6_T};	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:15:7, :51:20, :65:14, :72:25, :74:{20,30}, :76:29, :79:29
  wire [7:0]       _dout_7_T = _mempotMem_io_dout_7[7:0] + io_bias_7;	// src/main/scala/conv.scala:40:25, :72:25
  wire             _GEN_14 = ~wrap | io_wr_enable_mempot_7;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:47:26, :65:14, :74:30
  wire [8:0]       _GEN_15 =
    wrap ? io_din_mempot_7 : _dout_7_T > io_V_t ? 9'h100 : {1'h0, _dout_7_T};	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:15:7, :51:20, :65:14, :72:25, :74:{20,30}, :76:29, :79:29
  wire [7:0]       _dout_8_T = _mempotMem_io_dout_8[7:0] + io_bias_8;	// src/main/scala/conv.scala:40:25, :72:25
  wire             _GEN_16 = ~wrap | io_wr_enable_mempot_8;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:47:26, :65:14, :74:30
  wire [8:0]       _GEN_17 =
    wrap ? io_din_mempot_8 : _dout_8_T > io_V_t ? 9'h100 : {1'h0, _dout_8_T};	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/conv.scala:15:7, :51:20, :65:14, :72:25, :74:{20,30}, :76:29, :79:29
  reg              conv_done;	// src/main/scala/conv.scala:85:26
  wire             _GEN_18 = ~conv_done & io_conv_enab & ~io_thresh_enab;	// src/main/scala/conv.scala:85:26, :87:{8,35,38}
  wire [9:0]       m = {2'h0, _aeqMem_io_readData_0[8:1] / 8'h10} * 10'h3;	// src/main/scala/conv.scala:39:22, :72:25, :92:31, :93:{22,34}
  wire [7:0]       _n_T = _aeqMem_io_readData_0[8:1] % 8'h10;	// src/main/scala/conv.scala:39:22, :92:31, :93:34, :94:34
  wire [9:0]       _mk_T_24 = m - 10'h1;	// src/main/scala/conv.scala:93:22, :98:24
  wire [6:0]       _nl_T_24 = {2'h0, _n_T[4:0]} * 7'h3 - 7'h1;	// src/main/scala/conv.scala:72:25, :94:{22,34}, :99:24
  wire [9:0]       _c_T = _mk_T_24 % 10'h3;	// src/main/scala/conv.scala:93:22, :98:24, :101:25
  wire [7:0]       _c_T_1 = {1'h0, _nl_T_24} % 8'h3;	// src/main/scala/conv.scala:15:7, :99:{24,30}, :101:44
  wire [3:0]       _c_T_3 = {2'h0, _c_T[1:0]} + {2'h0, _c_T_1[1:0]} * 4'h3;	// src/main/scala/conv.scala:72:25, :101:{25,32,38,44}, :107:41
  wire [15:0][8:0] _GEN_19 =
    {{_mempotMem_io_dout_0},
     {_mempotMem_io_dout_0},
     {_mempotMem_io_dout_0},
     {_mempotMem_io_dout_0},
     {_mempotMem_io_dout_0},
     {_mempotMem_io_dout_0},
     {_mempotMem_io_dout_0},
     {_mempotMem_io_dout_8},
     {_mempotMem_io_dout_7},
     {_mempotMem_io_dout_6},
     {_mempotMem_io_dout_5},
     {_mempotMem_io_dout_4},
     {_mempotMem_io_dout_3},
     {_mempotMem_io_dout_2},
     {_mempotMem_io_dout_1},
     {_mempotMem_io_dout_0}};	// src/main/scala/conv.scala:40:25, :104:43
  wire [8:0]       _kernel_added_T = _GEN_19[_c_T_3] + {1'h0, io_kernel_8};	// src/main/scala/conv.scala:15:7, :101:32, :104:43
  wire [15:0]      _GEN_20 =
    {{io_wr_enable_mempot_0},
     {io_wr_enable_mempot_0},
     {io_wr_enable_mempot_0},
     {io_wr_enable_mempot_0},
     {io_wr_enable_mempot_0},
     {io_wr_enable_mempot_0},
     {io_wr_enable_mempot_0},
     {io_wr_enable_mempot_8},
     {io_wr_enable_mempot_7},
     {io_wr_enable_mempot_6},
     {io_wr_enable_mempot_5},
     {io_wr_enable_mempot_4},
     {io_wr_enable_mempot_3},
     {io_wr_enable_mempot_2},
     {io_wr_enable_mempot_1},
     {io_wr_enable_mempot_0}};	// src/main/scala/conv.scala:106:42
  wire             _GEN_21 = _GEN_20[_c_T_3] & _c_T_3 == 4'h0;	// src/main/scala/conv.scala:65:14, :101:32, :104:43, :106:42, :107:41
  wire             _GEN_22 = _GEN_20[_c_T_3] & _c_T_3 == 4'h1;	// src/main/scala/conv.scala:65:14, :101:32, :106:42, :107:41
  wire             _GEN_23 = _GEN_20[_c_T_3] & _c_T_3 == 4'h2;	// src/main/scala/conv.scala:65:14, :101:32, :106:42, :107:41
  wire             _GEN_24 = _GEN_20[_c_T_3] & _c_T_3 == 4'h3;	// src/main/scala/conv.scala:65:14, :101:32, :106:42, :107:41
  wire             _GEN_25 = _GEN_20[_c_T_3] & _c_T_3 == 4'h4;	// src/main/scala/conv.scala:65:14, :101:32, :106:42, :107:41
  wire             _GEN_26 = _GEN_20[_c_T_3] & _c_T_3 == 4'h5;	// src/main/scala/conv.scala:65:14, :101:32, :106:42, :107:41
  wire             _GEN_27 = _GEN_20[_c_T_3] & _c_T_3 == 4'h6;	// src/main/scala/conv.scala:65:14, :101:32, :106:42, :107:41
  wire             _GEN_28 = _GEN_20[_c_T_3] & _c_T_3 == 4'h7;	// src/main/scala/conv.scala:65:14, :101:32, :106:42, :107:41
  wire             _GEN_29 = _GEN_20[_c_T_3] & _c_T_3 == 4'h8;	// src/main/scala/conv.scala:65:14, :101:32, :106:42, :107:41
  wire [7:0]       _GEN_30 = {1'h0, _nl_T_24};	// src/main/scala/conv.scala:15:7, :99:{24,30}
  wire [9:0]       _c_T_4 = _mk_T_24 % 10'h3;	// src/main/scala/conv.scala:93:22, :98:24, :101:25
  wire [7:0]       _c_T_5 = (_GEN_30 + 8'h1) % 8'h3;	// src/main/scala/conv.scala:99:{24,30}, :101:44
  wire [3:0]       _c_T_7 = {2'h0, _c_T_4[1:0]} + {2'h0, _c_T_5[1:0]} * 4'h3;	// src/main/scala/conv.scala:72:25, :101:{25,32,38,44}, :107:41
  wire [8:0]       _kernel_added_T_1 = _GEN_19[_c_T_7] + {1'h0, io_kernel_7};	// src/main/scala/conv.scala:15:7, :101:32, :104:43
  wire             _GEN_31 = _c_T_7 == 4'h0;	// src/main/scala/conv.scala:101:32, :104:43, :107:41
  wire             _GEN_32 =
    _GEN_20[_c_T_7] ? _GEN_31 | _GEN_21 | _GEN_0 : _GEN_21 | _GEN_0;	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :101:32, :106:42, :107:41
  wire             _GEN_33 = _c_T_7 == 4'h1;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_34 =
    _GEN_20[_c_T_7] ? _GEN_33 | _GEN_22 | _GEN_2 : _GEN_22 | _GEN_2;	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :101:32, :106:42, :107:41
  wire             _GEN_35 = _c_T_7 == 4'h2;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_36 =
    _GEN_20[_c_T_7] ? _GEN_35 | _GEN_23 | _GEN_4 : _GEN_23 | _GEN_4;	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :101:32, :106:42, :107:41
  wire             _GEN_37 = _c_T_7 == 4'h3;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_38 =
    _GEN_20[_c_T_7] ? _GEN_37 | _GEN_24 | _GEN_6 : _GEN_24 | _GEN_6;	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :101:32, :106:42, :107:41
  wire             _GEN_39 = _c_T_7 == 4'h4;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_40 =
    _GEN_20[_c_T_7] ? _GEN_39 | _GEN_25 | _GEN_8 : _GEN_25 | _GEN_8;	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :101:32, :106:42, :107:41
  wire             _GEN_41 = _c_T_7 == 4'h5;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_42 =
    _GEN_20[_c_T_7] ? _GEN_41 | _GEN_26 | _GEN_10 : _GEN_26 | _GEN_10;	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :101:32, :106:42, :107:41
  wire             _GEN_43 = _c_T_7 == 4'h6;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_44 =
    _GEN_20[_c_T_7] ? _GEN_43 | _GEN_27 | _GEN_12 : _GEN_27 | _GEN_12;	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :101:32, :106:42, :107:41
  wire             _GEN_45 = _c_T_7 == 4'h7;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_46 =
    _GEN_20[_c_T_7] ? _GEN_45 | _GEN_28 | _GEN_14 : _GEN_28 | _GEN_14;	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :101:32, :106:42, :107:41
  wire             _GEN_47 = _c_T_7 == 4'h8;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_48 =
    _GEN_20[_c_T_7] ? _GEN_47 | _GEN_29 | _GEN_16 : _GEN_29 | _GEN_16;	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :101:32, :106:42, :107:41
  wire [9:0]       _c_T_8 = _mk_T_24 % 10'h3;	// src/main/scala/conv.scala:93:22, :98:24, :101:25
  wire [7:0]       _c_T_9 = (_GEN_30 + 8'h2) % 8'h3;	// src/main/scala/conv.scala:99:30, :101:44
  wire [3:0]       _c_T_11 = {2'h0, _c_T_8[1:0]} + {2'h0, _c_T_9[1:0]} * 4'h3;	// src/main/scala/conv.scala:72:25, :101:{25,32,38,44}, :107:41
  wire [8:0]       _kernel_added_T_2 = _GEN_19[_c_T_11] + {1'h0, io_kernel_6};	// src/main/scala/conv.scala:15:7, :101:32, :104:43
  wire             _GEN_49 = _GEN_20[_c_T_11] & _c_T_11 == 4'h0;	// src/main/scala/conv.scala:101:32, :104:43, :106:42, :107:41
  wire             _GEN_50 = _GEN_20[_c_T_11] & _c_T_11 == 4'h1;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_51 = _GEN_20[_c_T_11] & _c_T_11 == 4'h2;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_52 = _GEN_20[_c_T_11] & _c_T_11 == 4'h3;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_53 = _GEN_20[_c_T_11] & _c_T_11 == 4'h4;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_54 = _GEN_20[_c_T_11] & _c_T_11 == 4'h5;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_55 = _GEN_20[_c_T_11] & _c_T_11 == 4'h6;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_56 = _GEN_20[_c_T_11] & _c_T_11 == 4'h7;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_57 = _GEN_20[_c_T_11] & _c_T_11 == 4'h8;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire [9:0]       _c_T_12 = m % 10'h3;	// src/main/scala/conv.scala:93:22, :101:25
  wire [7:0]       _c_T_13 = {1'h0, _nl_T_24} % 8'h3;	// src/main/scala/conv.scala:15:7, :99:{24,30}, :101:44
  wire [3:0]       _c_T_15 = {2'h0, _c_T_12[1:0]} + {2'h0, _c_T_13[1:0]} * 4'h3;	// src/main/scala/conv.scala:72:25, :101:{25,32,38,44}, :107:41
  wire [8:0]       _kernel_added_T_3 = _GEN_19[_c_T_15] + {1'h0, io_kernel_5};	// src/main/scala/conv.scala:15:7, :101:32, :104:43
  wire             _GEN_58 = _c_T_15 == 4'h0;	// src/main/scala/conv.scala:101:32, :104:43, :107:41
  wire             _GEN_59 =
    _GEN_20[_c_T_15] ? _GEN_58 | _GEN_49 | _GEN_32 : _GEN_49 | _GEN_32;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_60 = _c_T_15 == 4'h1;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_61 =
    _GEN_20[_c_T_15] ? _GEN_60 | _GEN_50 | _GEN_34 : _GEN_50 | _GEN_34;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_62 = _c_T_15 == 4'h2;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_63 =
    _GEN_20[_c_T_15] ? _GEN_62 | _GEN_51 | _GEN_36 : _GEN_51 | _GEN_36;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_64 = _c_T_15 == 4'h3;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_65 =
    _GEN_20[_c_T_15] ? _GEN_64 | _GEN_52 | _GEN_38 : _GEN_52 | _GEN_38;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_66 = _c_T_15 == 4'h4;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_67 =
    _GEN_20[_c_T_15] ? _GEN_66 | _GEN_53 | _GEN_40 : _GEN_53 | _GEN_40;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_68 = _c_T_15 == 4'h5;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_69 =
    _GEN_20[_c_T_15] ? _GEN_68 | _GEN_54 | _GEN_42 : _GEN_54 | _GEN_42;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_70 = _c_T_15 == 4'h6;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_71 =
    _GEN_20[_c_T_15] ? _GEN_70 | _GEN_55 | _GEN_44 : _GEN_55 | _GEN_44;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_72 = _c_T_15 == 4'h7;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_73 =
    _GEN_20[_c_T_15] ? _GEN_72 | _GEN_56 | _GEN_46 : _GEN_56 | _GEN_46;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_74 = _c_T_15 == 4'h8;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_75 =
    _GEN_20[_c_T_15] ? _GEN_74 | _GEN_57 | _GEN_48 : _GEN_57 | _GEN_48;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire [9:0]       _c_T_16 = m % 10'h3;	// src/main/scala/conv.scala:93:22, :101:25
  wire [7:0]       _c_T_17 = (_GEN_30 + 8'h1) % 8'h3;	// src/main/scala/conv.scala:99:{24,30}, :101:44
  wire [3:0]       _c_T_19 = {2'h0, _c_T_16[1:0]} + {2'h0, _c_T_17[1:0]} * 4'h3;	// src/main/scala/conv.scala:72:25, :101:{25,32,38,44}, :107:41
  wire [8:0]       _kernel_added_T_4 = _GEN_19[_c_T_19] + {1'h0, io_kernel_4};	// src/main/scala/conv.scala:15:7, :101:32, :104:43
  wire             _GEN_76 = _GEN_20[_c_T_19] & _c_T_19 == 4'h0;	// src/main/scala/conv.scala:101:32, :104:43, :106:42, :107:41
  wire             _GEN_77 = _GEN_20[_c_T_19] & _c_T_19 == 4'h1;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_78 = _GEN_20[_c_T_19] & _c_T_19 == 4'h2;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_79 = _GEN_20[_c_T_19] & _c_T_19 == 4'h3;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_80 = _GEN_20[_c_T_19] & _c_T_19 == 4'h4;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_81 = _GEN_20[_c_T_19] & _c_T_19 == 4'h5;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_82 = _GEN_20[_c_T_19] & _c_T_19 == 4'h6;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_83 = _GEN_20[_c_T_19] & _c_T_19 == 4'h7;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_84 = _GEN_20[_c_T_19] & _c_T_19 == 4'h8;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire [9:0]       _c_T_20 = m % 10'h3;	// src/main/scala/conv.scala:93:22, :101:25
  wire [7:0]       _c_T_21 = (_GEN_30 + 8'h2) % 8'h3;	// src/main/scala/conv.scala:99:30, :101:44
  wire [3:0]       _c_T_23 = {2'h0, _c_T_20[1:0]} + {2'h0, _c_T_21[1:0]} * 4'h3;	// src/main/scala/conv.scala:72:25, :101:{25,32,38,44}, :107:41
  wire [8:0]       _kernel_added_T_5 = _GEN_19[_c_T_23] + {1'h0, io_kernel_3};	// src/main/scala/conv.scala:15:7, :101:32, :104:43
  wire             _GEN_85 = _c_T_23 == 4'h0;	// src/main/scala/conv.scala:101:32, :104:43, :107:41
  wire             _GEN_86 =
    _GEN_20[_c_T_23] ? _GEN_85 | _GEN_76 | _GEN_59 : _GEN_76 | _GEN_59;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_87 = _c_T_23 == 4'h1;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_88 =
    _GEN_20[_c_T_23] ? _GEN_87 | _GEN_77 | _GEN_61 : _GEN_77 | _GEN_61;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_89 = _c_T_23 == 4'h2;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_90 =
    _GEN_20[_c_T_23] ? _GEN_89 | _GEN_78 | _GEN_63 : _GEN_78 | _GEN_63;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_91 = _c_T_23 == 4'h3;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_92 =
    _GEN_20[_c_T_23] ? _GEN_91 | _GEN_79 | _GEN_65 : _GEN_79 | _GEN_65;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_93 = _c_T_23 == 4'h4;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_94 =
    _GEN_20[_c_T_23] ? _GEN_93 | _GEN_80 | _GEN_67 : _GEN_80 | _GEN_67;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_95 = _c_T_23 == 4'h5;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_96 =
    _GEN_20[_c_T_23] ? _GEN_95 | _GEN_81 | _GEN_69 : _GEN_81 | _GEN_69;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_97 = _c_T_23 == 4'h6;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_98 =
    _GEN_20[_c_T_23] ? _GEN_97 | _GEN_82 | _GEN_71 : _GEN_82 | _GEN_71;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_99 = _c_T_23 == 4'h7;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_100 =
    _GEN_20[_c_T_23] ? _GEN_99 | _GEN_83 | _GEN_73 : _GEN_83 | _GEN_73;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_101 = _c_T_23 == 4'h8;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_102 =
    _GEN_20[_c_T_23] ? _GEN_101 | _GEN_84 | _GEN_75 : _GEN_84 | _GEN_75;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire [9:0]       _c_T_24 = (m + 10'h1) % 10'h3;	// src/main/scala/conv.scala:93:22, :98:30, :101:25
  wire [7:0]       _c_T_25 = {1'h0, _nl_T_24} % 8'h3;	// src/main/scala/conv.scala:15:7, :99:{24,30}, :101:44
  wire [3:0]       _c_T_27 = {2'h0, _c_T_24[1:0]} + {2'h0, _c_T_25[1:0]} * 4'h3;	// src/main/scala/conv.scala:72:25, :101:{25,32,38,44}, :107:41
  wire [8:0]       _kernel_added_T_6 = _GEN_19[_c_T_27] + {1'h0, io_kernel_2};	// src/main/scala/conv.scala:15:7, :101:32, :104:43
  wire             _GEN_103 = _GEN_20[_c_T_27] & _c_T_27 == 4'h0;	// src/main/scala/conv.scala:101:32, :104:43, :106:42, :107:41
  wire             _GEN_104 = _GEN_20[_c_T_27] & _c_T_27 == 4'h1;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_105 = _GEN_20[_c_T_27] & _c_T_27 == 4'h2;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_106 = _GEN_20[_c_T_27] & _c_T_27 == 4'h3;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_107 = _GEN_20[_c_T_27] & _c_T_27 == 4'h4;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_108 = _GEN_20[_c_T_27] & _c_T_27 == 4'h5;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_109 = _GEN_20[_c_T_27] & _c_T_27 == 4'h6;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_110 = _GEN_20[_c_T_27] & _c_T_27 == 4'h7;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_111 = _GEN_20[_c_T_27] & _c_T_27 == 4'h8;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire [9:0]       _c_T_28 = (m + 10'h1) % 10'h3;	// src/main/scala/conv.scala:93:22, :98:30, :101:25
  wire [7:0]       _c_T_29 = (_GEN_30 + 8'h1) % 8'h3;	// src/main/scala/conv.scala:99:{24,30}, :101:44
  wire [3:0]       _c_T_31 = {2'h0, _c_T_28[1:0]} + {2'h0, _c_T_29[1:0]} * 4'h3;	// src/main/scala/conv.scala:72:25, :101:{25,32,38,44}, :107:41
  wire [8:0]       _kernel_added_T_7 = _GEN_19[_c_T_31] + {1'h0, io_kernel_1};	// src/main/scala/conv.scala:15:7, :101:32, :104:43
  wire             _GEN_112 = _c_T_31 == 4'h0;	// src/main/scala/conv.scala:101:32, :104:43, :107:41
  wire             _GEN_113 = _c_T_31 == 4'h1;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_114 = _c_T_31 == 4'h2;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_115 = _c_T_31 == 4'h3;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_116 = _c_T_31 == 4'h4;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_117 = _c_T_31 == 4'h5;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_118 = _c_T_31 == 4'h6;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_119 = _c_T_31 == 4'h7;	// src/main/scala/conv.scala:101:32, :107:41
  wire             _GEN_120 = _c_T_31 == 4'h8;	// src/main/scala/conv.scala:101:32, :107:41
  wire [9:0]       _c_T_32 = (m + 10'h1) % 10'h3;	// src/main/scala/conv.scala:93:22, :98:30, :101:25
  wire [7:0]       _c_T_33 = (_GEN_30 + 8'h2) % 8'h3;	// src/main/scala/conv.scala:99:30, :101:44
  wire [3:0]       _c_T_35 = {2'h0, _c_T_32[1:0]} + {2'h0, _c_T_33[1:0]} * 4'h3;	// src/main/scala/conv.scala:72:25, :101:{25,32,38,44}, :107:41
  wire [8:0]       _kernel_added_T_8 = _GEN_19[_c_T_35] + {1'h0, io_kernel_0};	// src/main/scala/conv.scala:15:7, :101:32, :104:43
  wire             _GEN_121 = _GEN_20[_c_T_35] & _c_T_35 == 4'h0;	// src/main/scala/conv.scala:101:32, :104:43, :106:42, :107:41
  wire             _GEN_122 = _GEN_18 & io_rd_enable_aeq & _aeqMem_io_readData_0[0];	// src/main/scala/conv.scala:39:22, :65:14, :87:{35,55}, :88:28, :91:{19,24}, :106:42
  wire             _GEN_123 = _GEN_20[_c_T_35] & _c_T_35 == 4'h1;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_124 = _GEN_20[_c_T_35] & _c_T_35 == 4'h2;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_125 = _GEN_20[_c_T_35] & _c_T_35 == 4'h3;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_126 = _GEN_20[_c_T_35] & _c_T_35 == 4'h4;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_127 = _GEN_20[_c_T_35] & _c_T_35 == 4'h5;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_128 = _GEN_20[_c_T_35] & _c_T_35 == 4'h6;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_129 = _GEN_20[_c_T_35] & _c_T_35 == 4'h7;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  wire             _GEN_130 = _GEN_20[_c_T_35] & _c_T_35 == 4'h8;	// src/main/scala/conv.scala:101:32, :106:42, :107:41
  always @(posedge clock) begin	// src/main/scala/conv.scala:15:7
    if (reset) begin	// src/main/scala/conv.scala:15:7
      counter <= 8'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      conv_done <= 1'h0;	// src/main/scala/conv.scala:15:7, :85:26
    end
    else begin	// src/main/scala/conv.scala:15:7
      if (_GEN)	// src/main/scala/conv.scala:63:48
        counter <= counter + 8'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24, src/main/scala/conv.scala:99:24
      conv_done <= _GEN_18 & io_rd_enable_aeq | conv_done;	// src/main/scala/conv.scala:85:26, :87:{35,55}, :88:28, :114:17
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/conv.scala:15:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/conv.scala:15:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/conv.scala:15:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/conv.scala:15:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/conv.scala:15:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/conv.scala:15:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/conv.scala:15:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/conv.scala:15:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/conv.scala:15:7
        counter = _RANDOM[/*Zero width*/ 1'b0][8:1];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/conv.scala:15:7
        conv_done = _RANDOM[/*Zero width*/ 1'b0][9];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/conv.scala:15:7, :85:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/conv.scala:15:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/conv.scala:15:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  AEQ aeqMem (	// src/main/scala/conv.scala:39:22
    .clock            (clock),
    .reset            (reset),
    .io_writeEnable_0 (io_wr_enable_aeq_0),
    .io_writeEnable_1 (io_wr_enable_aeq_1),
    .io_writeEnable_2 (io_wr_enable_aeq_2),
    .io_writeEnable_3 (io_wr_enable_aeq_3),
    .io_writeEnable_4 (io_wr_enable_aeq_4),
    .io_writeEnable_5 (io_wr_enable_aeq_5),
    .io_writeEnable_6 (io_wr_enable_aeq_6),
    .io_writeEnable_7 (io_wr_enable_aeq_7),
    .io_writeEnable_8 (io_wr_enable_aeq_8),
    .io_readEnable    (io_rd_enable_aeq),
    .io_writeData_0   (io_writeData_aeq_0),
    .io_writeData_1   (io_writeData_aeq_1),
    .io_writeData_2   (io_writeData_aeq_2),
    .io_writeData_3   (io_writeData_aeq_3),
    .io_writeData_4   (io_writeData_aeq_4),
    .io_writeData_5   (io_writeData_aeq_5),
    .io_writeData_6   (io_writeData_aeq_6),
    .io_writeData_7   (io_writeData_aeq_7),
    .io_writeData_8   (io_writeData_aeq_8),
    .io_readData_0    (_aeqMem_io_readData_0),
    .io_readData_1    (io_readData_aeq_1),
    .io_readData_2    (io_readData_aeq_2),
    .io_readData_3    (io_readData_aeq_3),
    .io_readData_4    (io_readData_aeq_4),
    .io_readData_5    (io_readData_aeq_5),
    .io_readData_6    (io_readData_aeq_6),
    .io_readData_7    (io_readData_aeq_7),
    .io_readData_8    (io_readData_aeq_8)
  );
  mempot mempotMem (	// src/main/scala/conv.scala:40:25
    .clock          (clock),
    .io_wr_enable_0
      (_GEN_122
         ? _GEN_121
           | (_GEN_20[_c_T_31] ? _GEN_112 | _GEN_103 | _GEN_86 : _GEN_103 | _GEN_86)
         : _GEN_0),	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :106:42, :107:41
    .io_wr_enable_1
      (_GEN_122
         ? _GEN_123
           | (_GEN_20[_c_T_31] ? _GEN_113 | _GEN_104 | _GEN_88 : _GEN_104 | _GEN_88)
         : _GEN_2),	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :106:42, :107:41
    .io_wr_enable_2
      (_GEN_122
         ? _GEN_124
           | (_GEN_20[_c_T_31] ? _GEN_114 | _GEN_105 | _GEN_90 : _GEN_105 | _GEN_90)
         : _GEN_4),	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :106:42, :107:41
    .io_wr_enable_3
      (_GEN_122
         ? _GEN_125
           | (_GEN_20[_c_T_31] ? _GEN_115 | _GEN_106 | _GEN_92 : _GEN_106 | _GEN_92)
         : _GEN_6),	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :106:42, :107:41
    .io_wr_enable_4
      (_GEN_122
         ? _GEN_126
           | (_GEN_20[_c_T_31] ? _GEN_116 | _GEN_107 | _GEN_94 : _GEN_107 | _GEN_94)
         : _GEN_8),	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :106:42, :107:41
    .io_wr_enable_5
      (_GEN_122
         ? _GEN_127
           | (_GEN_20[_c_T_31] ? _GEN_117 | _GEN_108 | _GEN_96 : _GEN_108 | _GEN_96)
         : _GEN_10),	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :106:42, :107:41
    .io_wr_enable_6
      (_GEN_122
         ? _GEN_128
           | (_GEN_20[_c_T_31] ? _GEN_118 | _GEN_109 | _GEN_98 : _GEN_109 | _GEN_98)
         : _GEN_12),	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :106:42, :107:41
    .io_wr_enable_7
      (_GEN_122
         ? _GEN_129
           | (_GEN_20[_c_T_31] ? _GEN_119 | _GEN_110 | _GEN_100 : _GEN_110 | _GEN_100)
         : _GEN_14),	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :106:42, :107:41
    .io_wr_enable_8
      (_GEN_122
         ? _GEN_130
           | (_GEN_20[_c_T_31] ? _GEN_120 | _GEN_111 | _GEN_102 : _GEN_111 | _GEN_102)
         : _GEN_16),	// src/main/scala/conv.scala:47:26, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :106:42, :107:41
    .io_rd_enable_0 (io_rd_enable_mempot_0),
    .io_rd_enable_1 (io_rd_enable_mempot_1),
    .io_rd_enable_2 (io_rd_enable_mempot_2),
    .io_rd_enable_3 (io_rd_enable_mempot_3),
    .io_rd_enable_4 (io_rd_enable_mempot_4),
    .io_rd_enable_5 (io_rd_enable_mempot_5),
    .io_rd_enable_6 (io_rd_enable_mempot_6),
    .io_rd_enable_7 (io_rd_enable_mempot_7),
    .io_rd_enable_8 (io_rd_enable_mempot_8),
    .io_addr_r_0    (io_addr_r_mempot_0),
    .io_addr_r_1    (io_addr_r_mempot_1),
    .io_addr_r_2    (io_addr_r_mempot_2),
    .io_addr_r_3    (io_addr_r_mempot_3),
    .io_addr_r_4    (io_addr_r_mempot_4),
    .io_addr_r_5    (io_addr_r_mempot_5),
    .io_addr_r_6    (io_addr_r_mempot_6),
    .io_addr_r_7    (io_addr_r_mempot_7),
    .io_addr_r_8    (io_addr_r_mempot_8),
    .io_addr_w_0    (io_addr_w_mempot_0),
    .io_addr_w_1    (io_addr_w_mempot_1),
    .io_addr_w_2    (io_addr_w_mempot_2),
    .io_addr_w_3    (io_addr_w_mempot_3),
    .io_addr_w_4    (io_addr_w_mempot_4),
    .io_addr_w_5    (io_addr_w_mempot_5),
    .io_addr_w_6    (io_addr_w_mempot_6),
    .io_addr_w_7    (io_addr_w_mempot_7),
    .io_addr_w_8    (io_addr_w_mempot_8),
    .io_din_0
      (_GEN_122
         ? (_GEN_121
              ? _kernel_added_T_8
              : _GEN_20[_c_T_31] & _GEN_112
                  ? _kernel_added_T_7
                  : _GEN_103
                      ? _kernel_added_T_6
                      : _GEN_20[_c_T_23] & _GEN_85
                          ? _kernel_added_T_5
                          : _GEN_76
                              ? _kernel_added_T_4
                              : _GEN_20[_c_T_15] & _GEN_58
                                  ? _kernel_added_T_3
                                  : _GEN_49
                                      ? _kernel_added_T_2
                                      : _GEN_20[_c_T_7] & _GEN_31
                                          ? _kernel_added_T_1
                                          : _GEN_21 ? _kernel_added_T : _GEN_1)
         : _GEN_1),	// src/main/scala/conv.scala:51:20, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :104:43, :106:42, :107:41, :108:35
    .io_din_1
      (_GEN_122
         ? (_GEN_123
              ? _kernel_added_T_8
              : _GEN_20[_c_T_31] & _GEN_113
                  ? _kernel_added_T_7
                  : _GEN_104
                      ? _kernel_added_T_6
                      : _GEN_20[_c_T_23] & _GEN_87
                          ? _kernel_added_T_5
                          : _GEN_77
                              ? _kernel_added_T_4
                              : _GEN_20[_c_T_15] & _GEN_60
                                  ? _kernel_added_T_3
                                  : _GEN_50
                                      ? _kernel_added_T_2
                                      : _GEN_20[_c_T_7] & _GEN_33
                                          ? _kernel_added_T_1
                                          : _GEN_22 ? _kernel_added_T : _GEN_3)
         : _GEN_3),	// src/main/scala/conv.scala:51:20, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :104:43, :106:42, :107:41, :108:35
    .io_din_2
      (_GEN_122
         ? (_GEN_124
              ? _kernel_added_T_8
              : _GEN_20[_c_T_31] & _GEN_114
                  ? _kernel_added_T_7
                  : _GEN_105
                      ? _kernel_added_T_6
                      : _GEN_20[_c_T_23] & _GEN_89
                          ? _kernel_added_T_5
                          : _GEN_78
                              ? _kernel_added_T_4
                              : _GEN_20[_c_T_15] & _GEN_62
                                  ? _kernel_added_T_3
                                  : _GEN_51
                                      ? _kernel_added_T_2
                                      : _GEN_20[_c_T_7] & _GEN_35
                                          ? _kernel_added_T_1
                                          : _GEN_23 ? _kernel_added_T : _GEN_5)
         : _GEN_5),	// src/main/scala/conv.scala:51:20, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :104:43, :106:42, :107:41, :108:35
    .io_din_3
      (_GEN_122
         ? (_GEN_125
              ? _kernel_added_T_8
              : _GEN_20[_c_T_31] & _GEN_115
                  ? _kernel_added_T_7
                  : _GEN_106
                      ? _kernel_added_T_6
                      : _GEN_20[_c_T_23] & _GEN_91
                          ? _kernel_added_T_5
                          : _GEN_79
                              ? _kernel_added_T_4
                              : _GEN_20[_c_T_15] & _GEN_64
                                  ? _kernel_added_T_3
                                  : _GEN_52
                                      ? _kernel_added_T_2
                                      : _GEN_20[_c_T_7] & _GEN_37
                                          ? _kernel_added_T_1
                                          : _GEN_24 ? _kernel_added_T : _GEN_7)
         : _GEN_7),	// src/main/scala/conv.scala:51:20, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :104:43, :106:42, :107:41, :108:35
    .io_din_4
      (_GEN_122
         ? (_GEN_126
              ? _kernel_added_T_8
              : _GEN_20[_c_T_31] & _GEN_116
                  ? _kernel_added_T_7
                  : _GEN_107
                      ? _kernel_added_T_6
                      : _GEN_20[_c_T_23] & _GEN_93
                          ? _kernel_added_T_5
                          : _GEN_80
                              ? _kernel_added_T_4
                              : _GEN_20[_c_T_15] & _GEN_66
                                  ? _kernel_added_T_3
                                  : _GEN_53
                                      ? _kernel_added_T_2
                                      : _GEN_20[_c_T_7] & _GEN_39
                                          ? _kernel_added_T_1
                                          : _GEN_25 ? _kernel_added_T : _GEN_9)
         : _GEN_9),	// src/main/scala/conv.scala:51:20, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :104:43, :106:42, :107:41, :108:35
    .io_din_5
      (_GEN_122
         ? (_GEN_127
              ? _kernel_added_T_8
              : _GEN_20[_c_T_31] & _GEN_117
                  ? _kernel_added_T_7
                  : _GEN_108
                      ? _kernel_added_T_6
                      : _GEN_20[_c_T_23] & _GEN_95
                          ? _kernel_added_T_5
                          : _GEN_81
                              ? _kernel_added_T_4
                              : _GEN_20[_c_T_15] & _GEN_68
                                  ? _kernel_added_T_3
                                  : _GEN_54
                                      ? _kernel_added_T_2
                                      : _GEN_20[_c_T_7] & _GEN_41
                                          ? _kernel_added_T_1
                                          : _GEN_26 ? _kernel_added_T : _GEN_11)
         : _GEN_11),	// src/main/scala/conv.scala:51:20, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :104:43, :106:42, :107:41, :108:35
    .io_din_6
      (_GEN_122
         ? (_GEN_128
              ? _kernel_added_T_8
              : _GEN_20[_c_T_31] & _GEN_118
                  ? _kernel_added_T_7
                  : _GEN_109
                      ? _kernel_added_T_6
                      : _GEN_20[_c_T_23] & _GEN_97
                          ? _kernel_added_T_5
                          : _GEN_82
                              ? _kernel_added_T_4
                              : _GEN_20[_c_T_15] & _GEN_70
                                  ? _kernel_added_T_3
                                  : _GEN_55
                                      ? _kernel_added_T_2
                                      : _GEN_20[_c_T_7] & _GEN_43
                                          ? _kernel_added_T_1
                                          : _GEN_27 ? _kernel_added_T : _GEN_13)
         : _GEN_13),	// src/main/scala/conv.scala:51:20, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :104:43, :106:42, :107:41, :108:35
    .io_din_7
      (_GEN_122
         ? (_GEN_129
              ? _kernel_added_T_8
              : _GEN_20[_c_T_31] & _GEN_119
                  ? _kernel_added_T_7
                  : _GEN_110
                      ? _kernel_added_T_6
                      : _GEN_20[_c_T_23] & _GEN_99
                          ? _kernel_added_T_5
                          : _GEN_83
                              ? _kernel_added_T_4
                              : _GEN_20[_c_T_15] & _GEN_72
                                  ? _kernel_added_T_3
                                  : _GEN_56
                                      ? _kernel_added_T_2
                                      : _GEN_20[_c_T_7] & _GEN_45
                                          ? _kernel_added_T_1
                                          : _GEN_28 ? _kernel_added_T : _GEN_15)
         : _GEN_15),	// src/main/scala/conv.scala:51:20, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :104:43, :106:42, :107:41, :108:35
    .io_din_8
      (_GEN_122
         ? (_GEN_130
              ? _kernel_added_T_8
              : _GEN_20[_c_T_31] & _GEN_120
                  ? _kernel_added_T_7
                  : _GEN_111
                      ? _kernel_added_T_6
                      : _GEN_20[_c_T_23] & _GEN_101
                          ? _kernel_added_T_5
                          : _GEN_84
                              ? _kernel_added_T_4
                              : _GEN_20[_c_T_15] & _GEN_74
                                  ? _kernel_added_T_3
                                  : _GEN_57
                                      ? _kernel_added_T_2
                                      : _GEN_20[_c_T_7] & _GEN_47
                                          ? _kernel_added_T_1
                                          : _GEN_29 ? _kernel_added_T : _GEN_17)
         : _GEN_17),	// src/main/scala/conv.scala:51:20, :65:14, :74:30, :87:55, :88:28, :91:24, :101:32, :104:43, :106:42, :107:41, :108:35
    .io_dout_0      (_mempotMem_io_dout_0),
    .io_dout_1      (_mempotMem_io_dout_1),
    .io_dout_2      (_mempotMem_io_dout_2),
    .io_dout_3      (_mempotMem_io_dout_3),
    .io_dout_4      (_mempotMem_io_dout_4),
    .io_dout_5      (_mempotMem_io_dout_5),
    .io_dout_6      (_mempotMem_io_dout_6),
    .io_dout_7      (_mempotMem_io_dout_7),
    .io_dout_8      (_mempotMem_io_dout_8)
  );
  assign io_readData_aeq_0 = _aeqMem_io_readData_0;	// src/main/scala/conv.scala:15:7, :39:22
  assign io_dout_mempot_0 = _mempotMem_io_dout_0;	// src/main/scala/conv.scala:15:7, :40:25
  assign io_dout_mempot_1 = _mempotMem_io_dout_1;	// src/main/scala/conv.scala:15:7, :40:25
  assign io_dout_mempot_2 = _mempotMem_io_dout_2;	// src/main/scala/conv.scala:15:7, :40:25
  assign io_dout_mempot_3 = _mempotMem_io_dout_3;	// src/main/scala/conv.scala:15:7, :40:25
  assign io_dout_mempot_4 = _mempotMem_io_dout_4;	// src/main/scala/conv.scala:15:7, :40:25
  assign io_dout_mempot_5 = _mempotMem_io_dout_5;	// src/main/scala/conv.scala:15:7, :40:25
  assign io_dout_mempot_6 = _mempotMem_io_dout_6;	// src/main/scala/conv.scala:15:7, :40:25
  assign io_dout_mempot_7 = _mempotMem_io_dout_7;	// src/main/scala/conv.scala:15:7, :40:25
  assign io_dout_mempot_8 = _mempotMem_io_dout_8;	// src/main/scala/conv.scala:15:7, :40:25
endmodule

