// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// VCS coverage exclude_file
module mem_256x8(	// src/main/scala/simpleMemory.scala:28:24
  input  [7:0] R0_addr,
  input        R0_en,
               R0_clk,
  output [7:0] R0_data,
  input  [7:0] W0_addr,
  input        W0_en,
               W0_clk,
  input  [7:0] W0_data
);

  reg [7:0] Memory[0:255];	// src/main/scala/simpleMemory.scala:28:24
  reg       _R0_en_d0;	// src/main/scala/simpleMemory.scala:28:24
  reg [7:0] _R0_addr_d0;	// src/main/scala/simpleMemory.scala:28:24
  always @(posedge R0_clk) begin	// src/main/scala/simpleMemory.scala:28:24
    _R0_en_d0 <= R0_en;	// src/main/scala/simpleMemory.scala:28:24
    _R0_addr_d0 <= R0_addr;	// src/main/scala/simpleMemory.scala:28:24
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/simpleMemory.scala:28:24
    if (W0_en & 1'h1)	// src/main/scala/simpleMemory.scala:28:24
      Memory[W0_addr] <= W0_data;	// src/main/scala/simpleMemory.scala:28:24
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/simpleMemory.scala:28:24
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/simpleMemory.scala:28:24
      reg [31:0] _RANDOM;	// src/main/scala/simpleMemory.scala:28:24
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/simpleMemory.scala:28:24
    initial begin	// src/main/scala/simpleMemory.scala:28:24
      `INIT_RANDOM_PROLOG_	// src/main/scala/simpleMemory.scala:28:24
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/simpleMemory.scala:28:24
        for (logic [8:0] i = 9'h0; i < 9'h100; i += 9'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/simpleMemory.scala:28:24
          Memory[i[7:0]] = _RANDOM_MEM[7:0];	// src/main/scala/simpleMemory.scala:28:24
        end	// src/main/scala/simpleMemory.scala:28:24
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/simpleMemory.scala:28:24
        _RANDOM = {`RANDOM};	// src/main/scala/simpleMemory.scala:28:24
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/simpleMemory.scala:28:24
        _R0_addr_d0 = _RANDOM[8:1];	// src/main/scala/simpleMemory.scala:28:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 8'bx;	// src/main/scala/simpleMemory.scala:28:24
endmodule

module SimpleMemory(	// src/main/scala/simpleMemory.scala:17:7
  input        clock,	// src/main/scala/simpleMemory.scala:17:7
               reset,	// src/main/scala/simpleMemory.scala:17:7
  input  [7:0] io_wrAddr,	// src/main/scala/simpleMemory.scala:18:14
               io_wrData,	// src/main/scala/simpleMemory.scala:18:14
  input        io_wrEna,	// src/main/scala/simpleMemory.scala:18:14
  input  [7:0] io_rdAddr,	// src/main/scala/simpleMemory.scala:18:14
  output [7:0] io_rdData,	// src/main/scala/simpleMemory.scala:18:14
  input        io_rdEna	// src/main/scala/simpleMemory.scala:18:14
);

  mem_256x8 mem_ext (	// src/main/scala/simpleMemory.scala:28:24
    .R0_addr (io_rdAddr),
    .R0_en   (io_rdEna),
    .R0_clk  (clock),
    .R0_data (io_rdData),
    .W0_addr (io_wrAddr),
    .W0_en   (io_wrEna),
    .W0_clk  (clock),
    .W0_data (io_wrData)
  );
endmodule

