// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module AeqReadStage(	// src/main/scala/tile_test/aeq.scala:22:7
  input        clock,	// src/main/scala/tile_test/aeq.scala:22:7
               reset,	// src/main/scala/tile_test/aeq.scala:22:7
               io_conv_en,	// src/main/scala/tile_test/aeq.scala:23:16
  output       io_conv_done,	// src/main/scala/tile_test/aeq.scala:23:16
  output [9:0] io_ai_rdaddr_0,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rdaddr_1,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rdaddr_2,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rdaddr_3,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rdaddr_4,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rdaddr_5,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rdaddr_6,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rdaddr_7,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rdaddr_8,	// src/main/scala/tile_test/aeq.scala:23:16
  input  [9:0] io_ai_rddata_0,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rddata_1,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rddata_2,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rddata_3,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rddata_4,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rddata_5,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rddata_6,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rddata_7,	// src/main/scala/tile_test/aeq.scala:23:16
               io_ai_rddata_8,	// src/main/scala/tile_test/aeq.scala:23:16
  output [9:0] io_spike_event,	// src/main/scala/tile_test/aeq.scala:23:16
  output       io_spike_valid,	// src/main/scala/tile_test/aeq.scala:23:16
               io_eoq_bit	// src/main/scala/tile_test/aeq.scala:23:16
);

  reg  [3:0] aeq_read_col_sel_counter;	// src/main/scala/tile_test/aeq.scala:25:43
  reg  [9:0] aeq_read_addr;	// src/main/scala/tile_test/aeq.scala:26:32
  reg  [9:0] spike_event_reg;	// src/main/scala/tile_test/aeq.scala:28:34
  reg        spike_valid_reg;	// src/main/scala/tile_test/aeq.scala:29:34
  reg        eoq_bit_reg;	// src/main/scala/tile_test/aeq.scala:30:30
  wire       read_en = aeq_read_col_sel_counter < 4'h9;	// src/main/scala/tile_test/aeq.scala:25:43, :44:35
  wire       _GEN = aeq_read_col_sel_counter == 4'h0;	// src/main/scala/tile_test/aeq.scala:25:43, :45:48
  wire       _GEN_0 = aeq_read_col_sel_counter == 4'h1;	// src/main/scala/tile_test/aeq.scala:25:43, :45:48
  wire       _GEN_1 = aeq_read_col_sel_counter == 4'h2;	// src/main/scala/tile_test/aeq.scala:25:43, :45:48
  wire       _GEN_2 = aeq_read_col_sel_counter == 4'h3;	// src/main/scala/tile_test/aeq.scala:25:43, :45:48
  wire       _GEN_3 = aeq_read_col_sel_counter == 4'h4;	// src/main/scala/tile_test/aeq.scala:25:43, :45:48
  wire       _GEN_4 = aeq_read_col_sel_counter == 4'h5;	// src/main/scala/tile_test/aeq.scala:25:43, :45:48
  wire       _GEN_5 = aeq_read_col_sel_counter == 4'h6;	// src/main/scala/tile_test/aeq.scala:25:43, :45:48
  wire       _GEN_6 = aeq_read_col_sel_counter == 4'h7;	// src/main/scala/tile_test/aeq.scala:25:43, :45:48
  wire       _GEN_7 = aeq_read_col_sel_counter == 4'h8;	// src/main/scala/tile_test/aeq.scala:25:43, :45:48
  wire [9:0] selected_data =
    _GEN_7
      ? io_ai_rddata_8
      : _GEN_6
          ? io_ai_rddata_7
          : _GEN_5
              ? io_ai_rddata_6
              : _GEN_4
                  ? io_ai_rddata_5
                  : _GEN_3
                      ? io_ai_rddata_4
                      : _GEN_2
                          ? io_ai_rddata_3
                          : _GEN_1
                              ? io_ai_rddata_2
                              : _GEN_0 ? io_ai_rddata_1 : _GEN ? io_ai_rddata_0 : 10'h0;	// src/main/scala/tile_test/aeq.scala:26:32, :45:48, :50:19, :52:48, :53:27
  wire       _GEN_8 = io_conv_en & read_en;	// src/main/scala/tile_test/aeq.scala:44:35, :60:21
  always @(posedge clock) begin	// src/main/scala/tile_test/aeq.scala:22:7
    if (reset) begin	// src/main/scala/tile_test/aeq.scala:22:7
      aeq_read_col_sel_counter <= 4'h0;	// src/main/scala/tile_test/aeq.scala:25:43
      aeq_read_addr <= 10'h0;	// src/main/scala/tile_test/aeq.scala:26:32
      spike_event_reg <= 10'h0;	// src/main/scala/tile_test/aeq.scala:26:32, :28:34
      spike_valid_reg <= 1'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :29:34
      eoq_bit_reg <= 1'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :30:30
    end
    else begin	// src/main/scala/tile_test/aeq.scala:22:7
      if (_GEN_8) begin	// src/main/scala/tile_test/aeq.scala:60:21
        if (selected_data[9]) begin	// src/main/scala/tile_test/aeq.scala:52:48, :53:27, :58:32
          if (_GEN_7)	// src/main/scala/tile_test/aeq.scala:45:48
            aeq_read_col_sel_counter <= 4'h0;	// src/main/scala/tile_test/aeq.scala:25:43
          else	// src/main/scala/tile_test/aeq.scala:45:48
            aeq_read_col_sel_counter <= aeq_read_col_sel_counter + 4'h1;	// src/main/scala/tile_test/aeq.scala:25:43, :45:48, :71:70
        end
        spike_event_reg <= selected_data;	// src/main/scala/tile_test/aeq.scala:28:34, :52:48, :53:27
        spike_valid_reg <= selected_data[0];	// src/main/scala/tile_test/aeq.scala:29:34, :52:48, :53:27, :57:36
        eoq_bit_reg <= selected_data[9];	// src/main/scala/tile_test/aeq.scala:30:30, :52:48, :53:27, :58:32
      end
      else	// src/main/scala/tile_test/aeq.scala:60:21
        aeq_read_col_sel_counter <= 4'h0;	// src/main/scala/tile_test/aeq.scala:25:43
      if (~_GEN_8 | selected_data[9])	// src/main/scala/tile_test/aeq.scala:52:48, :53:27, :58:32, :60:{21,33}, :65:23, :78:23
        aeq_read_addr <= 10'h0;	// src/main/scala/tile_test/aeq.scala:26:32
      else if (selected_data[0])	// src/main/scala/tile_test/aeq.scala:52:48, :53:27, :57:36
        aeq_read_addr <= aeq_read_addr + 10'h1;	// src/main/scala/tile_test/aeq.scala:26:32, :74:44
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/tile_test/aeq.scala:22:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/tile_test/aeq.scala:22:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/tile_test/aeq.scala:22:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/tile_test/aeq.scala:22:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/tile_test/aeq.scala:22:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/tile_test/aeq.scala:22:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/tile_test/aeq.scala:22:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/tile_test/aeq.scala:22:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/tile_test/aeq.scala:22:7
        aeq_read_col_sel_counter = _RANDOM[/*Zero width*/ 1'b0][3:0];	// src/main/scala/tile_test/aeq.scala:22:7, :25:43
        aeq_read_addr = _RANDOM[/*Zero width*/ 1'b0][13:4];	// src/main/scala/tile_test/aeq.scala:22:7, :25:43, :26:32
        spike_event_reg = _RANDOM[/*Zero width*/ 1'b0][23:14];	// src/main/scala/tile_test/aeq.scala:22:7, :25:43, :28:34
        spike_valid_reg = _RANDOM[/*Zero width*/ 1'b0][24];	// src/main/scala/tile_test/aeq.scala:22:7, :25:43, :29:34
        eoq_bit_reg = _RANDOM[/*Zero width*/ 1'b0][25];	// src/main/scala/tile_test/aeq.scala:22:7, :25:43, :30:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/tile_test/aeq.scala:22:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/tile_test/aeq.scala:22:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_conv_done = _GEN_8 & selected_data[9] & _GEN_7;	// src/main/scala/tile_test/aeq.scala:22:7, :38:18, :45:48, :52:48, :53:27, :58:32, :60:{21,33}, :65:23, :67:52
  assign io_ai_rdaddr_0 = read_en & _GEN ? aeq_read_addr : 10'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :26:32, :41:25, :44:{35,42}, :45:48
  assign io_ai_rdaddr_1 = read_en & _GEN_0 ? aeq_read_addr : 10'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :26:32, :41:25, :44:{35,42}, :45:48
  assign io_ai_rdaddr_2 = read_en & _GEN_1 ? aeq_read_addr : 10'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :26:32, :41:25, :44:{35,42}, :45:48
  assign io_ai_rdaddr_3 = read_en & _GEN_2 ? aeq_read_addr : 10'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :26:32, :41:25, :44:{35,42}, :45:48
  assign io_ai_rdaddr_4 = read_en & _GEN_3 ? aeq_read_addr : 10'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :26:32, :41:25, :44:{35,42}, :45:48
  assign io_ai_rdaddr_5 = read_en & _GEN_4 ? aeq_read_addr : 10'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :26:32, :41:25, :44:{35,42}, :45:48
  assign io_ai_rdaddr_6 = read_en & _GEN_5 ? aeq_read_addr : 10'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :26:32, :41:25, :44:{35,42}, :45:48
  assign io_ai_rdaddr_7 = read_en & _GEN_6 ? aeq_read_addr : 10'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :26:32, :41:25, :44:{35,42}, :45:48
  assign io_ai_rdaddr_8 = read_en & _GEN_7 ? aeq_read_addr : 10'h0;	// src/main/scala/tile_test/aeq.scala:22:7, :26:32, :41:25, :44:{35,42}, :45:48
  assign io_spike_event = spike_event_reg;	// src/main/scala/tile_test/aeq.scala:22:7, :28:34
  assign io_spike_valid = spike_valid_reg;	// src/main/scala/tile_test/aeq.scala:22:7, :29:34
  assign io_eoq_bit = eoq_bit_reg;	// src/main/scala/tile_test/aeq.scala:22:7, :30:30
endmodule

// external module tdpb_init

// external module tdpb_init

// external module tdpb_init

// external module tdpb_init

// external module tdpb_init

// external module tdpb_init

// external module tdpb_init

// external module tdpb_init

// external module tdpb_init

module TopLevelModule(	// src/main/scala/tile_test/aeq.scala:83:7
  input        clock,	// src/main/scala/tile_test/aeq.scala:83:7
               reset,	// src/main/scala/tile_test/aeq.scala:83:7
               io_conv_en,	// src/main/scala/tile_test/aeq.scala:84:16
  output       io_conv_done,	// src/main/scala/tile_test/aeq.scala:84:16
  output [9:0] io_spike_event,	// src/main/scala/tile_test/aeq.scala:84:16
  output       io_spike_valid,	// src/main/scala/tile_test/aeq.scala:84:16
               io_eoq_bit	// src/main/scala/tile_test/aeq.scala:84:16
);

  wire [9:0] _tdpb_init_8_doa;	// src/main/scala/tile_test/aeq.scala:103:31
  wire [9:0] _tdpb_init_7_doa;	// src/main/scala/tile_test/aeq.scala:103:31
  wire [9:0] _tdpb_init_6_doa;	// src/main/scala/tile_test/aeq.scala:103:31
  wire [9:0] _tdpb_init_5_doa;	// src/main/scala/tile_test/aeq.scala:103:31
  wire [9:0] _tdpb_init_4_doa;	// src/main/scala/tile_test/aeq.scala:103:31
  wire [9:0] _tdpb_init_3_doa;	// src/main/scala/tile_test/aeq.scala:103:31
  wire [9:0] _tdpb_init_2_doa;	// src/main/scala/tile_test/aeq.scala:103:31
  wire [9:0] _tdpb_init_1_doa;	// src/main/scala/tile_test/aeq.scala:103:31
  wire [9:0] _tdpb_init_doa;	// src/main/scala/tile_test/aeq.scala:103:31
  wire [9:0] _aeqReadStage_io_ai_rdaddr_0;	// src/main/scala/tile_test/aeq.scala:93:30
  wire [9:0] _aeqReadStage_io_ai_rdaddr_1;	// src/main/scala/tile_test/aeq.scala:93:30
  wire [9:0] _aeqReadStage_io_ai_rdaddr_2;	// src/main/scala/tile_test/aeq.scala:93:30
  wire [9:0] _aeqReadStage_io_ai_rdaddr_3;	// src/main/scala/tile_test/aeq.scala:93:30
  wire [9:0] _aeqReadStage_io_ai_rdaddr_4;	// src/main/scala/tile_test/aeq.scala:93:30
  wire [9:0] _aeqReadStage_io_ai_rdaddr_5;	// src/main/scala/tile_test/aeq.scala:93:30
  wire [9:0] _aeqReadStage_io_ai_rdaddr_6;	// src/main/scala/tile_test/aeq.scala:93:30
  wire [9:0] _aeqReadStage_io_ai_rdaddr_7;	// src/main/scala/tile_test/aeq.scala:93:30
  wire [9:0] _aeqReadStage_io_ai_rdaddr_8;	// src/main/scala/tile_test/aeq.scala:93:30
  AeqReadStage aeqReadStage (	// src/main/scala/tile_test/aeq.scala:93:30
    .clock          (clock),
    .reset          (reset),
    .io_conv_en     (io_conv_en),
    .io_conv_done   (io_conv_done),
    .io_ai_rdaddr_0 (_aeqReadStage_io_ai_rdaddr_0),
    .io_ai_rdaddr_1 (_aeqReadStage_io_ai_rdaddr_1),
    .io_ai_rdaddr_2 (_aeqReadStage_io_ai_rdaddr_2),
    .io_ai_rdaddr_3 (_aeqReadStage_io_ai_rdaddr_3),
    .io_ai_rdaddr_4 (_aeqReadStage_io_ai_rdaddr_4),
    .io_ai_rdaddr_5 (_aeqReadStage_io_ai_rdaddr_5),
    .io_ai_rdaddr_6 (_aeqReadStage_io_ai_rdaddr_6),
    .io_ai_rdaddr_7 (_aeqReadStage_io_ai_rdaddr_7),
    .io_ai_rdaddr_8 (_aeqReadStage_io_ai_rdaddr_8),
    .io_ai_rddata_0 (_tdpb_init_doa),	// src/main/scala/tile_test/aeq.scala:103:31
    .io_ai_rddata_1 (_tdpb_init_1_doa),	// src/main/scala/tile_test/aeq.scala:103:31
    .io_ai_rddata_2 (_tdpb_init_2_doa),	// src/main/scala/tile_test/aeq.scala:103:31
    .io_ai_rddata_3 (_tdpb_init_3_doa),	// src/main/scala/tile_test/aeq.scala:103:31
    .io_ai_rddata_4 (_tdpb_init_4_doa),	// src/main/scala/tile_test/aeq.scala:103:31
    .io_ai_rddata_5 (_tdpb_init_5_doa),	// src/main/scala/tile_test/aeq.scala:103:31
    .io_ai_rddata_6 (_tdpb_init_6_doa),	// src/main/scala/tile_test/aeq.scala:103:31
    .io_ai_rddata_7 (_tdpb_init_7_doa),	// src/main/scala/tile_test/aeq.scala:103:31
    .io_ai_rddata_8 (_tdpb_init_8_doa),	// src/main/scala/tile_test/aeq.scala:103:31
    .io_spike_event (io_spike_event),
    .io_spike_valid (io_spike_valid),
    .io_eoq_bit     (io_eoq_bit)
  );
  tdpb_init #(
    .ADDR_WIDTH(10),
    .DATA_WIDTH(10),
    .INIT_FILE("ai_0.mem")
  ) tdpb_init (	// src/main/scala/tile_test/aeq.scala:103:31
    .clka  (clock),
    .clkb  (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .ena   (1'h1),	// src/main/scala/tile_test/aeq.scala:114:22
    .enb   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .wea   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .web   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .addra (_aeqReadStage_io_ai_rdaddr_0),	// src/main/scala/tile_test/aeq.scala:93:30
    .addrb (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dia   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dib   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .doa   (_tdpb_init_doa),
    .dob   (/* unused */)
  );
  tdpb_init #(
    .ADDR_WIDTH(10),
    .DATA_WIDTH(10),
    .INIT_FILE("ai_1.mem")
  ) tdpb_init_1 (	// src/main/scala/tile_test/aeq.scala:103:31
    .clka  (clock),
    .clkb  (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .ena   (1'h1),	// src/main/scala/tile_test/aeq.scala:114:22
    .enb   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .wea   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .web   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .addra (_aeqReadStage_io_ai_rdaddr_1),	// src/main/scala/tile_test/aeq.scala:93:30
    .addrb (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dia   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dib   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .doa   (_tdpb_init_1_doa),
    .dob   (/* unused */)
  );
  tdpb_init #(
    .ADDR_WIDTH(10),
    .DATA_WIDTH(10),
    .INIT_FILE("ai_2.mem")
  ) tdpb_init_2 (	// src/main/scala/tile_test/aeq.scala:103:31
    .clka  (clock),
    .clkb  (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .ena   (1'h1),	// src/main/scala/tile_test/aeq.scala:114:22
    .enb   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .wea   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .web   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .addra (_aeqReadStage_io_ai_rdaddr_2),	// src/main/scala/tile_test/aeq.scala:93:30
    .addrb (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dia   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dib   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .doa   (_tdpb_init_2_doa),
    .dob   (/* unused */)
  );
  tdpb_init #(
    .ADDR_WIDTH(10),
    .DATA_WIDTH(10),
    .INIT_FILE("ai_3.mem")
  ) tdpb_init_3 (	// src/main/scala/tile_test/aeq.scala:103:31
    .clka  (clock),
    .clkb  (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .ena   (1'h1),	// src/main/scala/tile_test/aeq.scala:114:22
    .enb   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .wea   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .web   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .addra (_aeqReadStage_io_ai_rdaddr_3),	// src/main/scala/tile_test/aeq.scala:93:30
    .addrb (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dia   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dib   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .doa   (_tdpb_init_3_doa),
    .dob   (/* unused */)
  );
  tdpb_init #(
    .ADDR_WIDTH(10),
    .DATA_WIDTH(10),
    .INIT_FILE("ai_4.mem")
  ) tdpb_init_4 (	// src/main/scala/tile_test/aeq.scala:103:31
    .clka  (clock),
    .clkb  (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .ena   (1'h1),	// src/main/scala/tile_test/aeq.scala:114:22
    .enb   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .wea   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .web   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .addra (_aeqReadStage_io_ai_rdaddr_4),	// src/main/scala/tile_test/aeq.scala:93:30
    .addrb (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dia   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dib   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .doa   (_tdpb_init_4_doa),
    .dob   (/* unused */)
  );
  tdpb_init #(
    .ADDR_WIDTH(10),
    .DATA_WIDTH(10),
    .INIT_FILE("ai_5.mem")
  ) tdpb_init_5 (	// src/main/scala/tile_test/aeq.scala:103:31
    .clka  (clock),
    .clkb  (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .ena   (1'h1),	// src/main/scala/tile_test/aeq.scala:114:22
    .enb   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .wea   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .web   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .addra (_aeqReadStage_io_ai_rdaddr_5),	// src/main/scala/tile_test/aeq.scala:93:30
    .addrb (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dia   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dib   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .doa   (_tdpb_init_5_doa),
    .dob   (/* unused */)
  );
  tdpb_init #(
    .ADDR_WIDTH(10),
    .DATA_WIDTH(10),
    .INIT_FILE("ai_6.mem")
  ) tdpb_init_6 (	// src/main/scala/tile_test/aeq.scala:103:31
    .clka  (clock),
    .clkb  (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .ena   (1'h1),	// src/main/scala/tile_test/aeq.scala:114:22
    .enb   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .wea   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .web   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .addra (_aeqReadStage_io_ai_rdaddr_6),	// src/main/scala/tile_test/aeq.scala:93:30
    .addrb (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dia   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dib   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .doa   (_tdpb_init_6_doa),
    .dob   (/* unused */)
  );
  tdpb_init #(
    .ADDR_WIDTH(10),
    .DATA_WIDTH(10),
    .INIT_FILE("ai_7.mem")
  ) tdpb_init_7 (	// src/main/scala/tile_test/aeq.scala:103:31
    .clka  (clock),
    .clkb  (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .ena   (1'h1),	// src/main/scala/tile_test/aeq.scala:114:22
    .enb   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .wea   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .web   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .addra (_aeqReadStage_io_ai_rdaddr_7),	// src/main/scala/tile_test/aeq.scala:93:30
    .addrb (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dia   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dib   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .doa   (_tdpb_init_7_doa),
    .dob   (/* unused */)
  );
  tdpb_init #(
    .ADDR_WIDTH(10),
    .DATA_WIDTH(10),
    .INIT_FILE("ai_8.mem")
  ) tdpb_init_8 (	// src/main/scala/tile_test/aeq.scala:103:31
    .clka  (clock),
    .clkb  (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .ena   (1'h1),	// src/main/scala/tile_test/aeq.scala:114:22
    .enb   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .wea   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .web   (1'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .addra (_aeqReadStage_io_ai_rdaddr_8),	// src/main/scala/tile_test/aeq.scala:93:30
    .addrb (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dia   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .dib   (10'h0),	// src/main/scala/tile_test/aeq.scala:105:18
    .doa   (_tdpb_init_8_doa),
    .dob   (/* unused */)
  );
endmodule


// ----- 8< ----- FILE "./tdpb_init.v" ----- 8< -----

module tdpb_init #(
    parameter DATA_WIDTH = 16,
    parameter ADDR_WIDTH = 10,
    parameter INIT_FILE = ""
)(
    input                        clka, clkb,
    input                        ena, enb,
    input                        wea, web,
    input      [ADDR_WIDTH-1:0]  addra, addrb,
    input      [DATA_WIDTH-1:0]  dia, dib,
    output reg [DATA_WIDTH-1:0]  doa, dob
);

    reg [DATA_WIDTH-1:0] ram [(2**ADDR_WIDTH)-1:0];

    // Initialization block
    initial begin
        if (INIT_FILE != "") begin
            $readmemh(INIT_FILE, ram);
        end
    end

    always @(posedge clka) begin
        if (ena) begin
            if (wea)
                ram[addra] <= dia;
            doa <= ram[addra];
        end
    end

    always @(posedge clkb) begin
        if (enb) begin
            if (web)
                ram[addrb] <= dib;
            dob <= ram[addrb];
        end
    end

endmodule

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----

tdpb_init.v
