// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// VCS coverage exclude_file
module brams_256x9(	// src/main/scala/mempot.scala:27:40
  input  [7:0] RW0_addr,
  input        RW0_en,
               RW0_clk,
               RW0_wmode,
  input  [8:0] RW0_wdata,
  output [8:0] RW0_rdata
);

  reg [8:0] Memory[0:255];	// src/main/scala/mempot.scala:27:40
  reg [7:0] _RW0_raddr_d0;	// src/main/scala/mempot.scala:27:40
  reg       _RW0_ren_d0;	// src/main/scala/mempot.scala:27:40
  reg       _RW0_rmode_d0;	// src/main/scala/mempot.scala:27:40
  always @(posedge RW0_clk) begin	// src/main/scala/mempot.scala:27:40
    _RW0_raddr_d0 <= RW0_addr;	// src/main/scala/mempot.scala:27:40
    _RW0_ren_d0 <= RW0_en;	// src/main/scala/mempot.scala:27:40
    _RW0_rmode_d0 <= RW0_wmode;	// src/main/scala/mempot.scala:27:40
    if (RW0_en & RW0_wmode & 1'h1)	// src/main/scala/mempot.scala:27:40
      Memory[RW0_addr] <= RW0_wdata;	// src/main/scala/mempot.scala:27:40
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/mempot.scala:27:40
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/mempot.scala:27:40
      reg [31:0] _RANDOM;	// src/main/scala/mempot.scala:27:40
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/mempot.scala:27:40
    initial begin	// src/main/scala/mempot.scala:27:40
      `INIT_RANDOM_PROLOG_	// src/main/scala/mempot.scala:27:40
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/mempot.scala:27:40
        for (logic [8:0] i = 9'h0; i < 9'h100; i += 9'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/mempot.scala:27:40
          Memory[i[7:0]] = _RANDOM_MEM[8:0];	// src/main/scala/mempot.scala:27:40
        end	// src/main/scala/mempot.scala:27:40
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/mempot.scala:27:40
        _RANDOM = {`RANDOM};	// src/main/scala/mempot.scala:27:40
        _RW0_raddr_d0 = _RANDOM[7:0];	// src/main/scala/mempot.scala:27:40
        _RW0_ren_d0 = _RANDOM[8];	// src/main/scala/mempot.scala:27:40
        _RW0_rmode_d0 = _RANDOM[9];	// src/main/scala/mempot.scala:27:40
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign RW0_rdata = _RW0_ren_d0 & ~_RW0_rmode_d0 ? Memory[_RW0_raddr_d0] : 9'bx;	// src/main/scala/mempot.scala:27:40
endmodule

module mempot(	// src/main/scala/mempot.scala:16:8
  input        clock,	// src/main/scala/mempot.scala:16:8
               reset,	// src/main/scala/mempot.scala:16:8
               io_wr_enable_0,	// src/main/scala/mempot.scala:17:16
               io_wr_enable_1,	// src/main/scala/mempot.scala:17:16
               io_wr_enable_2,	// src/main/scala/mempot.scala:17:16
               io_wr_enable_3,	// src/main/scala/mempot.scala:17:16
               io_wr_enable_4,	// src/main/scala/mempot.scala:17:16
               io_wr_enable_5,	// src/main/scala/mempot.scala:17:16
               io_wr_enable_6,	// src/main/scala/mempot.scala:17:16
               io_wr_enable_7,	// src/main/scala/mempot.scala:17:16
               io_wr_enable_8,	// src/main/scala/mempot.scala:17:16
               io_rd_enable_0,	// src/main/scala/mempot.scala:17:16
               io_rd_enable_1,	// src/main/scala/mempot.scala:17:16
               io_rd_enable_2,	// src/main/scala/mempot.scala:17:16
               io_rd_enable_3,	// src/main/scala/mempot.scala:17:16
               io_rd_enable_4,	// src/main/scala/mempot.scala:17:16
               io_rd_enable_5,	// src/main/scala/mempot.scala:17:16
               io_rd_enable_6,	// src/main/scala/mempot.scala:17:16
               io_rd_enable_7,	// src/main/scala/mempot.scala:17:16
               io_rd_enable_8,	// src/main/scala/mempot.scala:17:16
  input  [7:0] io_addr_r_0,	// src/main/scala/mempot.scala:17:16
               io_addr_r_1,	// src/main/scala/mempot.scala:17:16
               io_addr_r_2,	// src/main/scala/mempot.scala:17:16
               io_addr_r_3,	// src/main/scala/mempot.scala:17:16
               io_addr_r_4,	// src/main/scala/mempot.scala:17:16
               io_addr_r_5,	// src/main/scala/mempot.scala:17:16
               io_addr_r_6,	// src/main/scala/mempot.scala:17:16
               io_addr_r_7,	// src/main/scala/mempot.scala:17:16
               io_addr_r_8,	// src/main/scala/mempot.scala:17:16
               io_addr_w_0,	// src/main/scala/mempot.scala:17:16
               io_addr_w_1,	// src/main/scala/mempot.scala:17:16
               io_addr_w_2,	// src/main/scala/mempot.scala:17:16
               io_addr_w_3,	// src/main/scala/mempot.scala:17:16
               io_addr_w_4,	// src/main/scala/mempot.scala:17:16
               io_addr_w_5,	// src/main/scala/mempot.scala:17:16
               io_addr_w_6,	// src/main/scala/mempot.scala:17:16
               io_addr_w_7,	// src/main/scala/mempot.scala:17:16
               io_addr_w_8,	// src/main/scala/mempot.scala:17:16
  input  [8:0] io_din_0,	// src/main/scala/mempot.scala:17:16
               io_din_1,	// src/main/scala/mempot.scala:17:16
               io_din_2,	// src/main/scala/mempot.scala:17:16
               io_din_3,	// src/main/scala/mempot.scala:17:16
               io_din_4,	// src/main/scala/mempot.scala:17:16
               io_din_5,	// src/main/scala/mempot.scala:17:16
               io_din_6,	// src/main/scala/mempot.scala:17:16
               io_din_7,	// src/main/scala/mempot.scala:17:16
               io_din_8,	// src/main/scala/mempot.scala:17:16
  output [8:0] io_dout_0,	// src/main/scala/mempot.scala:17:16
               io_dout_1,	// src/main/scala/mempot.scala:17:16
               io_dout_2,	// src/main/scala/mempot.scala:17:16
               io_dout_3,	// src/main/scala/mempot.scala:17:16
               io_dout_4,	// src/main/scala/mempot.scala:17:16
               io_dout_5,	// src/main/scala/mempot.scala:17:16
               io_dout_6,	// src/main/scala/mempot.scala:17:16
               io_dout_7,	// src/main/scala/mempot.scala:17:16
               io_dout_8	// src/main/scala/mempot.scala:17:16
);

  wire writeEnable;	// src/main/scala/mempot.scala:35:30
  wire writeEnable_0;	// src/main/scala/mempot.scala:35:30
  wire writeEnable_1;	// src/main/scala/mempot.scala:35:30
  wire writeEnable_2;	// src/main/scala/mempot.scala:35:30
  wire writeEnable_3;	// src/main/scala/mempot.scala:35:30
  wire writeEnable_4;	// src/main/scala/mempot.scala:35:30
  wire writeEnable_5;	// src/main/scala/mempot.scala:35:30
  wire writeEnable_6;	// src/main/scala/mempot.scala:35:30
  wire writeEnable_7;	// src/main/scala/mempot.scala:35:30
  assign writeEnable_7 = ~io_rd_enable_0 & io_wr_enable_0;	// src/main/scala/mempot.scala:35:{13,30}
  assign writeEnable_6 = ~io_rd_enable_1 & io_wr_enable_1;	// src/main/scala/mempot.scala:35:{13,30}
  assign writeEnable_5 = ~io_rd_enable_2 & io_wr_enable_2;	// src/main/scala/mempot.scala:35:{13,30}
  assign writeEnable_4 = ~io_rd_enable_3 & io_wr_enable_3;	// src/main/scala/mempot.scala:35:{13,30}
  assign writeEnable_3 = ~io_rd_enable_4 & io_wr_enable_4;	// src/main/scala/mempot.scala:35:{13,30}
  assign writeEnable_2 = ~io_rd_enable_5 & io_wr_enable_5;	// src/main/scala/mempot.scala:35:{13,30}
  assign writeEnable_1 = ~io_rd_enable_6 & io_wr_enable_6;	// src/main/scala/mempot.scala:35:{13,30}
  assign writeEnable_0 = ~io_rd_enable_7 & io_wr_enable_7;	// src/main/scala/mempot.scala:35:{13,30}
  assign writeEnable = ~io_rd_enable_8 & io_wr_enable_8;	// src/main/scala/mempot.scala:35:{13,30}
  brams_256x9 brams_0_ext (	// src/main/scala/mempot.scala:27:40
    .RW0_addr  (writeEnable_7 ? io_addr_w_0 : io_addr_r_0),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_en    (io_rd_enable_0 | writeEnable_7),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_clk   (clock),
    .RW0_wmode (~io_rd_enable_0),	// src/main/scala/mempot.scala:35:13
    .RW0_wdata (io_din_0),
    .RW0_rdata (io_dout_0)
  );
  brams_256x9 brams_1_ext (	// src/main/scala/mempot.scala:27:40
    .RW0_addr  (writeEnable_6 ? io_addr_w_1 : io_addr_r_1),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_en    (io_rd_enable_1 | writeEnable_6),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_clk   (clock),
    .RW0_wmode (~io_rd_enable_1),	// src/main/scala/mempot.scala:35:13
    .RW0_wdata (io_din_1),
    .RW0_rdata (io_dout_1)
  );
  brams_256x9 brams_2_ext (	// src/main/scala/mempot.scala:27:40
    .RW0_addr  (writeEnable_5 ? io_addr_w_2 : io_addr_r_2),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_en    (io_rd_enable_2 | writeEnable_5),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_clk   (clock),
    .RW0_wmode (~io_rd_enable_2),	// src/main/scala/mempot.scala:35:13
    .RW0_wdata (io_din_2),
    .RW0_rdata (io_dout_2)
  );
  brams_256x9 brams_3_ext (	// src/main/scala/mempot.scala:27:40
    .RW0_addr  (writeEnable_4 ? io_addr_w_3 : io_addr_r_3),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_en    (io_rd_enable_3 | writeEnable_4),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_clk   (clock),
    .RW0_wmode (~io_rd_enable_3),	// src/main/scala/mempot.scala:35:13
    .RW0_wdata (io_din_3),
    .RW0_rdata (io_dout_3)
  );
  brams_256x9 brams_4_ext (	// src/main/scala/mempot.scala:27:40
    .RW0_addr  (writeEnable_3 ? io_addr_w_4 : io_addr_r_4),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_en    (io_rd_enable_4 | writeEnable_3),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_clk   (clock),
    .RW0_wmode (~io_rd_enable_4),	// src/main/scala/mempot.scala:35:13
    .RW0_wdata (io_din_4),
    .RW0_rdata (io_dout_4)
  );
  brams_256x9 brams_5_ext (	// src/main/scala/mempot.scala:27:40
    .RW0_addr  (writeEnable_2 ? io_addr_w_5 : io_addr_r_5),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_en    (io_rd_enable_5 | writeEnable_2),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_clk   (clock),
    .RW0_wmode (~io_rd_enable_5),	// src/main/scala/mempot.scala:35:13
    .RW0_wdata (io_din_5),
    .RW0_rdata (io_dout_5)
  );
  brams_256x9 brams_6_ext (	// src/main/scala/mempot.scala:27:40
    .RW0_addr  (writeEnable_1 ? io_addr_w_6 : io_addr_r_6),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_en    (io_rd_enable_6 | writeEnable_1),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_clk   (clock),
    .RW0_wmode (~io_rd_enable_6),	// src/main/scala/mempot.scala:35:13
    .RW0_wdata (io_din_6),
    .RW0_rdata (io_dout_6)
  );
  brams_256x9 brams_7_ext (	// src/main/scala/mempot.scala:27:40
    .RW0_addr  (writeEnable_0 ? io_addr_w_7 : io_addr_r_7),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_en    (io_rd_enable_7 | writeEnable_0),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_clk   (clock),
    .RW0_wmode (~io_rd_enable_7),	// src/main/scala/mempot.scala:35:13
    .RW0_wdata (io_din_7),
    .RW0_rdata (io_dout_7)
  );
  brams_256x9 brams_8_ext (	// src/main/scala/mempot.scala:27:40
    .RW0_addr  (writeEnable ? io_addr_w_8 : io_addr_r_8),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_en    (io_rd_enable_8 | writeEnable),	// src/main/scala/mempot.scala:27:40, :35:30
    .RW0_clk   (clock),
    .RW0_wmode (~io_rd_enable_8),	// src/main/scala/mempot.scala:35:13
    .RW0_wdata (io_din_8),
    .RW0_rdata (io_dout_8)
  );
endmodule

