// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// VCS coverage exclude_file
module mems_256x11(	// src/main/scala/multi_sync_mem.scala:28:47
  input  [7:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [10:0] R0_data,
  input  [7:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [10:0] W0_data
);

  reg [10:0] Memory[0:255];	// src/main/scala/multi_sync_mem.scala:28:47
  reg        _R0_en_d0;	// src/main/scala/multi_sync_mem.scala:28:47
  reg [7:0]  _R0_addr_d0;	// src/main/scala/multi_sync_mem.scala:28:47
  always @(posedge R0_clk) begin	// src/main/scala/multi_sync_mem.scala:28:47
    _R0_en_d0 <= R0_en;	// src/main/scala/multi_sync_mem.scala:28:47
    _R0_addr_d0 <= R0_addr;	// src/main/scala/multi_sync_mem.scala:28:47
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/multi_sync_mem.scala:28:47
    if (W0_en & 1'h1)	// src/main/scala/multi_sync_mem.scala:28:47
      Memory[W0_addr] <= W0_data;	// src/main/scala/multi_sync_mem.scala:28:47
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/multi_sync_mem.scala:28:47
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/multi_sync_mem.scala:28:47
      reg [31:0] _RANDOM;	// src/main/scala/multi_sync_mem.scala:28:47
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/multi_sync_mem.scala:28:47
    initial begin	// src/main/scala/multi_sync_mem.scala:28:47
      `INIT_RANDOM_PROLOG_	// src/main/scala/multi_sync_mem.scala:28:47
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/multi_sync_mem.scala:28:47
        for (logic [8:0] i = 9'h0; i < 9'h100; i += 9'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/multi_sync_mem.scala:28:47
          Memory[i[7:0]] = _RANDOM_MEM[10:0];	// src/main/scala/multi_sync_mem.scala:28:47
        end	// src/main/scala/multi_sync_mem.scala:28:47
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/multi_sync_mem.scala:28:47
        _RANDOM = {`RANDOM};	// src/main/scala/multi_sync_mem.scala:28:47
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/multi_sync_mem.scala:28:47
        _R0_addr_d0 = _RANDOM[8:1];	// src/main/scala/multi_sync_mem.scala:28:47
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 11'bx;	// src/main/scala/multi_sync_mem.scala:28:47
endmodule

module MultiMemory(	// src/main/scala/multi_sync_mem.scala:17:7
  input         clock,	// src/main/scala/multi_sync_mem.scala:17:7
  input  [7:0]  io_rdAddr_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdAddr_8,	// src/main/scala/multi_sync_mem.scala:18:14
  output [10:0] io_rdData_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdData_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input  [7:0]  io_wrAddr_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrAddr_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input  [10:0] io_wrData_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrData_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input         io_wrEna_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_wrEna_8,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_0,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_1,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_2,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_3,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_4,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_5,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_6,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_7,	// src/main/scala/multi_sync_mem.scala:18:14
                io_rdEna_8	// src/main/scala/multi_sync_mem.scala:18:14
);

  mems_256x11 mems_0_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_0),
    .R0_en   (io_rdEna_0),
    .R0_clk  (clock),
    .R0_data (io_rdData_0),
    .W0_addr (io_wrAddr_0),
    .W0_en   (io_wrEna_0),
    .W0_clk  (clock),
    .W0_data (io_wrData_0)
  );
  mems_256x11 mems_1_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_1),
    .R0_en   (io_rdEna_1),
    .R0_clk  (clock),
    .R0_data (io_rdData_1),
    .W0_addr (io_wrAddr_1),
    .W0_en   (io_wrEna_1),
    .W0_clk  (clock),
    .W0_data (io_wrData_1)
  );
  mems_256x11 mems_2_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_2),
    .R0_en   (io_rdEna_2),
    .R0_clk  (clock),
    .R0_data (io_rdData_2),
    .W0_addr (io_wrAddr_2),
    .W0_en   (io_wrEna_2),
    .W0_clk  (clock),
    .W0_data (io_wrData_2)
  );
  mems_256x11 mems_3_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_3),
    .R0_en   (io_rdEna_3),
    .R0_clk  (clock),
    .R0_data (io_rdData_3),
    .W0_addr (io_wrAddr_3),
    .W0_en   (io_wrEna_3),
    .W0_clk  (clock),
    .W0_data (io_wrData_3)
  );
  mems_256x11 mems_4_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_4),
    .R0_en   (io_rdEna_4),
    .R0_clk  (clock),
    .R0_data (io_rdData_4),
    .W0_addr (io_wrAddr_4),
    .W0_en   (io_wrEna_4),
    .W0_clk  (clock),
    .W0_data (io_wrData_4)
  );
  mems_256x11 mems_5_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_5),
    .R0_en   (io_rdEna_5),
    .R0_clk  (clock),
    .R0_data (io_rdData_5),
    .W0_addr (io_wrAddr_5),
    .W0_en   (io_wrEna_5),
    .W0_clk  (clock),
    .W0_data (io_wrData_5)
  );
  mems_256x11 mems_6_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_6),
    .R0_en   (io_rdEna_6),
    .R0_clk  (clock),
    .R0_data (io_rdData_6),
    .W0_addr (io_wrAddr_6),
    .W0_en   (io_wrEna_6),
    .W0_clk  (clock),
    .W0_data (io_wrData_6)
  );
  mems_256x11 mems_7_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_7),
    .R0_en   (io_rdEna_7),
    .R0_clk  (clock),
    .R0_data (io_rdData_7),
    .W0_addr (io_wrAddr_7),
    .W0_en   (io_wrEna_7),
    .W0_clk  (clock),
    .W0_data (io_wrData_7)
  );
  mems_256x11 mems_8_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_8),
    .R0_en   (io_rdEna_8),
    .R0_clk  (clock),
    .R0_data (io_rdData_8),
    .W0_addr (io_wrAddr_8),
    .W0_en   (io_wrEna_8),
    .W0_clk  (clock),
    .W0_data (io_wrData_8)
  );
endmodule

module AEQ(	// src/main/scala/aeq.scala:45:7
  input        clock,	// src/main/scala/aeq.scala:45:7
               reset,	// src/main/scala/aeq.scala:45:7
               io_writeEnable_0,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_1,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_2,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_3,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_4,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_5,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_6,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_7,	// src/main/scala/aeq.scala:46:14
               io_writeEnable_8,	// src/main/scala/aeq.scala:46:14
               io_readEnable,	// src/main/scala/aeq.scala:46:14
  input  [8:0] io_writeData_0,	// src/main/scala/aeq.scala:46:14
               io_writeData_1,	// src/main/scala/aeq.scala:46:14
               io_writeData_2,	// src/main/scala/aeq.scala:46:14
               io_writeData_3,	// src/main/scala/aeq.scala:46:14
               io_writeData_4,	// src/main/scala/aeq.scala:46:14
               io_writeData_5,	// src/main/scala/aeq.scala:46:14
               io_writeData_6,	// src/main/scala/aeq.scala:46:14
               io_writeData_7,	// src/main/scala/aeq.scala:46:14
               io_writeData_8,	// src/main/scala/aeq.scala:46:14
  output [8:0] io_readData_0,	// src/main/scala/aeq.scala:46:14
               io_readData_1,	// src/main/scala/aeq.scala:46:14
               io_readData_2,	// src/main/scala/aeq.scala:46:14
               io_readData_3,	// src/main/scala/aeq.scala:46:14
               io_readData_4,	// src/main/scala/aeq.scala:46:14
               io_readData_5,	// src/main/scala/aeq.scala:46:14
               io_readData_6,	// src/main/scala/aeq.scala:46:14
               io_readData_7,	// src/main/scala/aeq.scala:46:14
               io_readData_8	// src/main/scala/aeq.scala:46:14
);

  wire [10:0] _multiMem_io_rdData_0;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_1;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_2;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_3;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_4;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_5;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_6;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_7;	// src/main/scala/aeq.scala:53:24
  wire [10:0] _multiMem_io_rdData_8;	// src/main/scala/aeq.scala:53:24
  reg  [7:0]  writeCounters_0;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_1;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_2;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_3;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_4;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_5;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_6;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_7;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  writeCounters_8;	// src/main/scala/aeq.scala:55:30
  reg  [7:0]  readCounter;	// src/main/scala/aeq.scala:56:28
  wire [7:0]  _GEN = io_readEnable ? readCounter : 8'h0;	// src/main/scala/aeq.scala:55:38, :56:28, :63:22, :70:23, :73:29
  always @(posedge clock) begin	// src/main/scala/aeq.scala:45:7
    if (reset) begin	// src/main/scala/aeq.scala:45:7
      writeCounters_0 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_1 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_2 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_3 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_4 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_5 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_6 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_7 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      writeCounters_8 <= 8'h0;	// src/main/scala/aeq.scala:55:{30,38}
      readCounter <= 8'h0;	// src/main/scala/aeq.scala:55:38, :56:28
    end
    else begin	// src/main/scala/aeq.scala:45:7
      if (io_writeEnable_0)	// src/main/scala/aeq.scala:46:14
        writeCounters_0 <= writeCounters_0 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_1)	// src/main/scala/aeq.scala:46:14
        writeCounters_1 <= writeCounters_1 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_2)	// src/main/scala/aeq.scala:46:14
        writeCounters_2 <= writeCounters_2 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_3)	// src/main/scala/aeq.scala:46:14
        writeCounters_3 <= writeCounters_3 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_4)	// src/main/scala/aeq.scala:46:14
        writeCounters_4 <= writeCounters_4 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_5)	// src/main/scala/aeq.scala:46:14
        writeCounters_5 <= writeCounters_5 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_6)	// src/main/scala/aeq.scala:46:14
        writeCounters_6 <= writeCounters_6 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_7)	// src/main/scala/aeq.scala:46:14
        writeCounters_7 <= writeCounters_7 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_writeEnable_8)	// src/main/scala/aeq.scala:46:14
        writeCounters_8 <= writeCounters_8 + 8'h1;	// src/main/scala/aeq.scala:55:30, :76:32, :92:44
      if (io_readEnable)	// src/main/scala/aeq.scala:46:14
        readCounter <= readCounter + 8'h1;	// src/main/scala/aeq.scala:56:28, :76:32
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/aeq.scala:45:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/aeq.scala:45:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/aeq.scala:45:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/aeq.scala:45:7
      automatic logic [31:0] _RANDOM[0:2];	// src/main/scala/aeq.scala:45:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/aeq.scala:45:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/aeq.scala:45:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/aeq.scala:45:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/aeq.scala:45:7
        end	// src/main/scala/aeq.scala:45:7
        writeCounters_0 = _RANDOM[2'h0][7:0];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_1 = _RANDOM[2'h0][15:8];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_2 = _RANDOM[2'h0][23:16];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_3 = _RANDOM[2'h0][31:24];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_4 = _RANDOM[2'h1][7:0];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_5 = _RANDOM[2'h1][15:8];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_6 = _RANDOM[2'h1][23:16];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_7 = _RANDOM[2'h1][31:24];	// src/main/scala/aeq.scala:45:7, :55:30
        writeCounters_8 = _RANDOM[2'h2][7:0];	// src/main/scala/aeq.scala:45:7, :55:30
        readCounter = _RANDOM[2'h2][15:8];	// src/main/scala/aeq.scala:45:7, :55:30, :56:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/aeq.scala:45:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/aeq.scala:45:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MultiMemory multiMem (	// src/main/scala/aeq.scala:53:24
    .clock       (clock),
    .io_rdAddr_0 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_1 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_2 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_3 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_4 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_5 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_6 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_7 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdAddr_8 (_GEN),	// src/main/scala/aeq.scala:63:22, :70:23, :73:29
    .io_rdData_0 (_multiMem_io_rdData_0),
    .io_rdData_1 (_multiMem_io_rdData_1),
    .io_rdData_2 (_multiMem_io_rdData_2),
    .io_rdData_3 (_multiMem_io_rdData_3),
    .io_rdData_4 (_multiMem_io_rdData_4),
    .io_rdData_5 (_multiMem_io_rdData_5),
    .io_rdData_6 (_multiMem_io_rdData_6),
    .io_rdData_7 (_multiMem_io_rdData_7),
    .io_rdData_8 (_multiMem_io_rdData_8),
    .io_wrAddr_0 (io_writeEnable_0 ? writeCounters_0 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_1 (io_writeEnable_1 ? writeCounters_1 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_2 (io_writeEnable_2 ? writeCounters_2 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_3 (io_writeEnable_3 ? writeCounters_3 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_4 (io_writeEnable_4 ? writeCounters_4 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_5 (io_writeEnable_5 ? writeCounters_5 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_6 (io_writeEnable_6 ? writeCounters_6 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_7 (io_writeEnable_7 ? writeCounters_7 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrAddr_8 (io_writeEnable_8 ? writeCounters_8 : 8'h0),	// src/main/scala/aeq.scala:55:{30,38}, :64:22, :87:29, :93:48
    .io_wrData_0 (io_writeEnable_0 ? {&writeCounters_0, io_writeData_0, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_1 (io_writeEnable_1 ? {&writeCounters_1, io_writeData_1, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_2 (io_writeEnable_2 ? {&writeCounters_2, io_writeData_2, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_3 (io_writeEnable_3 ? {&writeCounters_3, io_writeData_3, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_4 (io_writeEnable_4 ? {&writeCounters_4, io_writeData_4, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_5 (io_writeEnable_5 ? {&writeCounters_5, io_writeData_5, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_6 (io_writeEnable_6 ? {&writeCounters_6, io_writeData_6, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_7 (io_writeEnable_7 ? {&writeCounters_7, io_writeData_7, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrData_8 (io_writeEnable_8 ? {&writeCounters_8, io_writeData_8, 1'h1} : 11'h0),	// src/main/scala/aeq.scala:55:30, :65:{22,32}, :71:33, :87:29, :88:21, :90:29, :93:{29,48}, :94:27, :96:31
    .io_wrEna_0  (io_writeEnable_0),
    .io_wrEna_1  (io_writeEnable_1),
    .io_wrEna_2  (io_writeEnable_2),
    .io_wrEna_3  (io_writeEnable_3),
    .io_wrEna_4  (io_writeEnable_4),
    .io_wrEna_5  (io_writeEnable_5),
    .io_wrEna_6  (io_writeEnable_6),
    .io_wrEna_7  (io_writeEnable_7),
    .io_wrEna_8  (io_writeEnable_8),
    .io_rdEna_0  (io_readEnable),
    .io_rdEna_1  (io_readEnable),
    .io_rdEna_2  (io_readEnable),
    .io_rdEna_3  (io_readEnable),
    .io_rdEna_4  (io_readEnable),
    .io_rdEna_5  (io_readEnable),
    .io_rdEna_6  (io_readEnable),
    .io_rdEna_7  (io_readEnable),
    .io_rdEna_8  (io_readEnable)
  );
  assign io_readData_0 = _multiMem_io_rdData_0[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_1 = _multiMem_io_rdData_1[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_2 = _multiMem_io_rdData_2[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_3 = _multiMem_io_rdData_3[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_4 = _multiMem_io_rdData_4[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_5 = _multiMem_io_rdData_5[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_6 = _multiMem_io_rdData_6[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_7 = _multiMem_io_rdData_7[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
  assign io_readData_8 = _multiMem_io_rdData_8[9:1];	// src/main/scala/aeq.scala:45:7, :53:24, :74:46
endmodule

// VCS coverage exclude_file
module mems_256x9(	// src/main/scala/multi_sync_mem.scala:28:47
  input  [7:0] R0_addr,
  input        R0_en,
               R0_clk,
  output [8:0] R0_data,
  input  [7:0] W0_addr,
  input        W0_en,
               W0_clk,
  input  [8:0] W0_data
);

  reg [8:0] Memory[0:255];	// src/main/scala/multi_sync_mem.scala:28:47
  reg       _R0_en_d0;	// src/main/scala/multi_sync_mem.scala:28:47
  reg [7:0] _R0_addr_d0;	// src/main/scala/multi_sync_mem.scala:28:47
  always @(posedge R0_clk) begin	// src/main/scala/multi_sync_mem.scala:28:47
    _R0_en_d0 <= R0_en;	// src/main/scala/multi_sync_mem.scala:28:47
    _R0_addr_d0 <= R0_addr;	// src/main/scala/multi_sync_mem.scala:28:47
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/multi_sync_mem.scala:28:47
    if (W0_en & 1'h1)	// src/main/scala/multi_sync_mem.scala:28:47
      Memory[W0_addr] <= W0_data;	// src/main/scala/multi_sync_mem.scala:28:47
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/multi_sync_mem.scala:28:47
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/multi_sync_mem.scala:28:47
      reg [31:0] _RANDOM;	// src/main/scala/multi_sync_mem.scala:28:47
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/multi_sync_mem.scala:28:47
    initial begin	// src/main/scala/multi_sync_mem.scala:28:47
      `INIT_RANDOM_PROLOG_	// src/main/scala/multi_sync_mem.scala:28:47
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/multi_sync_mem.scala:28:47
        for (logic [8:0] i = 9'h0; i < 9'h100; i += 9'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/multi_sync_mem.scala:28:47
          Memory[i[7:0]] = _RANDOM_MEM[8:0];	// src/main/scala/multi_sync_mem.scala:28:47
        end	// src/main/scala/multi_sync_mem.scala:28:47
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/multi_sync_mem.scala:28:47
        _RANDOM = {`RANDOM};	// src/main/scala/multi_sync_mem.scala:28:47
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/multi_sync_mem.scala:28:47
        _R0_addr_d0 = _RANDOM[8:1];	// src/main/scala/multi_sync_mem.scala:28:47
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 9'bx;	// src/main/scala/multi_sync_mem.scala:28:47
endmodule

module MultiMemory_1(	// src/main/scala/multi_sync_mem.scala:17:7
  input        clock,	// src/main/scala/multi_sync_mem.scala:17:7
  input  [7:0] io_rdAddr_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdAddr_8,	// src/main/scala/multi_sync_mem.scala:18:14
  output [8:0] io_rdData_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdData_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input  [7:0] io_wrAddr_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrAddr_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input  [8:0] io_wrData_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrData_8,	// src/main/scala/multi_sync_mem.scala:18:14
  input        io_wrEna_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_wrEna_8,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_0,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_1,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_2,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_3,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_4,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_5,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_6,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_7,	// src/main/scala/multi_sync_mem.scala:18:14
               io_rdEna_8	// src/main/scala/multi_sync_mem.scala:18:14
);

  mems_256x9 mems_0_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_0),
    .R0_en   (io_rdEna_0),
    .R0_clk  (clock),
    .R0_data (io_rdData_0),
    .W0_addr (io_wrAddr_0),
    .W0_en   (io_wrEna_0),
    .W0_clk  (clock),
    .W0_data (io_wrData_0)
  );
  mems_256x9 mems_1_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_1),
    .R0_en   (io_rdEna_1),
    .R0_clk  (clock),
    .R0_data (io_rdData_1),
    .W0_addr (io_wrAddr_1),
    .W0_en   (io_wrEna_1),
    .W0_clk  (clock),
    .W0_data (io_wrData_1)
  );
  mems_256x9 mems_2_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_2),
    .R0_en   (io_rdEna_2),
    .R0_clk  (clock),
    .R0_data (io_rdData_2),
    .W0_addr (io_wrAddr_2),
    .W0_en   (io_wrEna_2),
    .W0_clk  (clock),
    .W0_data (io_wrData_2)
  );
  mems_256x9 mems_3_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_3),
    .R0_en   (io_rdEna_3),
    .R0_clk  (clock),
    .R0_data (io_rdData_3),
    .W0_addr (io_wrAddr_3),
    .W0_en   (io_wrEna_3),
    .W0_clk  (clock),
    .W0_data (io_wrData_3)
  );
  mems_256x9 mems_4_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_4),
    .R0_en   (io_rdEna_4),
    .R0_clk  (clock),
    .R0_data (io_rdData_4),
    .W0_addr (io_wrAddr_4),
    .W0_en   (io_wrEna_4),
    .W0_clk  (clock),
    .W0_data (io_wrData_4)
  );
  mems_256x9 mems_5_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_5),
    .R0_en   (io_rdEna_5),
    .R0_clk  (clock),
    .R0_data (io_rdData_5),
    .W0_addr (io_wrAddr_5),
    .W0_en   (io_wrEna_5),
    .W0_clk  (clock),
    .W0_data (io_wrData_5)
  );
  mems_256x9 mems_6_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_6),
    .R0_en   (io_rdEna_6),
    .R0_clk  (clock),
    .R0_data (io_rdData_6),
    .W0_addr (io_wrAddr_6),
    .W0_en   (io_wrEna_6),
    .W0_clk  (clock),
    .W0_data (io_wrData_6)
  );
  mems_256x9 mems_7_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_7),
    .R0_en   (io_rdEna_7),
    .R0_clk  (clock),
    .R0_data (io_rdData_7),
    .W0_addr (io_wrAddr_7),
    .W0_en   (io_wrEna_7),
    .W0_clk  (clock),
    .W0_data (io_wrData_7)
  );
  mems_256x9 mems_8_ext (	// src/main/scala/multi_sync_mem.scala:28:47
    .R0_addr (io_rdAddr_8),
    .R0_en   (io_rdEna_8),
    .R0_clk  (clock),
    .R0_data (io_rdData_8),
    .W0_addr (io_wrAddr_8),
    .W0_en   (io_wrEna_8),
    .W0_clk  (clock),
    .W0_data (io_wrData_8)
  );
endmodule

module mempot(	// src/main/scala/mempot.scala:43:7
  input        clock,	// src/main/scala/mempot.scala:43:7
               io_wr_enable_0,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_1,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_2,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_3,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_4,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_5,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_6,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_7,	// src/main/scala/mempot.scala:44:14
               io_wr_enable_8,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_0,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_1,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_2,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_3,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_4,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_5,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_6,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_7,	// src/main/scala/mempot.scala:44:14
               io_rd_enable_8,	// src/main/scala/mempot.scala:44:14
  input  [7:0] io_addr_r_0,	// src/main/scala/mempot.scala:44:14
               io_addr_r_1,	// src/main/scala/mempot.scala:44:14
               io_addr_r_2,	// src/main/scala/mempot.scala:44:14
               io_addr_r_3,	// src/main/scala/mempot.scala:44:14
               io_addr_r_4,	// src/main/scala/mempot.scala:44:14
               io_addr_r_5,	// src/main/scala/mempot.scala:44:14
               io_addr_r_6,	// src/main/scala/mempot.scala:44:14
               io_addr_r_7,	// src/main/scala/mempot.scala:44:14
               io_addr_r_8,	// src/main/scala/mempot.scala:44:14
               io_addr_w_0,	// src/main/scala/mempot.scala:44:14
               io_addr_w_1,	// src/main/scala/mempot.scala:44:14
               io_addr_w_2,	// src/main/scala/mempot.scala:44:14
               io_addr_w_3,	// src/main/scala/mempot.scala:44:14
               io_addr_w_4,	// src/main/scala/mempot.scala:44:14
               io_addr_w_5,	// src/main/scala/mempot.scala:44:14
               io_addr_w_6,	// src/main/scala/mempot.scala:44:14
               io_addr_w_7,	// src/main/scala/mempot.scala:44:14
               io_addr_w_8,	// src/main/scala/mempot.scala:44:14
  input  [8:0] io_din_0,	// src/main/scala/mempot.scala:44:14
               io_din_1,	// src/main/scala/mempot.scala:44:14
               io_din_2,	// src/main/scala/mempot.scala:44:14
               io_din_3,	// src/main/scala/mempot.scala:44:14
               io_din_4,	// src/main/scala/mempot.scala:44:14
               io_din_5,	// src/main/scala/mempot.scala:44:14
               io_din_6,	// src/main/scala/mempot.scala:44:14
               io_din_7,	// src/main/scala/mempot.scala:44:14
               io_din_8,	// src/main/scala/mempot.scala:44:14
  output [8:0] io_dout_0,	// src/main/scala/mempot.scala:44:14
               io_dout_1,	// src/main/scala/mempot.scala:44:14
               io_dout_2,	// src/main/scala/mempot.scala:44:14
               io_dout_3,	// src/main/scala/mempot.scala:44:14
               io_dout_4,	// src/main/scala/mempot.scala:44:14
               io_dout_5,	// src/main/scala/mempot.scala:44:14
               io_dout_6,	// src/main/scala/mempot.scala:44:14
               io_dout_7,	// src/main/scala/mempot.scala:44:14
               io_dout_8	// src/main/scala/mempot.scala:44:14
);

  wire _GEN = ~io_rd_enable_0 & io_wr_enable_0;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_0 = ~io_rd_enable_1 & io_wr_enable_1;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_1 = ~io_rd_enable_2 & io_wr_enable_2;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_2 = ~io_rd_enable_3 & io_wr_enable_3;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_3 = ~io_rd_enable_4 & io_wr_enable_4;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_4 = ~io_rd_enable_5 & io_wr_enable_5;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_5 = ~io_rd_enable_6 & io_wr_enable_6;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_6 = ~io_rd_enable_7 & io_wr_enable_7;	// src/main/scala/mempot.scala:72:{11,28}
  wire _GEN_7 = ~io_rd_enable_8 & io_wr_enable_8;	// src/main/scala/mempot.scala:72:{11,28}
  MultiMemory_1 multiMem (	// src/main/scala/mempot.scala:55:24
    .clock       (clock),
    .io_rdAddr_0 (io_rd_enable_0 ? io_addr_r_0 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_1 (io_rd_enable_1 ? io_addr_r_1 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_2 (io_rd_enable_2 ? io_addr_r_2 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_3 (io_rd_enable_3 ? io_addr_r_3 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_4 (io_rd_enable_4 ? io_addr_r_4 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_5 (io_rd_enable_5 ? io_addr_r_5 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_6 (io_rd_enable_6 ? io_addr_r_6 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_7 (io_rd_enable_7 ? io_addr_r_7 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdAddr_8 (io_rd_enable_8 ? io_addr_r_8 : 8'h0),	// src/main/scala/mempot.scala:58:{22,32}, :66:27, :68:29
    .io_rdData_0 (io_dout_0),
    .io_rdData_1 (io_dout_1),
    .io_rdData_2 (io_dout_2),
    .io_rdData_3 (io_dout_3),
    .io_rdData_4 (io_dout_4),
    .io_rdData_5 (io_dout_5),
    .io_rdData_6 (io_dout_6),
    .io_rdData_7 (io_dout_7),
    .io_rdData_8 (io_dout_8),
    .io_wrAddr_0 (_GEN ? io_addr_w_0 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_1 (_GEN_0 ? io_addr_w_1 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_2 (_GEN_1 ? io_addr_w_2 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_3 (_GEN_2 ? io_addr_w_3 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_4 (_GEN_3 ? io_addr_w_4 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_5 (_GEN_4 ? io_addr_w_5 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_6 (_GEN_5 ? io_addr_w_6 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_7 (_GEN_6 ? io_addr_w_7 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrAddr_8 (_GEN_7 ? io_addr_w_8 : 8'h0),	// src/main/scala/mempot.scala:58:32, :59:22, :72:{28,47}, :74:29
    .io_wrData_0 (_GEN ? io_din_0 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_1 (_GEN_0 ? io_din_1 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_2 (_GEN_1 ? io_din_2 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_3 (_GEN_2 ? io_din_3 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_4 (_GEN_3 ? io_din_4 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_5 (_GEN_4 ? io_din_5 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_6 (_GEN_5 ? io_din_6 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_7 (_GEN_6 ? io_din_7 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrData_8 (_GEN_7 ? io_din_8 : 9'h0),	// src/main/scala/mempot.scala:60:{22,32}, :72:{28,47}, :75:29
    .io_wrEna_0  (_GEN & io_wr_enable_0),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_1  (_GEN_0 & io_wr_enable_1),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_2  (_GEN_1 & io_wr_enable_2),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_3  (_GEN_2 & io_wr_enable_3),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_4  (_GEN_3 & io_wr_enable_4),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_5  (_GEN_4 & io_wr_enable_5),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_6  (_GEN_5 & io_wr_enable_6),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_7  (_GEN_6 & io_wr_enable_7),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_wrEna_8  (_GEN_7 & io_wr_enable_8),	// src/main/scala/mempot.scala:61:21, :72:{28,47}, :73:28
    .io_rdEna_0  (io_rd_enable_0),
    .io_rdEna_1  (io_rd_enable_1),
    .io_rdEna_2  (io_rd_enable_2),
    .io_rdEna_3  (io_rd_enable_3),
    .io_rdEna_4  (io_rd_enable_4),
    .io_rdEna_5  (io_rd_enable_5),
    .io_rdEna_6  (io_rd_enable_6),
    .io_rdEna_7  (io_rd_enable_7),
    .io_rdEna_8  (io_rd_enable_8)
  );
endmodule

module pe(	// src/main/scala/pe.scala:15:7
  input        clock,	// src/main/scala/pe.scala:15:7
               reset,	// src/main/scala/pe.scala:15:7
               io_wr_enable_aeq_0,	// src/main/scala/pe.scala:16:14
               io_wr_enable_aeq_1,	// src/main/scala/pe.scala:16:14
               io_wr_enable_aeq_2,	// src/main/scala/pe.scala:16:14
               io_wr_enable_aeq_3,	// src/main/scala/pe.scala:16:14
               io_wr_enable_aeq_4,	// src/main/scala/pe.scala:16:14
               io_wr_enable_aeq_5,	// src/main/scala/pe.scala:16:14
               io_wr_enable_aeq_6,	// src/main/scala/pe.scala:16:14
               io_wr_enable_aeq_7,	// src/main/scala/pe.scala:16:14
               io_wr_enable_aeq_8,	// src/main/scala/pe.scala:16:14
               io_rd_enable_aeq,	// src/main/scala/pe.scala:16:14
  input  [8:0] io_writeData_aeq_0,	// src/main/scala/pe.scala:16:14
               io_writeData_aeq_1,	// src/main/scala/pe.scala:16:14
               io_writeData_aeq_2,	// src/main/scala/pe.scala:16:14
               io_writeData_aeq_3,	// src/main/scala/pe.scala:16:14
               io_writeData_aeq_4,	// src/main/scala/pe.scala:16:14
               io_writeData_aeq_5,	// src/main/scala/pe.scala:16:14
               io_writeData_aeq_6,	// src/main/scala/pe.scala:16:14
               io_writeData_aeq_7,	// src/main/scala/pe.scala:16:14
               io_writeData_aeq_8,	// src/main/scala/pe.scala:16:14
  output [8:0] io_readData_aeq_0,	// src/main/scala/pe.scala:16:14
               io_readData_aeq_1,	// src/main/scala/pe.scala:16:14
               io_readData_aeq_2,	// src/main/scala/pe.scala:16:14
               io_readData_aeq_3,	// src/main/scala/pe.scala:16:14
               io_readData_aeq_4,	// src/main/scala/pe.scala:16:14
               io_readData_aeq_5,	// src/main/scala/pe.scala:16:14
               io_readData_aeq_6,	// src/main/scala/pe.scala:16:14
               io_readData_aeq_7,	// src/main/scala/pe.scala:16:14
               io_readData_aeq_8,	// src/main/scala/pe.scala:16:14
  input        io_wr_enable_mempot_0,	// src/main/scala/pe.scala:16:14
               io_wr_enable_mempot_1,	// src/main/scala/pe.scala:16:14
               io_wr_enable_mempot_2,	// src/main/scala/pe.scala:16:14
               io_wr_enable_mempot_3,	// src/main/scala/pe.scala:16:14
               io_wr_enable_mempot_4,	// src/main/scala/pe.scala:16:14
               io_wr_enable_mempot_5,	// src/main/scala/pe.scala:16:14
               io_wr_enable_mempot_6,	// src/main/scala/pe.scala:16:14
               io_wr_enable_mempot_7,	// src/main/scala/pe.scala:16:14
               io_wr_enable_mempot_8,	// src/main/scala/pe.scala:16:14
               io_rd_enable_mempot_0,	// src/main/scala/pe.scala:16:14
               io_rd_enable_mempot_1,	// src/main/scala/pe.scala:16:14
               io_rd_enable_mempot_2,	// src/main/scala/pe.scala:16:14
               io_rd_enable_mempot_3,	// src/main/scala/pe.scala:16:14
               io_rd_enable_mempot_4,	// src/main/scala/pe.scala:16:14
               io_rd_enable_mempot_5,	// src/main/scala/pe.scala:16:14
               io_rd_enable_mempot_6,	// src/main/scala/pe.scala:16:14
               io_rd_enable_mempot_7,	// src/main/scala/pe.scala:16:14
               io_rd_enable_mempot_8,	// src/main/scala/pe.scala:16:14
  input  [7:0] io_addr_r_mempot_0,	// src/main/scala/pe.scala:16:14
               io_addr_r_mempot_1,	// src/main/scala/pe.scala:16:14
               io_addr_r_mempot_2,	// src/main/scala/pe.scala:16:14
               io_addr_r_mempot_3,	// src/main/scala/pe.scala:16:14
               io_addr_r_mempot_4,	// src/main/scala/pe.scala:16:14
               io_addr_r_mempot_5,	// src/main/scala/pe.scala:16:14
               io_addr_r_mempot_6,	// src/main/scala/pe.scala:16:14
               io_addr_r_mempot_7,	// src/main/scala/pe.scala:16:14
               io_addr_r_mempot_8,	// src/main/scala/pe.scala:16:14
               io_addr_w_mempot_0,	// src/main/scala/pe.scala:16:14
               io_addr_w_mempot_1,	// src/main/scala/pe.scala:16:14
               io_addr_w_mempot_2,	// src/main/scala/pe.scala:16:14
               io_addr_w_mempot_3,	// src/main/scala/pe.scala:16:14
               io_addr_w_mempot_4,	// src/main/scala/pe.scala:16:14
               io_addr_w_mempot_5,	// src/main/scala/pe.scala:16:14
               io_addr_w_mempot_6,	// src/main/scala/pe.scala:16:14
               io_addr_w_mempot_7,	// src/main/scala/pe.scala:16:14
               io_addr_w_mempot_8,	// src/main/scala/pe.scala:16:14
  input  [8:0] io_din_mempot_0,	// src/main/scala/pe.scala:16:14
               io_din_mempot_1,	// src/main/scala/pe.scala:16:14
               io_din_mempot_2,	// src/main/scala/pe.scala:16:14
               io_din_mempot_3,	// src/main/scala/pe.scala:16:14
               io_din_mempot_4,	// src/main/scala/pe.scala:16:14
               io_din_mempot_5,	// src/main/scala/pe.scala:16:14
               io_din_mempot_6,	// src/main/scala/pe.scala:16:14
               io_din_mempot_7,	// src/main/scala/pe.scala:16:14
               io_din_mempot_8,	// src/main/scala/pe.scala:16:14
  output [8:0] io_dout_mempot_0,	// src/main/scala/pe.scala:16:14
               io_dout_mempot_1,	// src/main/scala/pe.scala:16:14
               io_dout_mempot_2,	// src/main/scala/pe.scala:16:14
               io_dout_mempot_3,	// src/main/scala/pe.scala:16:14
               io_dout_mempot_4,	// src/main/scala/pe.scala:16:14
               io_dout_mempot_5,	// src/main/scala/pe.scala:16:14
               io_dout_mempot_6,	// src/main/scala/pe.scala:16:14
               io_dout_mempot_7,	// src/main/scala/pe.scala:16:14
               io_dout_mempot_8,	// src/main/scala/pe.scala:16:14
  input  [7:0] io_bias_0,	// src/main/scala/pe.scala:16:14
               io_bias_1,	// src/main/scala/pe.scala:16:14
               io_bias_2,	// src/main/scala/pe.scala:16:14
               io_bias_3,	// src/main/scala/pe.scala:16:14
               io_bias_4,	// src/main/scala/pe.scala:16:14
               io_bias_5,	// src/main/scala/pe.scala:16:14
               io_bias_6,	// src/main/scala/pe.scala:16:14
               io_bias_7,	// src/main/scala/pe.scala:16:14
               io_bias_8,	// src/main/scala/pe.scala:16:14
               io_V_t,	// src/main/scala/pe.scala:16:14
  input        io_thresh_enab,	// src/main/scala/pe.scala:16:14
               io_conv_enab,	// src/main/scala/pe.scala:16:14
  input  [7:0] io_kernel_0,	// src/main/scala/pe.scala:16:14
               io_kernel_1,	// src/main/scala/pe.scala:16:14
               io_kernel_2,	// src/main/scala/pe.scala:16:14
               io_kernel_3,	// src/main/scala/pe.scala:16:14
               io_kernel_4,	// src/main/scala/pe.scala:16:14
               io_kernel_5,	// src/main/scala/pe.scala:16:14
               io_kernel_6,	// src/main/scala/pe.scala:16:14
               io_kernel_7,	// src/main/scala/pe.scala:16:14
               io_kernel_8	// src/main/scala/pe.scala:16:14
);

  wire [8:0] _mempotMem_io_dout_0;	// src/main/scala/pe.scala:37:25
  wire [8:0] _mempotMem_io_dout_1;	// src/main/scala/pe.scala:37:25
  wire [8:0] _mempotMem_io_dout_2;	// src/main/scala/pe.scala:37:25
  wire [8:0] _mempotMem_io_dout_3;	// src/main/scala/pe.scala:37:25
  wire [8:0] _mempotMem_io_dout_4;	// src/main/scala/pe.scala:37:25
  wire [8:0] _mempotMem_io_dout_5;	// src/main/scala/pe.scala:37:25
  wire [8:0] _mempotMem_io_dout_6;	// src/main/scala/pe.scala:37:25
  wire [8:0] _mempotMem_io_dout_7;	// src/main/scala/pe.scala:37:25
  wire [8:0] _mempotMem_io_dout_8;	// src/main/scala/pe.scala:37:25
  reg  [8:0] s2_memRead_0;	// src/main/scala/pe.scala:53:23
  reg  [8:0] s2_memRead_1;	// src/main/scala/pe.scala:53:23
  reg  [8:0] s2_memRead_2;	// src/main/scala/pe.scala:53:23
  reg  [8:0] s2_memRead_3;	// src/main/scala/pe.scala:53:23
  reg  [8:0] s2_memRead_4;	// src/main/scala/pe.scala:53:23
  reg  [8:0] s2_memRead_5;	// src/main/scala/pe.scala:53:23
  reg  [8:0] s2_memRead_6;	// src/main/scala/pe.scala:53:23
  reg  [8:0] s2_memRead_7;	// src/main/scala/pe.scala:53:23
  reg  [8:0] s2_memRead_8;	// src/main/scala/pe.scala:53:23
  reg  [8:0] s3_updates_0;	// src/main/scala/pe.scala:54:23
  reg  [8:0] s3_updates_1;	// src/main/scala/pe.scala:54:23
  reg  [8:0] s3_updates_2;	// src/main/scala/pe.scala:54:23
  reg  [8:0] s3_updates_3;	// src/main/scala/pe.scala:54:23
  reg  [8:0] s3_updates_4;	// src/main/scala/pe.scala:54:23
  reg  [8:0] s3_updates_5;	// src/main/scala/pe.scala:54:23
  reg  [8:0] s3_updates_6;	// src/main/scala/pe.scala:54:23
  reg  [8:0] s3_updates_7;	// src/main/scala/pe.scala:54:23
  reg  [8:0] s3_updates_8;	// src/main/scala/pe.scala:54:23
  reg        validS1;	// src/main/scala/pe.scala:56:24
  reg        validS2;	// src/main/scala/pe.scala:57:24
  reg        validS3;	// src/main/scala/pe.scala:58:24
  reg        validS4;	// src/main/scala/pe.scala:59:24
  always @(posedge clock) begin	// src/main/scala/pe.scala:15:7
    automatic logic _GEN;	// src/main/scala/pe.scala:67:18
    automatic logic _GEN_0;	// src/main/scala/pe.scala:89:18
    automatic logic _GEN_1;	// src/main/scala/pe.scala:97:18
    _GEN = validS2 & validS3;	// src/main/scala/pe.scala:57:24, :58:24, :67:18
    _GEN_0 = validS1 & ~_GEN;	// src/main/scala/pe.scala:56:24, :67:18, :73:30, :89:18
    _GEN_1 = validS2 & ~_GEN;	// src/main/scala/pe.scala:57:24, :67:18, :73:30, :97:18
    if (validS2 & validS4) begin	// src/main/scala/pe.scala:57:24, :59:24, :115:16
      s2_memRead_0 <= s3_updates_0;	// src/main/scala/pe.scala:53:23, :54:23
      s2_memRead_1 <= s3_updates_1;	// src/main/scala/pe.scala:53:23, :54:23
      s2_memRead_2 <= s3_updates_2;	// src/main/scala/pe.scala:53:23, :54:23
      s2_memRead_3 <= s3_updates_3;	// src/main/scala/pe.scala:53:23, :54:23
      s2_memRead_4 <= s3_updates_4;	// src/main/scala/pe.scala:53:23, :54:23
      s2_memRead_5 <= s3_updates_5;	// src/main/scala/pe.scala:53:23, :54:23
      s2_memRead_6 <= s3_updates_6;	// src/main/scala/pe.scala:53:23, :54:23
      s2_memRead_7 <= s3_updates_7;	// src/main/scala/pe.scala:53:23, :54:23
      s2_memRead_8 <= s3_updates_8;	// src/main/scala/pe.scala:53:23, :54:23
    end
    else if (_GEN_0) begin	// src/main/scala/pe.scala:89:18
      s2_memRead_0 <= _mempotMem_io_dout_0;	// src/main/scala/pe.scala:37:25, :53:23
      s2_memRead_1 <= _mempotMem_io_dout_1;	// src/main/scala/pe.scala:37:25, :53:23
      s2_memRead_2 <= _mempotMem_io_dout_2;	// src/main/scala/pe.scala:37:25, :53:23
      s2_memRead_3 <= _mempotMem_io_dout_3;	// src/main/scala/pe.scala:37:25, :53:23
      s2_memRead_4 <= _mempotMem_io_dout_4;	// src/main/scala/pe.scala:37:25, :53:23
      s2_memRead_5 <= _mempotMem_io_dout_5;	// src/main/scala/pe.scala:37:25, :53:23
      s2_memRead_6 <= _mempotMem_io_dout_6;	// src/main/scala/pe.scala:37:25, :53:23
      s2_memRead_7 <= _mempotMem_io_dout_7;	// src/main/scala/pe.scala:37:25, :53:23
      s2_memRead_8 <= _mempotMem_io_dout_8;	// src/main/scala/pe.scala:37:25, :53:23
    end
    if (_GEN_1) begin	// src/main/scala/pe.scala:97:18
      automatic logic [8:0] _update_T;	// src/main/scala/pe.scala:99:36
      automatic logic [8:0] _update_T_1;	// src/main/scala/pe.scala:99:36
      automatic logic [8:0] _update_T_2;	// src/main/scala/pe.scala:99:36
      automatic logic [8:0] _update_T_3;	// src/main/scala/pe.scala:99:36
      automatic logic [8:0] _update_T_4;	// src/main/scala/pe.scala:99:36
      automatic logic [8:0] _update_T_5;	// src/main/scala/pe.scala:99:36
      automatic logic [8:0] _update_T_6;	// src/main/scala/pe.scala:99:36
      automatic logic [8:0] _update_T_7;	// src/main/scala/pe.scala:99:36
      automatic logic [8:0] _update_T_8;	// src/main/scala/pe.scala:99:36
      _update_T = s2_memRead_0 + {1'h0, io_kernel_0};	// src/main/scala/pe.scala:53:23, :56:24, :99:36
      _update_T_1 = s2_memRead_1 + {1'h0, io_kernel_1};	// src/main/scala/pe.scala:53:23, :56:24, :99:36
      _update_T_2 = s2_memRead_2 + {1'h0, io_kernel_2};	// src/main/scala/pe.scala:53:23, :56:24, :99:36
      _update_T_3 = s2_memRead_3 + {1'h0, io_kernel_3};	// src/main/scala/pe.scala:53:23, :56:24, :99:36
      _update_T_4 = s2_memRead_4 + {1'h0, io_kernel_4};	// src/main/scala/pe.scala:53:23, :56:24, :99:36
      _update_T_5 = s2_memRead_5 + {1'h0, io_kernel_5};	// src/main/scala/pe.scala:53:23, :56:24, :99:36
      _update_T_6 = s2_memRead_6 + {1'h0, io_kernel_6};	// src/main/scala/pe.scala:53:23, :56:24, :99:36
      _update_T_7 = s2_memRead_7 + {1'h0, io_kernel_7};	// src/main/scala/pe.scala:53:23, :56:24, :99:36
      _update_T_8 = s2_memRead_8 + {1'h0, io_kernel_8};	// src/main/scala/pe.scala:53:23, :56:24, :99:36
      s3_updates_0 <= _update_T[8] ? 9'hFF : _update_T;	// src/main/scala/pe.scala:54:23, :99:36, :100:{29,37}
      s3_updates_1 <= _update_T_1[8] ? 9'hFF : _update_T_1;	// src/main/scala/pe.scala:54:23, :99:36, :100:{29,37}
      s3_updates_2 <= _update_T_2[8] ? 9'hFF : _update_T_2;	// src/main/scala/pe.scala:54:23, :99:36, :100:{29,37}
      s3_updates_3 <= _update_T_3[8] ? 9'hFF : _update_T_3;	// src/main/scala/pe.scala:54:23, :99:36, :100:{29,37}
      s3_updates_4 <= _update_T_4[8] ? 9'hFF : _update_T_4;	// src/main/scala/pe.scala:54:23, :99:36, :100:{29,37}
      s3_updates_5 <= _update_T_5[8] ? 9'hFF : _update_T_5;	// src/main/scala/pe.scala:54:23, :99:36, :100:{29,37}
      s3_updates_6 <= _update_T_6[8] ? 9'hFF : _update_T_6;	// src/main/scala/pe.scala:54:23, :99:36, :100:{29,37}
      s3_updates_7 <= _update_T_7[8] ? 9'hFF : _update_T_7;	// src/main/scala/pe.scala:54:23, :99:36, :100:{29,37}
      s3_updates_8 <= _update_T_8[8] ? 9'hFF : _update_T_8;	// src/main/scala/pe.scala:54:23, :99:36, :100:{29,37}
    end
    if (reset) begin	// src/main/scala/pe.scala:15:7
      validS1 <= 1'h0;	// src/main/scala/pe.scala:56:24
      validS2 <= 1'h0;	// src/main/scala/pe.scala:56:24, :57:24
      validS3 <= 1'h0;	// src/main/scala/pe.scala:56:24, :58:24
      validS4 <= 1'h0;	// src/main/scala/pe.scala:56:24, :59:24
    end
    else begin	// src/main/scala/pe.scala:15:7
      automatic logic _GEN_2;	// src/main/scala/pe.scala:122:16
      _GEN_2 = validS4 & ~_GEN;	// src/main/scala/pe.scala:59:24, :67:18, :73:30, :122:16
      validS1 <= ~_GEN_2 & (io_rd_enable_aeq & ~_GEN | validS1);	// src/main/scala/pe.scala:56:24, :67:18, :73:{27,30,46}, :85:17, :122:{16,35}, :123:13
      validS2 <= ~_GEN_2 & (_GEN_0 | validS2);	// src/main/scala/pe.scala:57:24, :73:46, :89:{18,37}, :93:17, :122:{16,35}, :123:13, :124:13
      validS3 <= ~_GEN_2 & (_GEN_1 | validS3);	// src/main/scala/pe.scala:58:24, :73:46, :97:{18,37}, :102:17, :122:{16,35}, :123:13, :125:13
      validS4 <= ~_GEN_2 & (validS3 | validS4);	// src/main/scala/pe.scala:58:24, :59:24, :73:46, :106:17, :111:13, :122:{16,35}, :123:13, :126:13
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/pe.scala:15:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/pe.scala:15:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/pe.scala:15:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/pe.scala:15:7
      automatic logic [31:0] _RANDOM[0:7];	// src/main/scala/pe.scala:15:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/pe.scala:15:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/pe.scala:15:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/pe.scala:15:7
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;	// src/main/scala/pe.scala:15:7
        end	// src/main/scala/pe.scala:15:7
        s2_memRead_0 = _RANDOM[3'h2][16:8];	// src/main/scala/pe.scala:15:7, :53:23
        s2_memRead_1 = _RANDOM[3'h2][25:17];	// src/main/scala/pe.scala:15:7, :53:23
        s2_memRead_2 = {_RANDOM[3'h2][31:26], _RANDOM[3'h3][2:0]};	// src/main/scala/pe.scala:15:7, :53:23
        s2_memRead_3 = _RANDOM[3'h3][11:3];	// src/main/scala/pe.scala:15:7, :53:23
        s2_memRead_4 = _RANDOM[3'h3][20:12];	// src/main/scala/pe.scala:15:7, :53:23
        s2_memRead_5 = _RANDOM[3'h3][29:21];	// src/main/scala/pe.scala:15:7, :53:23
        s2_memRead_6 = {_RANDOM[3'h3][31:30], _RANDOM[3'h4][6:0]};	// src/main/scala/pe.scala:15:7, :53:23
        s2_memRead_7 = _RANDOM[3'h4][15:7];	// src/main/scala/pe.scala:15:7, :53:23
        s2_memRead_8 = _RANDOM[3'h4][24:16];	// src/main/scala/pe.scala:15:7, :53:23
        s3_updates_0 = {_RANDOM[3'h4][31:25], _RANDOM[3'h5][1:0]};	// src/main/scala/pe.scala:15:7, :53:23, :54:23
        s3_updates_1 = _RANDOM[3'h5][10:2];	// src/main/scala/pe.scala:15:7, :54:23
        s3_updates_2 = _RANDOM[3'h5][19:11];	// src/main/scala/pe.scala:15:7, :54:23
        s3_updates_3 = _RANDOM[3'h5][28:20];	// src/main/scala/pe.scala:15:7, :54:23
        s3_updates_4 = {_RANDOM[3'h5][31:29], _RANDOM[3'h6][5:0]};	// src/main/scala/pe.scala:15:7, :54:23
        s3_updates_5 = _RANDOM[3'h6][14:6];	// src/main/scala/pe.scala:15:7, :54:23
        s3_updates_6 = _RANDOM[3'h6][23:15];	// src/main/scala/pe.scala:15:7, :54:23
        s3_updates_7 = {_RANDOM[3'h6][31:24], _RANDOM[3'h7][0]};	// src/main/scala/pe.scala:15:7, :54:23
        s3_updates_8 = _RANDOM[3'h7][9:1];	// src/main/scala/pe.scala:15:7, :54:23
        validS1 = _RANDOM[3'h7][10];	// src/main/scala/pe.scala:15:7, :54:23, :56:24
        validS2 = _RANDOM[3'h7][11];	// src/main/scala/pe.scala:15:7, :54:23, :57:24
        validS3 = _RANDOM[3'h7][12];	// src/main/scala/pe.scala:15:7, :54:23, :58:24
        validS4 = _RANDOM[3'h7][13];	// src/main/scala/pe.scala:15:7, :54:23, :59:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/pe.scala:15:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/pe.scala:15:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  AEQ aeqMem (	// src/main/scala/pe.scala:36:22
    .clock            (clock),
    .reset            (reset),
    .io_writeEnable_0 (io_wr_enable_aeq_0),
    .io_writeEnable_1 (io_wr_enable_aeq_1),
    .io_writeEnable_2 (io_wr_enable_aeq_2),
    .io_writeEnable_3 (io_wr_enable_aeq_3),
    .io_writeEnable_4 (io_wr_enable_aeq_4),
    .io_writeEnable_5 (io_wr_enable_aeq_5),
    .io_writeEnable_6 (io_wr_enable_aeq_6),
    .io_writeEnable_7 (io_wr_enable_aeq_7),
    .io_writeEnable_8 (io_wr_enable_aeq_8),
    .io_readEnable    (io_rd_enable_aeq),
    .io_writeData_0   (io_writeData_aeq_0),
    .io_writeData_1   (io_writeData_aeq_1),
    .io_writeData_2   (io_writeData_aeq_2),
    .io_writeData_3   (io_writeData_aeq_3),
    .io_writeData_4   (io_writeData_aeq_4),
    .io_writeData_5   (io_writeData_aeq_5),
    .io_writeData_6   (io_writeData_aeq_6),
    .io_writeData_7   (io_writeData_aeq_7),
    .io_writeData_8   (io_writeData_aeq_8),
    .io_readData_0    (io_readData_aeq_0),
    .io_readData_1    (io_readData_aeq_1),
    .io_readData_2    (io_readData_aeq_2),
    .io_readData_3    (io_readData_aeq_3),
    .io_readData_4    (io_readData_aeq_4),
    .io_readData_5    (io_readData_aeq_5),
    .io_readData_6    (io_readData_aeq_6),
    .io_readData_7    (io_readData_aeq_7),
    .io_readData_8    (io_readData_aeq_8)
  );
  mempot mempotMem (	// src/main/scala/pe.scala:37:25
    .clock          (clock),
    .io_wr_enable_0 (validS3 | io_wr_enable_mempot_0),	// src/main/scala/pe.scala:44:26, :58:24, :106:17, :108:33
    .io_wr_enable_1 (validS3 | io_wr_enable_mempot_1),	// src/main/scala/pe.scala:44:26, :58:24, :106:17, :108:33
    .io_wr_enable_2 (validS3 | io_wr_enable_mempot_2),	// src/main/scala/pe.scala:44:26, :58:24, :106:17, :108:33
    .io_wr_enable_3 (validS3 | io_wr_enable_mempot_3),	// src/main/scala/pe.scala:44:26, :58:24, :106:17, :108:33
    .io_wr_enable_4 (validS3 | io_wr_enable_mempot_4),	// src/main/scala/pe.scala:44:26, :58:24, :106:17, :108:33
    .io_wr_enable_5 (validS3 | io_wr_enable_mempot_5),	// src/main/scala/pe.scala:44:26, :58:24, :106:17, :108:33
    .io_wr_enable_6 (validS3 | io_wr_enable_mempot_6),	// src/main/scala/pe.scala:44:26, :58:24, :106:17, :108:33
    .io_wr_enable_7 (validS3 | io_wr_enable_mempot_7),	// src/main/scala/pe.scala:44:26, :58:24, :106:17, :108:33
    .io_wr_enable_8 (validS3 | io_wr_enable_mempot_8),	// src/main/scala/pe.scala:44:26, :58:24, :106:17, :108:33
    .io_rd_enable_0 (io_rd_enable_mempot_0),
    .io_rd_enable_1 (io_rd_enable_mempot_1),
    .io_rd_enable_2 (io_rd_enable_mempot_2),
    .io_rd_enable_3 (io_rd_enable_mempot_3),
    .io_rd_enable_4 (io_rd_enable_mempot_4),
    .io_rd_enable_5 (io_rd_enable_mempot_5),
    .io_rd_enable_6 (io_rd_enable_mempot_6),
    .io_rd_enable_7 (io_rd_enable_mempot_7),
    .io_rd_enable_8 (io_rd_enable_mempot_8),
    .io_addr_r_0    (io_addr_r_mempot_0),
    .io_addr_r_1    (io_addr_r_mempot_1),
    .io_addr_r_2    (io_addr_r_mempot_2),
    .io_addr_r_3    (io_addr_r_mempot_3),
    .io_addr_r_4    (io_addr_r_mempot_4),
    .io_addr_r_5    (io_addr_r_mempot_5),
    .io_addr_r_6    (io_addr_r_mempot_6),
    .io_addr_r_7    (io_addr_r_mempot_7),
    .io_addr_r_8    (io_addr_r_mempot_8),
    .io_addr_w_0    (io_addr_w_mempot_0),
    .io_addr_w_1    (io_addr_w_mempot_1),
    .io_addr_w_2    (io_addr_w_mempot_2),
    .io_addr_w_3    (io_addr_w_mempot_3),
    .io_addr_w_4    (io_addr_w_mempot_4),
    .io_addr_w_5    (io_addr_w_mempot_5),
    .io_addr_w_6    (io_addr_w_mempot_6),
    .io_addr_w_7    (io_addr_w_mempot_7),
    .io_addr_w_8    (io_addr_w_mempot_8),
    .io_din_0       (validS3 ? s3_updates_0 : io_din_mempot_0),	// src/main/scala/pe.scala:48:20, :54:23, :58:24, :106:17, :109:27
    .io_din_1       (validS3 ? s3_updates_1 : io_din_mempot_1),	// src/main/scala/pe.scala:48:20, :54:23, :58:24, :106:17, :109:27
    .io_din_2       (validS3 ? s3_updates_2 : io_din_mempot_2),	// src/main/scala/pe.scala:48:20, :54:23, :58:24, :106:17, :109:27
    .io_din_3       (validS3 ? s3_updates_3 : io_din_mempot_3),	// src/main/scala/pe.scala:48:20, :54:23, :58:24, :106:17, :109:27
    .io_din_4       (validS3 ? s3_updates_4 : io_din_mempot_4),	// src/main/scala/pe.scala:48:20, :54:23, :58:24, :106:17, :109:27
    .io_din_5       (validS3 ? s3_updates_5 : io_din_mempot_5),	// src/main/scala/pe.scala:48:20, :54:23, :58:24, :106:17, :109:27
    .io_din_6       (validS3 ? s3_updates_6 : io_din_mempot_6),	// src/main/scala/pe.scala:48:20, :54:23, :58:24, :106:17, :109:27
    .io_din_7       (validS3 ? s3_updates_7 : io_din_mempot_7),	// src/main/scala/pe.scala:48:20, :54:23, :58:24, :106:17, :109:27
    .io_din_8       (validS3 ? s3_updates_8 : io_din_mempot_8),	// src/main/scala/pe.scala:48:20, :54:23, :58:24, :106:17, :109:27
    .io_dout_0      (_mempotMem_io_dout_0),
    .io_dout_1      (_mempotMem_io_dout_1),
    .io_dout_2      (_mempotMem_io_dout_2),
    .io_dout_3      (_mempotMem_io_dout_3),
    .io_dout_4      (_mempotMem_io_dout_4),
    .io_dout_5      (_mempotMem_io_dout_5),
    .io_dout_6      (_mempotMem_io_dout_6),
    .io_dout_7      (_mempotMem_io_dout_7),
    .io_dout_8      (_mempotMem_io_dout_8)
  );
  assign io_dout_mempot_0 = _mempotMem_io_dout_0;	// src/main/scala/pe.scala:15:7, :37:25
  assign io_dout_mempot_1 = _mempotMem_io_dout_1;	// src/main/scala/pe.scala:15:7, :37:25
  assign io_dout_mempot_2 = _mempotMem_io_dout_2;	// src/main/scala/pe.scala:15:7, :37:25
  assign io_dout_mempot_3 = _mempotMem_io_dout_3;	// src/main/scala/pe.scala:15:7, :37:25
  assign io_dout_mempot_4 = _mempotMem_io_dout_4;	// src/main/scala/pe.scala:15:7, :37:25
  assign io_dout_mempot_5 = _mempotMem_io_dout_5;	// src/main/scala/pe.scala:15:7, :37:25
  assign io_dout_mempot_6 = _mempotMem_io_dout_6;	// src/main/scala/pe.scala:15:7, :37:25
  assign io_dout_mempot_7 = _mempotMem_io_dout_7;	// src/main/scala/pe.scala:15:7, :37:25
  assign io_dout_mempot_8 = _mempotMem_io_dout_8;	// src/main/scala/pe.scala:15:7, :37:25
endmodule

