// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module tile(	// src/main/scala/tile.scala:8:7
  input         clock,	// src/main/scala/tile.scala:8:7
                reset,	// src/main/scala/tile.scala:8:7
  output        io_rd_en_aeq_i,	// src/main/scala/tile.scala:9:16
  output [8:0]  io_rd_addr_aeq_i,	// src/main/scala/tile.scala:9:16
  input  [10:0] io_rd_data_aeq_i,	// src/main/scala/tile.scala:9:16
  output        io_wr_en_aeq_o,	// src/main/scala/tile.scala:9:16
  output [8:0]  io_wr_addr_aeq_o,	// src/main/scala/tile.scala:9:16
  output [10:0] io_wr_data_aeq_o,	// src/main/scala/tile.scala:9:16
  output        io_wr_en_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_8,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_wr_addr_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_8,	// src/main/scala/tile.scala:9:16
  output [8:0]  io_wr_data_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_8,	// src/main/scala/tile.scala:9:16
  output        io_rd_en_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_8,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_rd_addr_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_8,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_rd_data_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_8,	// src/main/scala/tile.scala:9:16
  output        io_wr_en_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_wr_en_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_wr_en_L2_N_2,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_wr_addr_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_wr_addr_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_wr_addr_L2_N_2,	// src/main/scala/tile.scala:9:16
  output [8:0]  io_wr_data_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_wr_data_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_wr_data_L2_N_2,	// src/main/scala/tile.scala:9:16
  output        io_rd_en_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_rd_en_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_rd_en_L2_N_2,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_rd_addr_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L2_N_2,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_rd_data_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_rd_data_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_rd_data_L2_N_2,	// src/main/scala/tile.scala:9:16
  output        io_wr_en_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_wr_en_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_wr_en_L2_S_2,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_wr_addr_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_wr_addr_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_wr_addr_L2_S_2,	// src/main/scala/tile.scala:9:16
  output [8:0]  io_wr_data_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_wr_data_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_wr_data_L2_S_2,	// src/main/scala/tile.scala:9:16
  output        io_rd_en_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_rd_en_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_rd_en_L2_S_2,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_rd_addr_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L2_S_2,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_rd_data_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_rd_data_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_rd_data_L2_S_2,	// src/main/scala/tile.scala:9:16
  output        io_rd_en_L1_N,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_rd_addr_L1_N_0,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L1_N_1,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L1_N_2,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_rd_data_L1_N_0,	// src/main/scala/tile.scala:9:16
                io_rd_data_L1_N_1,	// src/main/scala/tile.scala:9:16
                io_rd_data_L1_N_2,	// src/main/scala/tile.scala:9:16
  output        io_rd_en_L1_S,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_rd_addr_L1_S_0,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L1_S_1,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L1_S_2,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_rd_data_L1_S_0,	// src/main/scala/tile.scala:9:16
                io_rd_data_L1_S_1,	// src/main/scala/tile.scala:9:16
                io_rd_data_L1_S_2,	// src/main/scala/tile.scala:9:16
  input         io_thresh_en,	// src/main/scala/tile.scala:9:16
                io_conv_en,	// src/main/scala/tile.scala:9:16
  input  [7:0]  io_bias_0,	// src/main/scala/tile.scala:9:16
                io_bias_1,	// src/main/scala/tile.scala:9:16
                io_bias_2,	// src/main/scala/tile.scala:9:16
                io_bias_3,	// src/main/scala/tile.scala:9:16
                io_bias_4,	// src/main/scala/tile.scala:9:16
                io_bias_5,	// src/main/scala/tile.scala:9:16
                io_bias_6,	// src/main/scala/tile.scala:9:16
                io_bias_7,	// src/main/scala/tile.scala:9:16
                io_bias_8,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_v_t,	// src/main/scala/tile.scala:9:16
  input  [7:0]  io_kernel_0,	// src/main/scala/tile.scala:9:16
                io_kernel_1,	// src/main/scala/tile.scala:9:16
                io_kernel_2,	// src/main/scala/tile.scala:9:16
                io_kernel_3,	// src/main/scala/tile.scala:9:16
                io_kernel_4,	// src/main/scala/tile.scala:9:16
                io_kernel_5,	// src/main/scala/tile.scala:9:16
                io_kernel_6,	// src/main/scala/tile.scala:9:16
                io_kernel_7,	// src/main/scala/tile.scala:9:16
                io_kernel_8,	// src/main/scala/tile.scala:9:16
  output        io_conv_done,	// src/main/scala/tile.scala:9:16
                io_thresh_done	// src/main/scala/tile.scala:9:16
);

  reg  [8:0] s1_addr_calc_0;	// src/main/scala/tile.scala:113:27
  reg  [8:0] s1_addr_calc_1;	// src/main/scala/tile.scala:113:27
  reg  [8:0] s2_mempot_rd_0;	// src/main/scala/tile.scala:114:27
  reg  [8:0] s2_mempot_rd_1;	// src/main/scala/tile.scala:114:27
  reg  [8:0] s2_mempot_rd_2;	// src/main/scala/tile.scala:114:27
  reg  [8:0] s2_mempot_rd_3;	// src/main/scala/tile.scala:114:27
  reg  [8:0] s2_mempot_rd_4;	// src/main/scala/tile.scala:114:27
  reg  [8:0] s2_mempot_rd_5;	// src/main/scala/tile.scala:114:27
  reg  [8:0] s2_mempot_rd_6;	// src/main/scala/tile.scala:114:27
  reg  [8:0] s2_mempot_rd_7;	// src/main/scala/tile.scala:114:27
  reg  [8:0] s2_mempot_rd_8;	// src/main/scala/tile.scala:114:27
  reg  [8:0] s3_conv_0;	// src/main/scala/tile.scala:115:22
  reg  [8:0] s3_conv_1;	// src/main/scala/tile.scala:115:22
  reg  [8:0] s3_conv_2;	// src/main/scala/tile.scala:115:22
  reg  [8:0] s3_conv_3;	// src/main/scala/tile.scala:115:22
  reg  [8:0] s3_conv_4;	// src/main/scala/tile.scala:115:22
  reg  [8:0] s3_conv_5;	// src/main/scala/tile.scala:115:22
  reg  [8:0] s3_conv_6;	// src/main/scala/tile.scala:115:22
  reg  [8:0] s3_conv_7;	// src/main/scala/tile.scala:115:22
  reg  [8:0] s3_conv_8;	// src/main/scala/tile.scala:115:22
  reg        s1_valid;	// src/main/scala/tile.scala:117:27
  reg        s2_valid;	// src/main/scala/tile.scala:118:27
  reg        s3_valid;	// src/main/scala/tile.scala:119:27
  reg        conv_done_reg;	// src/main/scala/tile.scala:124:32
  reg        thresh_done_reg;	// src/main/scala/tile.scala:125:34
  reg  [7:0] read_counter;	// src/main/scala/tile.scala:135:31
  wire       io_rd_en_aeq_i_0 = io_conv_en & ~conv_done_reg;	// src/main/scala/tile.scala:124:32, :136:{36,39}
  reg        i;	// src/main/scala/tile.scala:150:28
  wire       _GEN = s1_valid & io_conv_en;	// src/main/scala/tile.scala:117:27, :172:34
  wire       _GEN_0 = s1_addr_calc_0[8:4] < 5'h9 & s1_addr_calc_0[3:0] < 4'h3;	// src/main/scala/tile.scala:8:7, :113:27, :158:37, :193:{40,46,58,78,85}
  wire       io_rd_en_L2_N_2_0 = _GEN & _GEN_0;	// src/main/scala/tile.scala:87:19, :172:{34,48}, :174:92, :193:58
  wire       _GEN_1 = _GEN & _GEN_0;	// src/main/scala/tile.scala:88:21, :172:{34,48}, :174:92, :193:58
  wire       _GEN_2 = ~_GEN | _GEN_0;	// src/main/scala/tile.scala:82:28, :172:{34,48}, :174:92, :193:58
  wire       io_wr_en_main_mempot_5_0 = s3_valid & io_conv_en;	// src/main/scala/tile.scala:119:27, :233:19
  wire       io_wr_en_L2_S_2_0 = io_wr_en_main_mempot_5_0 & _GEN_0;	// src/main/scala/tile.scala:90:19, :193:58, :233:{19,34}, :235:92
  wire       _GEN_3 = io_wr_en_main_mempot_5_0 & _GEN_0;	// src/main/scala/tile.scala:91:21, :193:58, :233:{19,34}, :235:92
  wire       io_wr_en_main_mempot_2_0 = io_wr_en_main_mempot_5_0 & ~_GEN_0;	// src/main/scala/tile.scala:70:20, :77:26, :81:26, :137:24, :193:{58,98}, :215:41, :233:{19,34}, :235:92
  wire       _GEN_4 = ~io_wr_en_main_mempot_5_0 | _GEN_0;	// src/main/scala/tile.scala:78:28, :193:58, :233:{19,34}, :235:92
  wire       _GEN_5 = io_thresh_en & ~io_conv_en;	// src/main/scala/tile.scala:287:{57,60}
  reg  [4:0] read_mem_counter;	// src/main/scala/chisel3/util/Counter.scala:61:40
  wire       wrap_wrap = read_mem_counter == 5'h11;	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24, src/main/scala/tile.scala:8:7
  wire       wrap = _GEN_5 & wrap_wrap;	// src/main/scala/chisel3/util/Counter.scala:73:24, :117:24, :118:{16,23}, src/main/scala/tile.scala:287:57
  reg  [4:0] thresh_blk_counter;	// src/main/scala/tile.scala:288:33
  reg  [8:0] s1_thresh_main_mem_rd_0;	// src/main/scala/tile.scala:299:36
  reg  [8:0] s1_thresh_main_mem_rd_1;	// src/main/scala/tile.scala:299:36
  reg  [8:0] s1_thresh_main_mem_rd_2;	// src/main/scala/tile.scala:299:36
  reg  [8:0] s1_thresh_main_mem_rd_3;	// src/main/scala/tile.scala:299:36
  reg  [8:0] s1_thresh_main_mem_rd_4;	// src/main/scala/tile.scala:299:36
  reg  [8:0] s1_thresh_main_mem_rd_5;	// src/main/scala/tile.scala:299:36
  reg  [8:0] s1_thresh_main_mem_rd_6;	// src/main/scala/tile.scala:299:36
  reg  [8:0] s1_thresh_main_mem_rd_7;	// src/main/scala/tile.scala:299:36
  reg  [8:0] s1_thresh_main_mem_rd_8;	// src/main/scala/tile.scala:299:36
  reg  [8:0] s1_thresh_local_mem_rd_0;	// src/main/scala/tile.scala:300:37
  reg  [8:0] s1_thresh_local_mem_rd_1;	// src/main/scala/tile.scala:300:37
  reg  [8:0] s1_thresh_local_mem_rd_2;	// src/main/scala/tile.scala:300:37
  reg  [8:0] s2_thresh_bias_added_0;	// src/main/scala/tile.scala:301:35
  reg  [8:0] s2_thresh_bias_added_1;	// src/main/scala/tile.scala:301:35
  reg  [8:0] s2_thresh_bias_added_2;	// src/main/scala/tile.scala:301:35
  reg  [8:0] s2_thresh_bias_added_3;	// src/main/scala/tile.scala:301:35
  reg  [8:0] s2_thresh_bias_added_4;	// src/main/scala/tile.scala:301:35
  reg  [8:0] s2_thresh_bias_added_5;	// src/main/scala/tile.scala:301:35
  reg  [8:0] s2_thresh_bias_added_6;	// src/main/scala/tile.scala:301:35
  reg  [8:0] s2_thresh_bias_added_7;	// src/main/scala/tile.scala:301:35
  reg  [8:0] s2_thresh_bias_added_8;	// src/main/scala/tile.scala:301:35
  reg  [9:0] s3_thresh_aeq_out_data_0;	// src/main/scala/tile.scala:302:37
  reg  [9:0] s3_thresh_aeq_out_data_1;	// src/main/scala/tile.scala:302:37
  reg  [9:0] s3_thresh_aeq_out_data_2;	// src/main/scala/tile.scala:302:37
  reg  [9:0] s3_thresh_aeq_out_data_3;	// src/main/scala/tile.scala:302:37
  reg  [9:0] s3_thresh_aeq_out_data_4;	// src/main/scala/tile.scala:302:37
  reg  [9:0] s3_thresh_aeq_out_data_5;	// src/main/scala/tile.scala:302:37
  reg  [9:0] s3_thresh_aeq_out_data_6;	// src/main/scala/tile.scala:302:37
  reg  [9:0] s3_thresh_aeq_out_data_7;	// src/main/scala/tile.scala:302:37
  reg  [9:0] s3_thresh_aeq_out_data_8;	// src/main/scala/tile.scala:302:37
  reg        s1_thresh_valid;	// src/main/scala/tile.scala:305:34
  reg        s2_thresh_valid;	// src/main/scala/tile.scala:306:34
  reg        s3_thresh_valid;	// src/main/scala/tile.scala:307:34
  wire       _GEN_6 = io_thresh_en & ~wrap;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/tile.scala:311:{23,26}
  wire       _GEN_7 = thresh_blk_counter < 5'h9;	// src/main/scala/tile.scala:8:7, :288:33, :312:33
  wire [7:0] _GEN_8 = {3'h0, thresh_blk_counter};	// src/main/scala/tile.scala:148:42, :288:33, :316:36
  wire [7:0] io_rd_addr_L1_N_2_0 = _GEN_6 & _GEN_7 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:78:38, :97:21, :311:{23,32}, :312:{33,39}, :316:36
  wire       _GEN_9 = thresh_blk_counter > 5'h8;	// src/main/scala/tile.scala:8:7, :288:33, :326:40
  wire [7:0] io_rd_addr_L1_S_2_0 = ~_GEN_6 | _GEN_7 | ~_GEN_9 ? 8'h0 : _GEN_8;	// src/main/scala/tile.scala:78:38, :100:21, :311:{23,32}, :312:{33,39}, :316:36, :326:{40,47}
  wire       _GEN_10 = _GEN_6 & (_GEN_7 | _GEN_9);	// src/main/scala/tile.scala:172:48, :311:{23,32}, :312:{33,39}, :321:41, :326:{40,47}, :335:41
  wire       io_rd_en_main_mempot_2_0 = _GEN_10 | _GEN & ~_GEN_0;	// src/main/scala/tile.scala:70:20, :81:26, :137:24, :172:{34,48}, :174:92, :193:{58,98}, :215:41, :311:32, :312:39, :321:41, :326:47, :335:41
  wire       _GEN_11 = _GEN_6 & (_GEN_7 | _GEN_9);	// src/main/scala/tile.scala:172:48, :311:{23,32}, :312:{33,39}, :322:43, :326:{40,47}
  wire       io_rd_en_main_mempot_5_0 = _GEN_10 | _GEN;	// src/main/scala/tile.scala:172:{34,48}, :311:32, :312:39, :321:41, :326:47, :335:41
  wire       io_rd_en_main_mempot_8_0 = _GEN_10 | _GEN;	// src/main/scala/tile.scala:172:{34,48}, :311:32, :312:39, :321:41, :326:47, :335:41
  reg  [4:0] s3_thresh_blk_counter;	// src/main/scala/tile.scala:359:36
  reg  [4:0] s4_thresh_aeq_counter;	// src/main/scala/tile.scala:379:36
  always @(posedge clock) begin	// src/main/scala/tile.scala:8:7
    automatic logic       _GEN_12;	// src/main/scala/tile.scala:142:29
    automatic logic [3:0] _m_T_2 = io_rd_data_aeq_i[4:1] % 4'h3;	// src/main/scala/tile.scala:144:37, :146:52, :158:37
    automatic logic [6:0] _mk_T_26 =
      {2'h0, io_rd_data_aeq_i[9:5] / 5'h9} * 7'h3 + {5'h0, _m_T_2[1:0]} + 7'h1;	// src/main/scala/tile.scala:8:7, :143:37, :146:{25,35,42,52}, :153:37
    automatic logic [4:0] _n_T = io_rd_data_aeq_i[9:5] % 5'h9;	// src/main/scala/tile.scala:8:7, :143:37, :148:35
    automatic logic [5:0] _nl_T_26 =
      {2'h0, _n_T[3:0]} * 6'h3 + {2'h0, io_rd_data_aeq_i[4:1] / 4'h3} + 6'h1;	// src/main/scala/tile.scala:144:37, :146:25, :148:{25,35,42,52}, :154:38, :158:37
    automatic logic [5:0] _col_out_T_34 = _nl_T_26 % 6'h3;	// src/main/scala/tile.scala:148:25, :154:38, :157:56
    automatic logic [6:0] _col_out_T_32 = _mk_T_26 % 7'h3;	// src/main/scala/tile.scala:146:25, :153:37, :157:40
    automatic logic [5:0] _blk_out_T_34 = _nl_T_26 / 6'h3;	// src/main/scala/tile.scala:148:25, :154:38, :156:58
    automatic logic [6:0] _blk_out_T_32 = _mk_T_26 / 7'h3;	// src/main/scala/tile.scala:146:25, :153:37, :156:46
    automatic logic [8:0] _GEN_13;	// src/main/scala/tile.scala:158:37
    automatic logic       _GEN_14;	// src/main/scala/tile.scala:113:27, :136:55, :142:49, :158:37
    automatic logic       _GEN_15;	// src/main/scala/tile.scala:224:19
    _GEN_12 = io_rd_data_aeq_i[0] & ~(io_rd_data_aeq_i[10]);	// src/main/scala/tile.scala:142:{25,29,32,44}
    _GEN_13 =
      {1'h0,
       _blk_out_T_32[3:0] * 4'h9 + _blk_out_T_34[3:0],
       {2'h0, _col_out_T_32[1:0]} * 4'h3 + {2'h0, _col_out_T_34[1:0]}};	// src/main/scala/tile.scala:70:20, :146:25, :156:{40,46,53,58}, :157:{40,46,51,56}, :158:37
    _GEN_14 = io_rd_en_aeq_i_0 & _GEN_12;	// src/main/scala/tile.scala:113:27, :136:{36,55}, :142:{29,49}, :158:37
    _GEN_15 = s2_valid & io_conv_en;	// src/main/scala/tile.scala:118:27, :224:19
    if (~_GEN_14 | i) begin	// src/main/scala/tile.scala:113:27, :136:55, :142:49, :150:28, :158:37
    end
    else	// src/main/scala/tile.scala:113:27, :136:55, :142:49, :158:37
      s1_addr_calc_0 <= _GEN_13;	// src/main/scala/tile.scala:113:27, :158:37
    if (_GEN_14 & i)	// src/main/scala/tile.scala:113:27, :136:55, :142:49, :150:28, :158:37
      s1_addr_calc_1 <= _GEN_13;	// src/main/scala/tile.scala:113:27, :158:37
    if (_GEN) begin	// src/main/scala/tile.scala:172:34
      s2_mempot_rd_0 <= _GEN_0 ? io_rd_data_L2_N_0 : io_rd_data_main_mempot_0;	// src/main/scala/tile.scala:114:27, :193:{58,98}, :197:29, :217:33
      s2_mempot_rd_1 <= _GEN_0 ? io_rd_data_L2_N_1 : io_rd_data_main_mempot_1;	// src/main/scala/tile.scala:114:27, :193:{58,98}, :201:29, :217:33
      s2_mempot_rd_2 <= _GEN_0 ? io_rd_data_L2_N_2 : io_rd_data_main_mempot_2;	// src/main/scala/tile.scala:114:27, :193:{58,98}, :205:29, :217:33
      s2_mempot_rd_3 <= io_rd_data_main_mempot_3;	// src/main/scala/tile.scala:114:27
      s2_mempot_rd_4 <= io_rd_data_main_mempot_4;	// src/main/scala/tile.scala:114:27
      s2_mempot_rd_5 <= io_rd_data_main_mempot_5;	// src/main/scala/tile.scala:114:27
      s2_mempot_rd_6 <= io_rd_data_main_mempot_6;	// src/main/scala/tile.scala:114:27
      s2_mempot_rd_7 <= io_rd_data_main_mempot_7;	// src/main/scala/tile.scala:114:27
      s2_mempot_rd_8 <= io_rd_data_main_mempot_8;	// src/main/scala/tile.scala:114:27
    end
    if (_GEN_15) begin	// src/main/scala/tile.scala:224:19
      s3_conv_0 <= s2_mempot_rd_0 + {1'h0, io_kernel_8};	// src/main/scala/tile.scala:70:20, :114:27, :115:22, :226:43
      s3_conv_1 <= s2_mempot_rd_1 + {1'h0, io_kernel_7};	// src/main/scala/tile.scala:70:20, :114:27, :115:22, :226:43
      s3_conv_2 <= s2_mempot_rd_2 + {1'h0, io_kernel_6};	// src/main/scala/tile.scala:70:20, :114:27, :115:22, :226:43
      s3_conv_3 <= s2_mempot_rd_3 + {1'h0, io_kernel_5};	// src/main/scala/tile.scala:70:20, :114:27, :115:22, :226:43
      s3_conv_4 <= s2_mempot_rd_4 + {1'h0, io_kernel_4};	// src/main/scala/tile.scala:70:20, :114:27, :115:22, :226:43
      s3_conv_5 <= s2_mempot_rd_5 + {1'h0, io_kernel_3};	// src/main/scala/tile.scala:70:20, :114:27, :115:22, :226:43
      s3_conv_6 <= s2_mempot_rd_6 + {1'h0, io_kernel_2};	// src/main/scala/tile.scala:70:20, :114:27, :115:22, :226:43
      s3_conv_7 <= s2_mempot_rd_7 + {1'h0, io_kernel_1};	// src/main/scala/tile.scala:70:20, :114:27, :115:22, :226:43
      s3_conv_8 <= s2_mempot_rd_8 + {1'h0, io_kernel_0};	// src/main/scala/tile.scala:70:20, :114:27, :115:22, :226:43
    end
    if (_GEN_6) begin	// src/main/scala/tile.scala:311:23
      thresh_blk_counter <= thresh_blk_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :288:33, :341:50
      if (_GEN_7) begin	// src/main/scala/tile.scala:312:33
        s1_thresh_local_mem_rd_0 <= io_rd_data_L1_N_0;	// src/main/scala/tile.scala:300:37
        s1_thresh_local_mem_rd_1 <= io_rd_data_L1_N_1;	// src/main/scala/tile.scala:300:37
        s1_thresh_local_mem_rd_2 <= io_rd_data_L1_N_2;	// src/main/scala/tile.scala:300:37
      end
      else if (_GEN_9) begin	// src/main/scala/tile.scala:326:40
        s1_thresh_local_mem_rd_0 <= io_rd_data_L1_S_0;	// src/main/scala/tile.scala:300:37
        s1_thresh_local_mem_rd_1 <= io_rd_data_L1_S_1;	// src/main/scala/tile.scala:300:37
        s1_thresh_local_mem_rd_2 <= io_rd_data_L1_S_2;	// src/main/scala/tile.scala:300:37
      end
    end
    if (_GEN_10) begin	// src/main/scala/tile.scala:172:48, :311:32, :312:39, :321:41, :326:47, :335:41
      s1_thresh_main_mem_rd_0 <= io_rd_data_main_mempot_0;	// src/main/scala/tile.scala:299:36
      s1_thresh_main_mem_rd_1 <= io_rd_data_main_mempot_1;	// src/main/scala/tile.scala:299:36
      s1_thresh_main_mem_rd_2 <= io_rd_data_main_mempot_2;	// src/main/scala/tile.scala:299:36
      s1_thresh_main_mem_rd_3 <= io_rd_data_main_mempot_3;	// src/main/scala/tile.scala:299:36
      s1_thresh_main_mem_rd_4 <= io_rd_data_main_mempot_4;	// src/main/scala/tile.scala:299:36
      s1_thresh_main_mem_rd_5 <= io_rd_data_main_mempot_5;	// src/main/scala/tile.scala:299:36
      s1_thresh_main_mem_rd_6 <= io_rd_data_main_mempot_6;	// src/main/scala/tile.scala:299:36
      s1_thresh_main_mem_rd_7 <= io_rd_data_main_mempot_7;	// src/main/scala/tile.scala:299:36
      s1_thresh_main_mem_rd_8 <= io_rd_data_main_mempot_8;	// src/main/scala/tile.scala:299:36
    end
    if (s1_thresh_valid) begin	// src/main/scala/tile.scala:305:34
      s2_thresh_bias_added_0 <=
        s1_thresh_main_mem_rd_0 + s1_thresh_local_mem_rd_0 + {1'h0, io_bias_0};	// src/main/scala/tile.scala:70:20, :299:36, :300:37, :301:35, :348:93
      s2_thresh_bias_added_1 <=
        s1_thresh_main_mem_rd_1 + s1_thresh_local_mem_rd_1 + {1'h0, io_bias_1};	// src/main/scala/tile.scala:70:20, :299:36, :300:37, :301:35, :348:93
      s2_thresh_bias_added_2 <=
        s1_thresh_main_mem_rd_2 + s1_thresh_local_mem_rd_2 + {1'h0, io_bias_2};	// src/main/scala/tile.scala:70:20, :299:36, :300:37, :301:35, :348:93
      s2_thresh_bias_added_3 <= s1_thresh_main_mem_rd_3 + {1'h0, io_bias_3};	// src/main/scala/tile.scala:70:20, :299:36, :301:35, :353:65
      s2_thresh_bias_added_4 <= s1_thresh_main_mem_rd_4 + {1'h0, io_bias_4};	// src/main/scala/tile.scala:70:20, :299:36, :301:35, :353:65
      s2_thresh_bias_added_5 <= s1_thresh_main_mem_rd_5 + {1'h0, io_bias_5};	// src/main/scala/tile.scala:70:20, :299:36, :301:35, :353:65
      s2_thresh_bias_added_6 <= s1_thresh_main_mem_rd_6 + {1'h0, io_bias_6};	// src/main/scala/tile.scala:70:20, :299:36, :301:35, :353:65
      s2_thresh_bias_added_7 <= s1_thresh_main_mem_rd_7 + {1'h0, io_bias_7};	// src/main/scala/tile.scala:70:20, :299:36, :301:35, :353:65
      s2_thresh_bias_added_8 <= s1_thresh_main_mem_rd_8 + {1'h0, io_bias_8};	// src/main/scala/tile.scala:70:20, :299:36, :301:35, :353:65
    end
    if (s2_thresh_valid & s2_thresh_bias_added_0 >= io_v_t)	// src/main/scala/tile.scala:301:35, :302:37, :306:34, :360:26, :361:45, :363:46
      s3_thresh_aeq_out_data_0 <= {s3_thresh_blk_counter, 5'h1};	// src/main/scala/tile.scala:8:7, :302:37, :359:36, :364:47
    if (s2_thresh_valid & s2_thresh_bias_added_1 >= io_v_t)	// src/main/scala/tile.scala:301:35, :302:37, :306:34, :360:26, :361:45, :363:46
      s3_thresh_aeq_out_data_1 <= {s3_thresh_blk_counter, 5'h3};	// src/main/scala/tile.scala:8:7, :302:37, :359:36, :364:47
    if (s2_thresh_valid & s2_thresh_bias_added_2 >= io_v_t)	// src/main/scala/tile.scala:301:35, :302:37, :306:34, :360:26, :361:45, :363:46
      s3_thresh_aeq_out_data_2 <= {s3_thresh_blk_counter, 5'h5};	// src/main/scala/tile.scala:8:7, :302:37, :359:36, :364:47
    if (s2_thresh_valid & s2_thresh_bias_added_3 >= io_v_t)	// src/main/scala/tile.scala:301:35, :302:37, :306:34, :360:26, :361:45, :363:46
      s3_thresh_aeq_out_data_3 <= {s3_thresh_blk_counter, 5'h7};	// src/main/scala/tile.scala:8:7, :302:37, :359:36, :364:47
    if (s2_thresh_valid & s2_thresh_bias_added_4 >= io_v_t)	// src/main/scala/tile.scala:301:35, :302:37, :306:34, :360:26, :361:45, :363:46
      s3_thresh_aeq_out_data_4 <= {s3_thresh_blk_counter, 5'h9};	// src/main/scala/tile.scala:8:7, :302:37, :359:36, :364:47
    if (s2_thresh_valid & s2_thresh_bias_added_5 >= io_v_t)	// src/main/scala/tile.scala:301:35, :302:37, :306:34, :360:26, :361:45, :363:46
      s3_thresh_aeq_out_data_5 <= {s3_thresh_blk_counter, 5'hB};	// src/main/scala/tile.scala:8:7, :302:37, :359:36, :364:47
    if (s2_thresh_valid & s2_thresh_bias_added_6 >= io_v_t)	// src/main/scala/tile.scala:301:35, :302:37, :306:34, :360:26, :361:45, :363:46
      s3_thresh_aeq_out_data_6 <= {s3_thresh_blk_counter, 5'hD};	// src/main/scala/tile.scala:8:7, :302:37, :359:36, :364:47
    if (s2_thresh_valid & s2_thresh_bias_added_7 >= io_v_t)	// src/main/scala/tile.scala:301:35, :302:37, :306:34, :360:26, :361:45, :363:46
      s3_thresh_aeq_out_data_7 <= {s3_thresh_blk_counter, 5'hF};	// src/main/scala/tile.scala:8:7, :302:37, :359:36, :364:47
    if (s2_thresh_valid & s2_thresh_bias_added_8 >= io_v_t)	// src/main/scala/tile.scala:301:35, :302:37, :306:34, :360:26, :361:45, :363:46
      s3_thresh_aeq_out_data_8 <= {s3_thresh_blk_counter, 5'h11};	// src/main/scala/tile.scala:8:7, :302:37, :359:36, :364:47
    if (s2_thresh_valid)	// src/main/scala/tile.scala:306:34
      s3_thresh_blk_counter <= s3_thresh_blk_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :359:36, :374:56
    if (s3_thresh_valid) begin	// src/main/scala/tile.scala:307:34
      if (s3_thresh_aeq_out_data_8[0])	// src/main/scala/tile.scala:302:37, :384:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :379:36, :387:64
      else if (s3_thresh_aeq_out_data_7[0])	// src/main/scala/tile.scala:302:37, :384:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :379:36, :387:64
      else if (s3_thresh_aeq_out_data_6[0])	// src/main/scala/tile.scala:302:37, :384:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :379:36, :387:64
      else if (s3_thresh_aeq_out_data_5[0])	// src/main/scala/tile.scala:302:37, :384:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :379:36, :387:64
      else if (s3_thresh_aeq_out_data_4[0])	// src/main/scala/tile.scala:302:37, :384:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :379:36, :387:64
      else if (s3_thresh_aeq_out_data_3[0])	// src/main/scala/tile.scala:302:37, :384:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :379:36, :387:64
      else if (s3_thresh_aeq_out_data_2[0])	// src/main/scala/tile.scala:302:37, :384:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :379:36, :387:64
      else if (s3_thresh_aeq_out_data_1[0])	// src/main/scala/tile.scala:302:37, :384:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :379:36, :387:64
      else if (s3_thresh_aeq_out_data_0[0])	// src/main/scala/tile.scala:302:37, :384:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :379:36, :387:64
    end
    if (reset) begin	// src/main/scala/tile.scala:8:7
      s1_valid <= 1'h0;	// src/main/scala/tile.scala:70:20, :117:27
      s2_valid <= 1'h0;	// src/main/scala/tile.scala:70:20, :118:27
      s3_valid <= 1'h0;	// src/main/scala/tile.scala:70:20, :119:27
      conv_done_reg <= 1'h0;	// src/main/scala/tile.scala:70:20, :124:32
      thresh_done_reg <= 1'h0;	// src/main/scala/tile.scala:70:20, :125:34
      read_counter <= 8'h0;	// src/main/scala/tile.scala:78:38, :135:31
      i <= 1'h0;	// src/main/scala/tile.scala:70:20, :150:28
      read_mem_counter <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/tile.scala:8:7
      s1_thresh_valid <= 1'h0;	// src/main/scala/tile.scala:70:20, :305:34
      s2_thresh_valid <= 1'h0;	// src/main/scala/tile.scala:70:20, :306:34
      s3_thresh_valid <= 1'h0;	// src/main/scala/tile.scala:70:20, :307:34
    end
    else begin	// src/main/scala/tile.scala:8:7
      automatic logic _GEN_16;	// src/main/scala/tile.scala:165:30
      _GEN_16 = io_rd_data_aeq_i[10] | ~(io_rd_data_aeq_i[0]);	// src/main/scala/tile.scala:142:{25,44}, :165:{30,33}
      if (io_rd_en_aeq_i_0) begin	// src/main/scala/tile.scala:136:36
        s1_valid <= _GEN_12;	// src/main/scala/tile.scala:117:27, :142:29
        if (_GEN_16)	// src/main/scala/tile.scala:165:30
          read_counter <= 8'h0;	// src/main/scala/tile.scala:78:38, :135:31
        else	// src/main/scala/tile.scala:165:30
          read_counter <= read_counter + 8'h1;	// src/main/scala/tile.scala:135:31, :164:38
      end
      s2_valid <= _GEN | s2_valid;	// src/main/scala/tile.scala:118:27, :172:{34,48}, :220:18
      s3_valid <= _GEN_15 | s3_valid;	// src/main/scala/tile.scala:119:27, :224:{19,34}, :228:18
      conv_done_reg <= io_rd_en_aeq_i_0 & _GEN_16 | conv_done_reg;	// src/main/scala/tile.scala:124:32, :136:{36,55}, :165:{30,50}, :167:27
      thresh_done_reg <= wrap;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/tile.scala:125:34
      i <= i - 1'h1;	// src/main/scala/tile.scala:150:28, :159:28
      if (_GEN_5) begin	// src/main/scala/tile.scala:287:57
        if (wrap_wrap)	// src/main/scala/chisel3/util/Counter.scala:73:24
          read_mem_counter <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/tile.scala:8:7
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          read_mem_counter <= read_mem_counter + 5'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24, src/main/scala/tile.scala:8:7
      end
      s1_thresh_valid <= _GEN_6 | s1_thresh_valid;	// src/main/scala/tile.scala:305:34, :311:{23,32}, :342:25
      s2_thresh_valid <= s1_thresh_valid | s2_thresh_valid;	// src/main/scala/tile.scala:305:34, :306:34, :346:26, :355:25
      s3_thresh_valid <= s2_thresh_valid | s3_thresh_valid;	// src/main/scala/tile.scala:306:34, :307:34, :360:26, :375:25
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/tile.scala:8:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/tile.scala:8:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/tile.scala:8:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/tile.scala:8:7
      automatic logic [31:0] _RANDOM[0:19];	// src/main/scala/tile.scala:8:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/tile.scala:8:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/tile.scala:8:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/tile.scala:8:7
        for (logic [4:0] i_0 = 5'h0; i_0 < 5'h14; i_0 += 5'h1) begin
          _RANDOM[i_0] = `RANDOM;	// src/main/scala/tile.scala:8:7
        end	// src/main/scala/tile.scala:8:7
        s1_addr_calc_0 = _RANDOM[5'h2][16:8];	// src/main/scala/tile.scala:8:7, :113:27
        s1_addr_calc_1 = _RANDOM[5'h2][25:17];	// src/main/scala/tile.scala:8:7, :113:27
        s2_mempot_rd_0 = {_RANDOM[5'h4][31:25], _RANDOM[5'h5][1:0]};	// src/main/scala/tile.scala:8:7, :114:27
        s2_mempot_rd_1 = _RANDOM[5'h5][10:2];	// src/main/scala/tile.scala:8:7, :114:27
        s2_mempot_rd_2 = _RANDOM[5'h5][19:11];	// src/main/scala/tile.scala:8:7, :114:27
        s2_mempot_rd_3 = _RANDOM[5'h5][28:20];	// src/main/scala/tile.scala:8:7, :114:27
        s2_mempot_rd_4 = {_RANDOM[5'h5][31:29], _RANDOM[5'h6][5:0]};	// src/main/scala/tile.scala:8:7, :114:27
        s2_mempot_rd_5 = _RANDOM[5'h6][14:6];	// src/main/scala/tile.scala:8:7, :114:27
        s2_mempot_rd_6 = _RANDOM[5'h6][23:15];	// src/main/scala/tile.scala:8:7, :114:27
        s2_mempot_rd_7 = {_RANDOM[5'h6][31:24], _RANDOM[5'h7][0]};	// src/main/scala/tile.scala:8:7, :114:27
        s2_mempot_rd_8 = _RANDOM[5'h7][9:1];	// src/main/scala/tile.scala:8:7, :114:27
        s3_conv_0 = _RANDOM[5'h7][18:10];	// src/main/scala/tile.scala:8:7, :114:27, :115:22
        s3_conv_1 = _RANDOM[5'h7][27:19];	// src/main/scala/tile.scala:8:7, :114:27, :115:22
        s3_conv_2 = {_RANDOM[5'h7][31:28], _RANDOM[5'h8][4:0]};	// src/main/scala/tile.scala:8:7, :114:27, :115:22
        s3_conv_3 = _RANDOM[5'h8][13:5];	// src/main/scala/tile.scala:8:7, :115:22
        s3_conv_4 = _RANDOM[5'h8][22:14];	// src/main/scala/tile.scala:8:7, :115:22
        s3_conv_5 = _RANDOM[5'h8][31:23];	// src/main/scala/tile.scala:8:7, :115:22
        s3_conv_6 = _RANDOM[5'h9][8:0];	// src/main/scala/tile.scala:8:7, :115:22
        s3_conv_7 = _RANDOM[5'h9][17:9];	// src/main/scala/tile.scala:8:7, :115:22
        s3_conv_8 = _RANDOM[5'h9][26:18];	// src/main/scala/tile.scala:8:7, :115:22
        s1_valid = _RANDOM[5'h9][27];	// src/main/scala/tile.scala:8:7, :115:22, :117:27
        s2_valid = _RANDOM[5'h9][28];	// src/main/scala/tile.scala:8:7, :115:22, :118:27
        s3_valid = _RANDOM[5'h9][29];	// src/main/scala/tile.scala:8:7, :115:22, :119:27
        conv_done_reg = _RANDOM[5'h9][31];	// src/main/scala/tile.scala:8:7, :115:22, :124:32
        thresh_done_reg = _RANDOM[5'hA][0];	// src/main/scala/tile.scala:8:7, :125:34
        read_counter = _RANDOM[5'hA][8:1];	// src/main/scala/tile.scala:8:7, :125:34, :135:31
        i = _RANDOM[5'hA][9];	// src/main/scala/tile.scala:8:7, :125:34, :150:28
        read_mem_counter = _RANDOM[5'hA][14:10];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/tile.scala:8:7, :125:34
        thresh_blk_counter = _RANDOM[5'hA][19:15];	// src/main/scala/tile.scala:8:7, :125:34, :288:33
        s1_thresh_main_mem_rd_0 = _RANDOM[5'hA][28:20];	// src/main/scala/tile.scala:8:7, :125:34, :299:36
        s1_thresh_main_mem_rd_1 = {_RANDOM[5'hA][31:29], _RANDOM[5'hB][5:0]};	// src/main/scala/tile.scala:8:7, :125:34, :299:36
        s1_thresh_main_mem_rd_2 = _RANDOM[5'hB][14:6];	// src/main/scala/tile.scala:8:7, :299:36
        s1_thresh_main_mem_rd_3 = _RANDOM[5'hB][23:15];	// src/main/scala/tile.scala:8:7, :299:36
        s1_thresh_main_mem_rd_4 = {_RANDOM[5'hB][31:24], _RANDOM[5'hC][0]};	// src/main/scala/tile.scala:8:7, :299:36
        s1_thresh_main_mem_rd_5 = _RANDOM[5'hC][9:1];	// src/main/scala/tile.scala:8:7, :299:36
        s1_thresh_main_mem_rd_6 = _RANDOM[5'hC][18:10];	// src/main/scala/tile.scala:8:7, :299:36
        s1_thresh_main_mem_rd_7 = _RANDOM[5'hC][27:19];	// src/main/scala/tile.scala:8:7, :299:36
        s1_thresh_main_mem_rd_8 = {_RANDOM[5'hC][31:28], _RANDOM[5'hD][4:0]};	// src/main/scala/tile.scala:8:7, :299:36
        s1_thresh_local_mem_rd_0 = _RANDOM[5'hD][13:5];	// src/main/scala/tile.scala:8:7, :299:36, :300:37
        s1_thresh_local_mem_rd_1 = _RANDOM[5'hD][22:14];	// src/main/scala/tile.scala:8:7, :299:36, :300:37
        s1_thresh_local_mem_rd_2 = _RANDOM[5'hD][31:23];	// src/main/scala/tile.scala:8:7, :299:36, :300:37
        s2_thresh_bias_added_0 = _RANDOM[5'hE][8:0];	// src/main/scala/tile.scala:8:7, :301:35
        s2_thresh_bias_added_1 = _RANDOM[5'hE][17:9];	// src/main/scala/tile.scala:8:7, :301:35
        s2_thresh_bias_added_2 = _RANDOM[5'hE][26:18];	// src/main/scala/tile.scala:8:7, :301:35
        s2_thresh_bias_added_3 = {_RANDOM[5'hE][31:27], _RANDOM[5'hF][3:0]};	// src/main/scala/tile.scala:8:7, :301:35
        s2_thresh_bias_added_4 = _RANDOM[5'hF][12:4];	// src/main/scala/tile.scala:8:7, :301:35
        s2_thresh_bias_added_5 = _RANDOM[5'hF][21:13];	// src/main/scala/tile.scala:8:7, :301:35
        s2_thresh_bias_added_6 = _RANDOM[5'hF][30:22];	// src/main/scala/tile.scala:8:7, :301:35
        s2_thresh_bias_added_7 = {_RANDOM[5'hF][31], _RANDOM[5'h10][7:0]};	// src/main/scala/tile.scala:8:7, :301:35
        s2_thresh_bias_added_8 = _RANDOM[5'h10][16:8];	// src/main/scala/tile.scala:8:7, :301:35
        s3_thresh_aeq_out_data_0 = _RANDOM[5'h10][26:17];	// src/main/scala/tile.scala:8:7, :301:35, :302:37
        s3_thresh_aeq_out_data_1 = {_RANDOM[5'h10][31:27], _RANDOM[5'h11][4:0]};	// src/main/scala/tile.scala:8:7, :301:35, :302:37
        s3_thresh_aeq_out_data_2 = _RANDOM[5'h11][14:5];	// src/main/scala/tile.scala:8:7, :302:37
        s3_thresh_aeq_out_data_3 = _RANDOM[5'h11][24:15];	// src/main/scala/tile.scala:8:7, :302:37
        s3_thresh_aeq_out_data_4 = {_RANDOM[5'h11][31:25], _RANDOM[5'h12][2:0]};	// src/main/scala/tile.scala:8:7, :302:37
        s3_thresh_aeq_out_data_5 = _RANDOM[5'h12][12:3];	// src/main/scala/tile.scala:8:7, :302:37
        s3_thresh_aeq_out_data_6 = _RANDOM[5'h12][22:13];	// src/main/scala/tile.scala:8:7, :302:37
        s3_thresh_aeq_out_data_7 = {_RANDOM[5'h12][31:23], _RANDOM[5'h13][0]};	// src/main/scala/tile.scala:8:7, :302:37
        s3_thresh_aeq_out_data_8 = _RANDOM[5'h13][10:1];	// src/main/scala/tile.scala:8:7, :302:37
        s1_thresh_valid = _RANDOM[5'h13][11];	// src/main/scala/tile.scala:8:7, :302:37, :305:34
        s2_thresh_valid = _RANDOM[5'h13][12];	// src/main/scala/tile.scala:8:7, :302:37, :306:34
        s3_thresh_valid = _RANDOM[5'h13][13];	// src/main/scala/tile.scala:8:7, :302:37, :307:34
        s3_thresh_blk_counter = _RANDOM[5'h13][18:14];	// src/main/scala/tile.scala:8:7, :302:37, :359:36
        s4_thresh_aeq_counter = _RANDOM[5'h13][23:19];	// src/main/scala/tile.scala:8:7, :302:37, :379:36
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/tile.scala:8:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/tile.scala:8:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rd_en_aeq_i = io_rd_en_aeq_i_0;	// src/main/scala/tile.scala:8:7, :136:36
  assign io_rd_addr_aeq_i = io_rd_en_aeq_i_0 ? {1'h0, read_counter} : 9'h0;	// src/main/scala/tile.scala:8:7, :70:20, :71:22, :79:38, :135:31, :136:{36,55}, :138:26
  assign io_wr_en_aeq_o = s3_thresh_valid;	// src/main/scala/tile.scala:8:7, :307:34
  assign io_wr_addr_aeq_o =
    s3_thresh_valid
    & (s3_thresh_aeq_out_data_8[0] | s3_thresh_aeq_out_data_7[0]
       | s3_thresh_aeq_out_data_6[0] | s3_thresh_aeq_out_data_5[0]
       | s3_thresh_aeq_out_data_4[0] | s3_thresh_aeq_out_data_3[0]
       | s3_thresh_aeq_out_data_2[0] | s3_thresh_aeq_out_data_1[0]
       | s3_thresh_aeq_out_data_0[0])
      ? {4'h0, s4_thresh_aeq_counter}
      : 9'h0;	// src/main/scala/tile.scala:8:7, :74:22, :79:38, :148:25, :302:37, :307:34, :379:36, :380:26, :384:{43,47}, :385:34
  assign io_wr_data_aeq_o =
    s3_thresh_valid
      ? (s3_thresh_aeq_out_data_8[0]
           ? {1'h0, s3_thresh_aeq_out_data_8}
           : s3_thresh_aeq_out_data_7[0]
               ? {1'h0, s3_thresh_aeq_out_data_7}
               : s3_thresh_aeq_out_data_6[0]
                   ? {1'h0, s3_thresh_aeq_out_data_6}
                   : s3_thresh_aeq_out_data_5[0]
                       ? {1'h0, s3_thresh_aeq_out_data_5}
                       : s3_thresh_aeq_out_data_4[0]
                           ? {1'h0, s3_thresh_aeq_out_data_4}
                           : s3_thresh_aeq_out_data_3[0]
                               ? {1'h0, s3_thresh_aeq_out_data_3}
                               : s3_thresh_aeq_out_data_2[0]
                                   ? {1'h0, s3_thresh_aeq_out_data_2}
                                   : s3_thresh_aeq_out_data_1[0]
                                       ? {1'h0, s3_thresh_aeq_out_data_1}
                                       : s3_thresh_aeq_out_data_0[0]
                                           ? {1'h0, s3_thresh_aeq_out_data_0}
                                           : 11'h0)
      : 11'h0;	// src/main/scala/tile.scala:8:7, :70:20, :75:22, :302:37, :307:34, :380:26, :384:{43,47}, :386:34
  assign io_wr_en_main_mempot_0 = io_wr_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :77:26, :233:34, :235:92
  assign io_wr_en_main_mempot_1 = io_wr_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :77:26, :233:34, :235:92
  assign io_wr_en_main_mempot_2 = io_wr_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :77:26, :233:34, :235:92
  assign io_wr_en_main_mempot_3 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :233:19
  assign io_wr_en_main_mempot_4 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :233:19
  assign io_wr_en_main_mempot_5 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :233:19
  assign io_wr_en_main_mempot_6 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :233:19
  assign io_wr_en_main_mempot_7 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :233:19
  assign io_wr_en_main_mempot_8 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :233:19
  assign io_wr_addr_main_mempot_0 = _GEN_4 ? 8'h0 : s1_addr_calc_0[7:0];	// src/main/scala/tile.scala:8:7, :78:{28,38}, :113:27, :178:43, :233:34, :235:92
  assign io_wr_addr_main_mempot_1 = _GEN_4 ? 8'h0 : s1_addr_calc_1[7:0];	// src/main/scala/tile.scala:8:7, :78:{28,38}, :113:27, :178:43, :233:34, :235:92
  assign io_wr_addr_main_mempot_2 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_addr_main_mempot_3 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_addr_main_mempot_4 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_addr_main_mempot_5 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_addr_main_mempot_6 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_addr_main_mempot_7 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_addr_main_mempot_8 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_data_main_mempot_0 = _GEN_4 ? 9'h0 : s3_conv_0;	// src/main/scala/tile.scala:8:7, :78:28, :79:{28,38}, :115:22, :233:34, :235:92
  assign io_wr_data_main_mempot_1 = _GEN_4 ? 9'h0 : s3_conv_1;	// src/main/scala/tile.scala:8:7, :78:28, :79:{28,38}, :115:22, :233:34, :235:92
  assign io_wr_data_main_mempot_2 = _GEN_4 ? 9'h0 : s3_conv_2;	// src/main/scala/tile.scala:8:7, :78:28, :79:{28,38}, :115:22, :233:34, :235:92
  assign io_wr_data_main_mempot_3 = io_wr_en_main_mempot_5_0 ? s3_conv_3 : 9'h0;	// src/main/scala/tile.scala:8:7, :79:{28,38}, :115:22, :233:{19,34}, :235:92
  assign io_wr_data_main_mempot_4 = io_wr_en_main_mempot_5_0 ? s3_conv_4 : 9'h0;	// src/main/scala/tile.scala:8:7, :79:{28,38}, :115:22, :233:{19,34}, :235:92
  assign io_wr_data_main_mempot_5 = io_wr_en_main_mempot_5_0 ? s3_conv_5 : 9'h0;	// src/main/scala/tile.scala:8:7, :79:{28,38}, :115:22, :233:{19,34}, :235:92
  assign io_wr_data_main_mempot_6 = io_wr_en_main_mempot_5_0 ? s3_conv_6 : 9'h0;	// src/main/scala/tile.scala:8:7, :79:{28,38}, :115:22, :233:{19,34}, :235:92
  assign io_wr_data_main_mempot_7 = io_wr_en_main_mempot_5_0 ? s3_conv_7 : 9'h0;	// src/main/scala/tile.scala:8:7, :79:{28,38}, :115:22, :233:{19,34}, :235:92
  assign io_wr_data_main_mempot_8 = io_wr_en_main_mempot_5_0 ? s3_conv_8 : 9'h0;	// src/main/scala/tile.scala:8:7, :79:{28,38}, :115:22, :233:{19,34}, :235:92
  assign io_rd_en_main_mempot_0 = io_rd_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :172:48, :311:32, :312:39, :321:41, :326:47, :335:41
  assign io_rd_en_main_mempot_1 = io_rd_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :172:48, :311:32, :312:39, :321:41, :326:47, :335:41
  assign io_rd_en_main_mempot_2 = io_rd_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :172:48, :311:32, :312:39, :321:41, :326:47, :335:41
  assign io_rd_en_main_mempot_3 = io_rd_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :172:48, :311:32, :312:39, :321:41, :326:47, :335:41
  assign io_rd_en_main_mempot_4 = io_rd_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :172:48, :311:32, :312:39, :321:41, :326:47, :335:41
  assign io_rd_en_main_mempot_5 = io_rd_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :172:48, :311:32, :312:39, :321:41, :326:47, :335:41
  assign io_rd_en_main_mempot_6 = io_rd_en_main_mempot_8_0;	// src/main/scala/tile.scala:8:7, :172:48, :311:32, :312:39, :321:41, :326:47, :335:41
  assign io_rd_en_main_mempot_7 = io_rd_en_main_mempot_8_0;	// src/main/scala/tile.scala:8:7, :172:48, :311:32, :312:39, :321:41, :326:47, :335:41
  assign io_rd_en_main_mempot_8 = io_rd_en_main_mempot_8_0;	// src/main/scala/tile.scala:8:7, :172:48, :311:32, :312:39, :321:41, :326:47, :335:41
  assign io_rd_addr_main_mempot_0 =
    _GEN_11 ? _GEN_8 : _GEN_2 ? 8'h0 : s1_addr_calc_0[7:0];	// src/main/scala/tile.scala:8:7, :78:38, :82:28, :113:27, :172:48, :174:92, :178:43, :311:32, :312:39, :316:36
  assign io_rd_addr_main_mempot_1 =
    _GEN_11 ? _GEN_8 : _GEN_2 ? 8'h0 : s1_addr_calc_1[7:0];	// src/main/scala/tile.scala:8:7, :78:38, :82:28, :113:27, :172:48, :174:92, :178:43, :311:32, :312:39, :316:36
  assign io_rd_addr_main_mempot_2 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :172:48, :311:32, :312:39, :316:36
  assign io_rd_addr_main_mempot_3 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :172:48, :311:32, :312:39, :316:36
  assign io_rd_addr_main_mempot_4 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :172:48, :311:32, :312:39, :316:36
  assign io_rd_addr_main_mempot_5 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :172:48, :311:32, :312:39, :316:36
  assign io_rd_addr_main_mempot_6 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :172:48, :311:32, :312:39, :316:36
  assign io_rd_addr_main_mempot_7 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :172:48, :311:32, :312:39, :316:36
  assign io_rd_addr_main_mempot_8 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :172:48, :311:32, :312:39, :316:36
  assign io_wr_en_L2_N_0 = 1'h0;	// src/main/scala/tile.scala:8:7, :70:20
  assign io_wr_en_L2_N_1 = 1'h0;	// src/main/scala/tile.scala:8:7, :70:20
  assign io_wr_en_L2_N_2 = 1'h0;	// src/main/scala/tile.scala:8:7, :70:20
  assign io_wr_addr_L2_N_0 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_addr_L2_N_1 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_addr_L2_N_2 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_data_L2_N_0 = 9'h0;	// src/main/scala/tile.scala:8:7, :79:38
  assign io_wr_data_L2_N_1 = 9'h0;	// src/main/scala/tile.scala:8:7, :79:38
  assign io_wr_data_L2_N_2 = 9'h0;	// src/main/scala/tile.scala:8:7, :79:38
  assign io_rd_en_L2_N_0 = io_rd_en_L2_N_2_0;	// src/main/scala/tile.scala:8:7, :87:19, :172:48, :174:92
  assign io_rd_en_L2_N_1 = io_rd_en_L2_N_2_0;	// src/main/scala/tile.scala:8:7, :87:19, :172:48, :174:92
  assign io_rd_en_L2_N_2 = io_rd_en_L2_N_2_0;	// src/main/scala/tile.scala:8:7, :87:19, :172:48, :174:92
  assign io_rd_addr_L2_N_0 = _GEN_1 ? s1_addr_calc_0[7:0] : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :88:21, :113:27, :172:48, :174:92, :178:43
  assign io_rd_addr_L2_N_1 = _GEN_1 ? s1_addr_calc_1[7:0] : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :88:21, :113:27, :172:48, :174:92, :178:43
  assign io_rd_addr_L2_N_2 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_en_L2_S_0 = io_wr_en_L2_S_2_0;	// src/main/scala/tile.scala:8:7, :90:19, :233:34, :235:92
  assign io_wr_en_L2_S_1 = io_wr_en_L2_S_2_0;	// src/main/scala/tile.scala:8:7, :90:19, :233:34, :235:92
  assign io_wr_en_L2_S_2 = io_wr_en_L2_S_2_0;	// src/main/scala/tile.scala:8:7, :90:19, :233:34, :235:92
  assign io_wr_addr_L2_S_0 = _GEN_3 ? s1_addr_calc_0[7:0] : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :91:21, :113:27, :178:43, :233:34, :235:92
  assign io_wr_addr_L2_S_1 = _GEN_3 ? s1_addr_calc_1[7:0] : 8'h0;	// src/main/scala/tile.scala:8:7, :78:38, :91:21, :113:27, :178:43, :233:34, :235:92
  assign io_wr_addr_L2_S_2 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_wr_data_L2_S_0 = _GEN_3 ? s3_conv_0 : 9'h0;	// src/main/scala/tile.scala:8:7, :79:38, :91:21, :92:21, :115:22, :233:34, :235:92
  assign io_wr_data_L2_S_1 = _GEN_3 ? s3_conv_1 : 9'h0;	// src/main/scala/tile.scala:8:7, :79:38, :91:21, :92:21, :115:22, :233:34, :235:92
  assign io_wr_data_L2_S_2 = _GEN_3 ? s3_conv_2 : 9'h0;	// src/main/scala/tile.scala:8:7, :79:38, :91:21, :92:21, :115:22, :233:34, :235:92
  assign io_rd_en_L2_S_0 = 1'h0;	// src/main/scala/tile.scala:8:7, :70:20
  assign io_rd_en_L2_S_1 = 1'h0;	// src/main/scala/tile.scala:8:7, :70:20
  assign io_rd_en_L2_S_2 = 1'h0;	// src/main/scala/tile.scala:8:7, :70:20
  assign io_rd_addr_L2_S_0 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_rd_addr_L2_S_1 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_rd_addr_L2_S_2 = 8'h0;	// src/main/scala/tile.scala:8:7, :78:38
  assign io_rd_en_L1_N = _GEN_6 & _GEN_7;	// src/main/scala/tile.scala:8:7, :96:19, :311:{23,32}, :312:{33,39}
  assign io_rd_addr_L1_N_0 = io_rd_addr_L1_N_2_0;	// src/main/scala/tile.scala:8:7, :97:21, :311:32, :312:39, :316:36
  assign io_rd_addr_L1_N_1 = io_rd_addr_L1_N_2_0;	// src/main/scala/tile.scala:8:7, :97:21, :311:32, :312:39, :316:36
  assign io_rd_addr_L1_N_2 = io_rd_addr_L1_N_2_0;	// src/main/scala/tile.scala:8:7, :97:21, :311:32, :312:39, :316:36
  assign io_rd_en_L1_S = _GEN_6 & ~_GEN_7 & _GEN_9;	// src/main/scala/tile.scala:8:7, :99:19, :311:{23,32}, :312:{33,39}, :326:{40,47}
  assign io_rd_addr_L1_S_0 = io_rd_addr_L1_S_2_0;	// src/main/scala/tile.scala:8:7, :100:21, :311:32, :312:39
  assign io_rd_addr_L1_S_1 = io_rd_addr_L1_S_2_0;	// src/main/scala/tile.scala:8:7, :100:21, :311:32, :312:39
  assign io_rd_addr_L1_S_2 = io_rd_addr_L1_S_2_0;	// src/main/scala/tile.scala:8:7, :100:21, :311:32, :312:39
  assign io_conv_done = conv_done_reg;	// src/main/scala/tile.scala:8:7, :124:32
  assign io_thresh_done = thresh_done_reg;	// src/main/scala/tile.scala:8:7, :125:34
endmodule

