// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module tile(	// src/main/scala/tile.scala:8:7
  input         clock,	// src/main/scala/tile.scala:8:7
                reset,	// src/main/scala/tile.scala:8:7
  output        io_rd_en_aeq_i,	// src/main/scala/tile.scala:9:16
  output [8:0]  io_rd_addr_aeq_i,	// src/main/scala/tile.scala:9:16
  input  [10:0] io_rd_data_aeq_i,	// src/main/scala/tile.scala:9:16
  output        io_wr_en_aeq_o,	// src/main/scala/tile.scala:9:16
  output [8:0]  io_wr_addr_aeq_o,	// src/main/scala/tile.scala:9:16
  output [10:0] io_wr_data_aeq_o,	// src/main/scala/tile.scala:9:16
  output        io_wr_en_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_wr_en_main_mempot_8,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_wr_addr_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_wr_addr_main_mempot_8,	// src/main/scala/tile.scala:9:16
  output [8:0]  io_wr_data_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_wr_data_main_mempot_8,	// src/main/scala/tile.scala:9:16
  output        io_rd_en_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_rd_en_main_mempot_8,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_rd_addr_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_rd_addr_main_mempot_8,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_rd_data_main_mempot_0,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_1,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_2,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_3,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_4,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_5,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_6,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_7,	// src/main/scala/tile.scala:9:16
                io_rd_data_main_mempot_8,	// src/main/scala/tile.scala:9:16
  output        io_wr_en_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_wr_en_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_wr_en_L2_N_2,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_wr_addr_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_wr_addr_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_wr_addr_L2_N_2,	// src/main/scala/tile.scala:9:16
  output [8:0]  io_wr_data_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_wr_data_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_wr_data_L2_N_2,	// src/main/scala/tile.scala:9:16
  output        io_rd_en_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_rd_en_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_rd_en_L2_N_2,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_rd_addr_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L2_N_2,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_rd_data_L2_N_0,	// src/main/scala/tile.scala:9:16
                io_rd_data_L2_N_1,	// src/main/scala/tile.scala:9:16
                io_rd_data_L2_N_2,	// src/main/scala/tile.scala:9:16
  output        io_wr_en_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_wr_en_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_wr_en_L2_S_2,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_wr_addr_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_wr_addr_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_wr_addr_L2_S_2,	// src/main/scala/tile.scala:9:16
  output [8:0]  io_wr_data_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_wr_data_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_wr_data_L2_S_2,	// src/main/scala/tile.scala:9:16
  output        io_rd_en_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_rd_en_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_rd_en_L2_S_2,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_rd_addr_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L2_S_2,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_rd_data_L2_S_0,	// src/main/scala/tile.scala:9:16
                io_rd_data_L2_S_1,	// src/main/scala/tile.scala:9:16
                io_rd_data_L2_S_2,	// src/main/scala/tile.scala:9:16
  output        io_rd_en_L1_N,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_rd_addr_L1_N_0,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L1_N_1,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L1_N_2,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_rd_data_L1_N_0,	// src/main/scala/tile.scala:9:16
                io_rd_data_L1_N_1,	// src/main/scala/tile.scala:9:16
                io_rd_data_L1_N_2,	// src/main/scala/tile.scala:9:16
  output        io_rd_en_L1_S,	// src/main/scala/tile.scala:9:16
  output [7:0]  io_rd_addr_L1_S_0,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L1_S_1,	// src/main/scala/tile.scala:9:16
                io_rd_addr_L1_S_2,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_rd_data_L1_S_0,	// src/main/scala/tile.scala:9:16
                io_rd_data_L1_S_1,	// src/main/scala/tile.scala:9:16
                io_rd_data_L1_S_2,	// src/main/scala/tile.scala:9:16
  input         io_thresh_en,	// src/main/scala/tile.scala:9:16
                io_conv_en,	// src/main/scala/tile.scala:9:16
  input  [7:0]  io_bias_0,	// src/main/scala/tile.scala:9:16
                io_bias_1,	// src/main/scala/tile.scala:9:16
                io_bias_2,	// src/main/scala/tile.scala:9:16
                io_bias_3,	// src/main/scala/tile.scala:9:16
                io_bias_4,	// src/main/scala/tile.scala:9:16
                io_bias_5,	// src/main/scala/tile.scala:9:16
                io_bias_6,	// src/main/scala/tile.scala:9:16
                io_bias_7,	// src/main/scala/tile.scala:9:16
                io_bias_8,	// src/main/scala/tile.scala:9:16
  input  [8:0]  io_v_t,	// src/main/scala/tile.scala:9:16
  input  [7:0]  io_kernel_0,	// src/main/scala/tile.scala:9:16
                io_kernel_1,	// src/main/scala/tile.scala:9:16
                io_kernel_2,	// src/main/scala/tile.scala:9:16
                io_kernel_3,	// src/main/scala/tile.scala:9:16
                io_kernel_4,	// src/main/scala/tile.scala:9:16
                io_kernel_5,	// src/main/scala/tile.scala:9:16
                io_kernel_6,	// src/main/scala/tile.scala:9:16
                io_kernel_7,	// src/main/scala/tile.scala:9:16
                io_kernel_8,	// src/main/scala/tile.scala:9:16
  output        io_conv_done,	// src/main/scala/tile.scala:9:16
                io_thresh_done	// src/main/scala/tile.scala:9:16
);

  reg  [8:0] s1_addr_calc_0;	// src/main/scala/tile.scala:119:27
  reg  [8:0] s1_addr_calc_1;	// src/main/scala/tile.scala:119:27
  reg  [8:0] s2_mempot_rd_0;	// src/main/scala/tile.scala:120:27
  reg  [8:0] s2_mempot_rd_1;	// src/main/scala/tile.scala:120:27
  reg  [8:0] s2_mempot_rd_2;	// src/main/scala/tile.scala:120:27
  reg  [8:0] s2_mempot_rd_3;	// src/main/scala/tile.scala:120:27
  reg  [8:0] s2_mempot_rd_4;	// src/main/scala/tile.scala:120:27
  reg  [8:0] s2_mempot_rd_5;	// src/main/scala/tile.scala:120:27
  reg  [8:0] s2_mempot_rd_6;	// src/main/scala/tile.scala:120:27
  reg  [8:0] s2_mempot_rd_7;	// src/main/scala/tile.scala:120:27
  reg  [8:0] s2_mempot_rd_8;	// src/main/scala/tile.scala:120:27
  reg  [8:0] s3_conv_0;	// src/main/scala/tile.scala:121:22
  reg  [8:0] s3_conv_1;	// src/main/scala/tile.scala:121:22
  reg  [8:0] s3_conv_2;	// src/main/scala/tile.scala:121:22
  reg  [8:0] s3_conv_3;	// src/main/scala/tile.scala:121:22
  reg  [8:0] s3_conv_4;	// src/main/scala/tile.scala:121:22
  reg  [8:0] s3_conv_5;	// src/main/scala/tile.scala:121:22
  reg  [8:0] s3_conv_6;	// src/main/scala/tile.scala:121:22
  reg  [8:0] s3_conv_7;	// src/main/scala/tile.scala:121:22
  reg  [8:0] s3_conv_8;	// src/main/scala/tile.scala:121:22
  reg        s1_valid;	// src/main/scala/tile.scala:123:27
  reg        s2_valid;	// src/main/scala/tile.scala:124:27
  reg        s3_valid;	// src/main/scala/tile.scala:125:27
  reg        conv_done_reg;	// src/main/scala/tile.scala:130:32
  reg        thresh_done_reg;	// src/main/scala/tile.scala:131:34
  reg  [7:0] read_counter;	// src/main/scala/tile.scala:141:31
  wire       io_rd_en_aeq_i_0 = io_conv_en & ~conv_done_reg;	// src/main/scala/tile.scala:130:32, :142:{36,39}
  reg        i;	// src/main/scala/tile.scala:156:28
  wire       _GEN = s1_valid & io_conv_en;	// src/main/scala/tile.scala:123:27, :178:34
  wire       _GEN_0 = s1_addr_calc_0[8:4] < 5'h9 & s1_addr_calc_0[3:0] < 4'h3;	// src/main/scala/tile.scala:8:7, :119:27, :164:37, :199:{40,46,58,78,85}
  wire       io_rd_en_L2_N_2_0 = _GEN & _GEN_0;	// src/main/scala/tile.scala:93:19, :178:{34,48}, :180:92, :199:58
  wire       _GEN_1 = _GEN & _GEN_0;	// src/main/scala/tile.scala:94:21, :178:{34,48}, :180:92, :199:58
  wire       _GEN_2 = ~_GEN | _GEN_0;	// src/main/scala/tile.scala:88:28, :178:{34,48}, :180:92, :199:58
  wire       io_wr_en_main_mempot_5_0 = s3_valid & io_conv_en;	// src/main/scala/tile.scala:125:27, :239:19
  wire       io_wr_en_L2_S_2_0 = io_wr_en_main_mempot_5_0 & _GEN_0;	// src/main/scala/tile.scala:96:19, :199:58, :239:{19,34}, :241:92
  wire       _GEN_3 = io_wr_en_main_mempot_5_0 & _GEN_0;	// src/main/scala/tile.scala:97:21, :199:58, :239:{19,34}, :241:92
  wire       io_wr_en_main_mempot_2_0 = io_wr_en_main_mempot_5_0 & ~_GEN_0;	// src/main/scala/tile.scala:76:20, :83:26, :87:26, :143:24, :199:{58,98}, :221:41, :239:{19,34}, :241:92
  wire       _GEN_4 = ~io_wr_en_main_mempot_5_0 | _GEN_0;	// src/main/scala/tile.scala:84:28, :199:58, :239:{19,34}, :241:92
  wire       _GEN_5 = io_thresh_en & ~io_conv_en;	// src/main/scala/tile.scala:293:{57,60}
  reg  [4:0] read_mem_counter;	// src/main/scala/chisel3/util/Counter.scala:61:40
  wire       wrap_wrap = read_mem_counter == 5'h11;	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24, src/main/scala/tile.scala:8:7
  wire       wrap = _GEN_5 & wrap_wrap;	// src/main/scala/chisel3/util/Counter.scala:73:24, :117:24, :118:{16,23}, src/main/scala/tile.scala:293:57
  reg  [4:0] thresh_blk_counter;	// src/main/scala/tile.scala:294:33
  reg  [8:0] s1_thresh_main_mem_rd_0;	// src/main/scala/tile.scala:305:36
  reg  [8:0] s1_thresh_main_mem_rd_1;	// src/main/scala/tile.scala:305:36
  reg  [8:0] s1_thresh_main_mem_rd_2;	// src/main/scala/tile.scala:305:36
  reg  [8:0] s1_thresh_main_mem_rd_3;	// src/main/scala/tile.scala:305:36
  reg  [8:0] s1_thresh_main_mem_rd_4;	// src/main/scala/tile.scala:305:36
  reg  [8:0] s1_thresh_main_mem_rd_5;	// src/main/scala/tile.scala:305:36
  reg  [8:0] s1_thresh_main_mem_rd_6;	// src/main/scala/tile.scala:305:36
  reg  [8:0] s1_thresh_main_mem_rd_7;	// src/main/scala/tile.scala:305:36
  reg  [8:0] s1_thresh_main_mem_rd_8;	// src/main/scala/tile.scala:305:36
  reg  [8:0] s1_thresh_local_mem_rd_0;	// src/main/scala/tile.scala:306:37
  reg  [8:0] s1_thresh_local_mem_rd_1;	// src/main/scala/tile.scala:306:37
  reg  [8:0] s1_thresh_local_mem_rd_2;	// src/main/scala/tile.scala:306:37
  reg  [8:0] s2_thresh_bias_added_0;	// src/main/scala/tile.scala:307:35
  reg  [8:0] s2_thresh_bias_added_1;	// src/main/scala/tile.scala:307:35
  reg  [8:0] s2_thresh_bias_added_2;	// src/main/scala/tile.scala:307:35
  reg  [8:0] s2_thresh_bias_added_3;	// src/main/scala/tile.scala:307:35
  reg  [8:0] s2_thresh_bias_added_4;	// src/main/scala/tile.scala:307:35
  reg  [8:0] s2_thresh_bias_added_5;	// src/main/scala/tile.scala:307:35
  reg  [8:0] s2_thresh_bias_added_6;	// src/main/scala/tile.scala:307:35
  reg  [8:0] s2_thresh_bias_added_7;	// src/main/scala/tile.scala:307:35
  reg  [8:0] s2_thresh_bias_added_8;	// src/main/scala/tile.scala:307:35
  reg  [9:0] s3_thresh_aeq_out_data_0;	// src/main/scala/tile.scala:308:37
  reg  [9:0] s3_thresh_aeq_out_data_1;	// src/main/scala/tile.scala:308:37
  reg  [9:0] s3_thresh_aeq_out_data_2;	// src/main/scala/tile.scala:308:37
  reg  [9:0] s3_thresh_aeq_out_data_3;	// src/main/scala/tile.scala:308:37
  reg  [9:0] s3_thresh_aeq_out_data_4;	// src/main/scala/tile.scala:308:37
  reg  [9:0] s3_thresh_aeq_out_data_5;	// src/main/scala/tile.scala:308:37
  reg  [9:0] s3_thresh_aeq_out_data_6;	// src/main/scala/tile.scala:308:37
  reg  [9:0] s3_thresh_aeq_out_data_7;	// src/main/scala/tile.scala:308:37
  reg  [9:0] s3_thresh_aeq_out_data_8;	// src/main/scala/tile.scala:308:37
  reg        s1_thresh_valid;	// src/main/scala/tile.scala:311:34
  reg        s2_thresh_valid;	// src/main/scala/tile.scala:312:34
  reg        s3_thresh_valid;	// src/main/scala/tile.scala:313:34
  wire       _GEN_6 = io_thresh_en & ~wrap;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/tile.scala:317:{23,26}
  wire       _GEN_7 = thresh_blk_counter < 5'h9;	// src/main/scala/tile.scala:8:7, :294:33, :318:33
  wire [7:0] _GEN_8 = {3'h0, thresh_blk_counter};	// src/main/scala/tile.scala:154:42, :294:33, :322:36
  wire [7:0] io_rd_addr_L1_N_2_0 = _GEN_6 & _GEN_7 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:84:38, :103:21, :317:{23,32}, :318:{33,39}, :322:36
  wire       _GEN_9 = thresh_blk_counter > 5'h8;	// src/main/scala/tile.scala:8:7, :294:33, :332:40
  wire [7:0] io_rd_addr_L1_S_2_0 = ~_GEN_6 | _GEN_7 | ~_GEN_9 ? 8'h0 : _GEN_8;	// src/main/scala/tile.scala:84:38, :106:21, :317:{23,32}, :318:{33,39}, :322:36, :332:{40,47}
  wire       _GEN_10 = _GEN_6 & (_GEN_7 | _GEN_9);	// src/main/scala/tile.scala:178:48, :317:{23,32}, :318:{33,39}, :327:41, :332:{40,47}, :341:41
  wire       io_rd_en_main_mempot_2_0 = _GEN_10 | _GEN & ~_GEN_0;	// src/main/scala/tile.scala:76:20, :87:26, :143:24, :178:{34,48}, :180:92, :199:{58,98}, :221:41, :317:32, :318:39, :327:41, :332:47, :341:41
  wire       _GEN_11 = _GEN_6 & (_GEN_7 | _GEN_9);	// src/main/scala/tile.scala:178:48, :317:{23,32}, :318:{33,39}, :328:43, :332:{40,47}
  wire       io_rd_en_main_mempot_5_0 = _GEN_10 | _GEN;	// src/main/scala/tile.scala:178:{34,48}, :317:32, :318:39, :327:41, :332:47, :341:41
  wire       io_rd_en_main_mempot_8_0 = _GEN_10 | _GEN;	// src/main/scala/tile.scala:178:{34,48}, :317:32, :318:39, :327:41, :332:47, :341:41
  reg  [4:0] s3_thresh_blk_counter;	// src/main/scala/tile.scala:365:36
  reg  [4:0] s4_thresh_aeq_counter;	// src/main/scala/tile.scala:385:36
  wire       io_wr_en_aeq_o_0 = s3_thresh_valid & io_thresh_en;	// src/main/scala/tile.scala:313:34, :386:26
  always @(posedge clock) begin	// src/main/scala/tile.scala:8:7
    automatic logic       _GEN_12;	// src/main/scala/tile.scala:148:29
    automatic logic [3:0] _m_T_2 = io_rd_data_aeq_i[4:1] % 4'h3;	// src/main/scala/tile.scala:150:37, :152:52, :164:37
    automatic logic [6:0] _mk_T_26 =
      {2'h0, io_rd_data_aeq_i[9:5] / 5'h9} * 7'h3 + {5'h0, _m_T_2[1:0]} + 7'h1;	// src/main/scala/tile.scala:8:7, :149:37, :152:{25,35,42,52}, :159:37
    automatic logic [4:0] _n_T = io_rd_data_aeq_i[9:5] % 5'h9;	// src/main/scala/tile.scala:8:7, :149:37, :154:35
    automatic logic [5:0] _nl_T_26 =
      {2'h0, _n_T[3:0]} * 6'h3 + {2'h0, io_rd_data_aeq_i[4:1] / 4'h3} + 6'h1;	// src/main/scala/tile.scala:150:37, :152:25, :154:{25,35,42,52}, :160:38, :164:37
    automatic logic [5:0] _col_out_T_34 = _nl_T_26 % 6'h3;	// src/main/scala/tile.scala:154:25, :160:38, :163:56
    automatic logic [6:0] _col_out_T_32 = _mk_T_26 % 7'h3;	// src/main/scala/tile.scala:152:25, :159:37, :163:40
    automatic logic [5:0] _blk_out_T_34 = _nl_T_26 / 6'h3;	// src/main/scala/tile.scala:154:25, :160:38, :162:58
    automatic logic [6:0] _blk_out_T_32 = _mk_T_26 / 7'h3;	// src/main/scala/tile.scala:152:25, :159:37, :162:46
    automatic logic [8:0] _GEN_13;	// src/main/scala/tile.scala:164:37
    automatic logic       _GEN_14;	// src/main/scala/tile.scala:119:27, :142:55, :148:49, :164:37
    automatic logic       _GEN_15;	// src/main/scala/tile.scala:230:19
    automatic logic       _GEN_16;	// src/main/scala/tile.scala:352:26
    automatic logic       _GEN_17;	// src/main/scala/tile.scala:366:26
    _GEN_12 = io_rd_data_aeq_i[0] & ~(io_rd_data_aeq_i[10]);	// src/main/scala/tile.scala:148:{25,29,32,44}
    _GEN_13 =
      {1'h0,
       _blk_out_T_32[3:0] * 4'h9 + _blk_out_T_34[3:0],
       {2'h0, _col_out_T_32[1:0]} * 4'h3 + {2'h0, _col_out_T_34[1:0]}};	// src/main/scala/tile.scala:76:20, :152:25, :162:{40,46,53,58}, :163:{40,46,51,56}, :164:37
    _GEN_14 = io_rd_en_aeq_i_0 & _GEN_12;	// src/main/scala/tile.scala:119:27, :142:{36,55}, :148:{29,49}, :164:37
    _GEN_15 = s2_valid & io_conv_en;	// src/main/scala/tile.scala:124:27, :230:19
    _GEN_16 = s1_thresh_valid & io_thresh_en;	// src/main/scala/tile.scala:311:34, :352:26
    _GEN_17 = s2_thresh_valid & io_thresh_en;	// src/main/scala/tile.scala:312:34, :366:26
    if (~_GEN_14 | i) begin	// src/main/scala/tile.scala:119:27, :142:55, :148:49, :156:28, :164:37
    end
    else	// src/main/scala/tile.scala:119:27, :142:55, :148:49, :164:37
      s1_addr_calc_0 <= _GEN_13;	// src/main/scala/tile.scala:119:27, :164:37
    if (_GEN_14 & i)	// src/main/scala/tile.scala:119:27, :142:55, :148:49, :156:28, :164:37
      s1_addr_calc_1 <= _GEN_13;	// src/main/scala/tile.scala:119:27, :164:37
    if (_GEN) begin	// src/main/scala/tile.scala:178:34
      s2_mempot_rd_0 <= _GEN_0 ? io_rd_data_L2_N_0 : io_rd_data_main_mempot_0;	// src/main/scala/tile.scala:120:27, :199:{58,98}, :203:29, :223:33
      s2_mempot_rd_1 <= _GEN_0 ? io_rd_data_L2_N_1 : io_rd_data_main_mempot_1;	// src/main/scala/tile.scala:120:27, :199:{58,98}, :207:29, :223:33
      s2_mempot_rd_2 <= _GEN_0 ? io_rd_data_L2_N_2 : io_rd_data_main_mempot_2;	// src/main/scala/tile.scala:120:27, :199:{58,98}, :211:29, :223:33
      s2_mempot_rd_3 <= io_rd_data_main_mempot_3;	// src/main/scala/tile.scala:120:27
      s2_mempot_rd_4 <= io_rd_data_main_mempot_4;	// src/main/scala/tile.scala:120:27
      s2_mempot_rd_5 <= io_rd_data_main_mempot_5;	// src/main/scala/tile.scala:120:27
      s2_mempot_rd_6 <= io_rd_data_main_mempot_6;	// src/main/scala/tile.scala:120:27
      s2_mempot_rd_7 <= io_rd_data_main_mempot_7;	// src/main/scala/tile.scala:120:27
      s2_mempot_rd_8 <= io_rd_data_main_mempot_8;	// src/main/scala/tile.scala:120:27
    end
    if (_GEN_15) begin	// src/main/scala/tile.scala:230:19
      s3_conv_0 <= s2_mempot_rd_0 + {1'h0, io_kernel_8};	// src/main/scala/tile.scala:76:20, :120:27, :121:22, :232:43
      s3_conv_1 <= s2_mempot_rd_1 + {1'h0, io_kernel_7};	// src/main/scala/tile.scala:76:20, :120:27, :121:22, :232:43
      s3_conv_2 <= s2_mempot_rd_2 + {1'h0, io_kernel_6};	// src/main/scala/tile.scala:76:20, :120:27, :121:22, :232:43
      s3_conv_3 <= s2_mempot_rd_3 + {1'h0, io_kernel_5};	// src/main/scala/tile.scala:76:20, :120:27, :121:22, :232:43
      s3_conv_4 <= s2_mempot_rd_4 + {1'h0, io_kernel_4};	// src/main/scala/tile.scala:76:20, :120:27, :121:22, :232:43
      s3_conv_5 <= s2_mempot_rd_5 + {1'h0, io_kernel_3};	// src/main/scala/tile.scala:76:20, :120:27, :121:22, :232:43
      s3_conv_6 <= s2_mempot_rd_6 + {1'h0, io_kernel_2};	// src/main/scala/tile.scala:76:20, :120:27, :121:22, :232:43
      s3_conv_7 <= s2_mempot_rd_7 + {1'h0, io_kernel_1};	// src/main/scala/tile.scala:76:20, :120:27, :121:22, :232:43
      s3_conv_8 <= s2_mempot_rd_8 + {1'h0, io_kernel_0};	// src/main/scala/tile.scala:76:20, :120:27, :121:22, :232:43
    end
    if (_GEN_6) begin	// src/main/scala/tile.scala:317:23
      thresh_blk_counter <= thresh_blk_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :294:33, :347:50
      if (_GEN_7) begin	// src/main/scala/tile.scala:318:33
        s1_thresh_local_mem_rd_0 <= io_rd_data_L1_N_0;	// src/main/scala/tile.scala:306:37
        s1_thresh_local_mem_rd_1 <= io_rd_data_L1_N_1;	// src/main/scala/tile.scala:306:37
        s1_thresh_local_mem_rd_2 <= io_rd_data_L1_N_2;	// src/main/scala/tile.scala:306:37
      end
      else if (_GEN_9) begin	// src/main/scala/tile.scala:332:40
        s1_thresh_local_mem_rd_0 <= io_rd_data_L1_S_0;	// src/main/scala/tile.scala:306:37
        s1_thresh_local_mem_rd_1 <= io_rd_data_L1_S_1;	// src/main/scala/tile.scala:306:37
        s1_thresh_local_mem_rd_2 <= io_rd_data_L1_S_2;	// src/main/scala/tile.scala:306:37
      end
    end
    if (_GEN_10) begin	// src/main/scala/tile.scala:178:48, :317:32, :318:39, :327:41, :332:47, :341:41
      s1_thresh_main_mem_rd_0 <= io_rd_data_main_mempot_0;	// src/main/scala/tile.scala:305:36
      s1_thresh_main_mem_rd_1 <= io_rd_data_main_mempot_1;	// src/main/scala/tile.scala:305:36
      s1_thresh_main_mem_rd_2 <= io_rd_data_main_mempot_2;	// src/main/scala/tile.scala:305:36
      s1_thresh_main_mem_rd_3 <= io_rd_data_main_mempot_3;	// src/main/scala/tile.scala:305:36
      s1_thresh_main_mem_rd_4 <= io_rd_data_main_mempot_4;	// src/main/scala/tile.scala:305:36
      s1_thresh_main_mem_rd_5 <= io_rd_data_main_mempot_5;	// src/main/scala/tile.scala:305:36
      s1_thresh_main_mem_rd_6 <= io_rd_data_main_mempot_6;	// src/main/scala/tile.scala:305:36
      s1_thresh_main_mem_rd_7 <= io_rd_data_main_mempot_7;	// src/main/scala/tile.scala:305:36
      s1_thresh_main_mem_rd_8 <= io_rd_data_main_mempot_8;	// src/main/scala/tile.scala:305:36
    end
    if (_GEN_16) begin	// src/main/scala/tile.scala:352:26
      s2_thresh_bias_added_0 <=
        s1_thresh_main_mem_rd_0 + s1_thresh_local_mem_rd_0 + {1'h0, io_bias_0};	// src/main/scala/tile.scala:76:20, :305:36, :306:37, :307:35, :354:93
      s2_thresh_bias_added_1 <=
        s1_thresh_main_mem_rd_1 + s1_thresh_local_mem_rd_1 + {1'h0, io_bias_1};	// src/main/scala/tile.scala:76:20, :305:36, :306:37, :307:35, :354:93
      s2_thresh_bias_added_2 <=
        s1_thresh_main_mem_rd_2 + s1_thresh_local_mem_rd_2 + {1'h0, io_bias_2};	// src/main/scala/tile.scala:76:20, :305:36, :306:37, :307:35, :354:93
      s2_thresh_bias_added_3 <= s1_thresh_main_mem_rd_3 + {1'h0, io_bias_3};	// src/main/scala/tile.scala:76:20, :305:36, :307:35, :359:65
      s2_thresh_bias_added_4 <= s1_thresh_main_mem_rd_4 + {1'h0, io_bias_4};	// src/main/scala/tile.scala:76:20, :305:36, :307:35, :359:65
      s2_thresh_bias_added_5 <= s1_thresh_main_mem_rd_5 + {1'h0, io_bias_5};	// src/main/scala/tile.scala:76:20, :305:36, :307:35, :359:65
      s2_thresh_bias_added_6 <= s1_thresh_main_mem_rd_6 + {1'h0, io_bias_6};	// src/main/scala/tile.scala:76:20, :305:36, :307:35, :359:65
      s2_thresh_bias_added_7 <= s1_thresh_main_mem_rd_7 + {1'h0, io_bias_7};	// src/main/scala/tile.scala:76:20, :305:36, :307:35, :359:65
      s2_thresh_bias_added_8 <= s1_thresh_main_mem_rd_8 + {1'h0, io_bias_8};	// src/main/scala/tile.scala:76:20, :305:36, :307:35, :359:65
    end
    if (_GEN_17 & s2_thresh_bias_added_0 >= io_v_t)	// src/main/scala/tile.scala:307:35, :308:37, :366:{26,42}, :367:45, :369:46
      s3_thresh_aeq_out_data_0 <= {s3_thresh_blk_counter, 5'h1};	// src/main/scala/tile.scala:8:7, :308:37, :365:36, :370:47
    if (_GEN_17 & s2_thresh_bias_added_1 >= io_v_t)	// src/main/scala/tile.scala:307:35, :308:37, :366:{26,42}, :367:45, :369:46
      s3_thresh_aeq_out_data_1 <= {s3_thresh_blk_counter, 5'h3};	// src/main/scala/tile.scala:8:7, :308:37, :365:36, :370:47
    if (_GEN_17 & s2_thresh_bias_added_2 >= io_v_t)	// src/main/scala/tile.scala:307:35, :308:37, :366:{26,42}, :367:45, :369:46
      s3_thresh_aeq_out_data_2 <= {s3_thresh_blk_counter, 5'h5};	// src/main/scala/tile.scala:8:7, :308:37, :365:36, :370:47
    if (_GEN_17 & s2_thresh_bias_added_3 >= io_v_t)	// src/main/scala/tile.scala:307:35, :308:37, :366:{26,42}, :367:45, :369:46
      s3_thresh_aeq_out_data_3 <= {s3_thresh_blk_counter, 5'h7};	// src/main/scala/tile.scala:8:7, :308:37, :365:36, :370:47
    if (_GEN_17 & s2_thresh_bias_added_4 >= io_v_t)	// src/main/scala/tile.scala:307:35, :308:37, :366:{26,42}, :367:45, :369:46
      s3_thresh_aeq_out_data_4 <= {s3_thresh_blk_counter, 5'h9};	// src/main/scala/tile.scala:8:7, :308:37, :365:36, :370:47
    if (_GEN_17 & s2_thresh_bias_added_5 >= io_v_t)	// src/main/scala/tile.scala:307:35, :308:37, :366:{26,42}, :367:45, :369:46
      s3_thresh_aeq_out_data_5 <= {s3_thresh_blk_counter, 5'hB};	// src/main/scala/tile.scala:8:7, :308:37, :365:36, :370:47
    if (_GEN_17 & s2_thresh_bias_added_6 >= io_v_t)	// src/main/scala/tile.scala:307:35, :308:37, :366:{26,42}, :367:45, :369:46
      s3_thresh_aeq_out_data_6 <= {s3_thresh_blk_counter, 5'hD};	// src/main/scala/tile.scala:8:7, :308:37, :365:36, :370:47
    if (_GEN_17 & s2_thresh_bias_added_7 >= io_v_t)	// src/main/scala/tile.scala:307:35, :308:37, :366:{26,42}, :367:45, :369:46
      s3_thresh_aeq_out_data_7 <= {s3_thresh_blk_counter, 5'hF};	// src/main/scala/tile.scala:8:7, :308:37, :365:36, :370:47
    if (_GEN_17 & s2_thresh_bias_added_8 >= io_v_t)	// src/main/scala/tile.scala:307:35, :308:37, :366:{26,42}, :367:45, :369:46
      s3_thresh_aeq_out_data_8 <= {s3_thresh_blk_counter, 5'h11};	// src/main/scala/tile.scala:8:7, :308:37, :365:36, :370:47
    if (_GEN_17)	// src/main/scala/tile.scala:366:26
      s3_thresh_blk_counter <= s3_thresh_blk_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :365:36, :380:56
    if (io_wr_en_aeq_o_0) begin	// src/main/scala/tile.scala:386:26
      if (s3_thresh_aeq_out_data_8[0])	// src/main/scala/tile.scala:308:37, :390:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :385:36, :393:64
      else if (s3_thresh_aeq_out_data_7[0])	// src/main/scala/tile.scala:308:37, :390:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :385:36, :393:64
      else if (s3_thresh_aeq_out_data_6[0])	// src/main/scala/tile.scala:308:37, :390:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :385:36, :393:64
      else if (s3_thresh_aeq_out_data_5[0])	// src/main/scala/tile.scala:308:37, :390:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :385:36, :393:64
      else if (s3_thresh_aeq_out_data_4[0])	// src/main/scala/tile.scala:308:37, :390:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :385:36, :393:64
      else if (s3_thresh_aeq_out_data_3[0])	// src/main/scala/tile.scala:308:37, :390:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :385:36, :393:64
      else if (s3_thresh_aeq_out_data_2[0])	// src/main/scala/tile.scala:308:37, :390:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :385:36, :393:64
      else if (s3_thresh_aeq_out_data_1[0])	// src/main/scala/tile.scala:308:37, :390:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :385:36, :393:64
      else if (s3_thresh_aeq_out_data_0[0])	// src/main/scala/tile.scala:308:37, :390:43
        s4_thresh_aeq_counter <= s4_thresh_aeq_counter + 5'h1;	// src/main/scala/tile.scala:8:7, :385:36, :393:64
    end
    if (reset) begin	// src/main/scala/tile.scala:8:7
      s1_valid <= 1'h0;	// src/main/scala/tile.scala:76:20, :123:27
      s2_valid <= 1'h0;	// src/main/scala/tile.scala:76:20, :124:27
      s3_valid <= 1'h0;	// src/main/scala/tile.scala:76:20, :125:27
      conv_done_reg <= 1'h0;	// src/main/scala/tile.scala:76:20, :130:32
      thresh_done_reg <= 1'h0;	// src/main/scala/tile.scala:76:20, :131:34
      read_counter <= 8'h0;	// src/main/scala/tile.scala:84:38, :141:31
      i <= 1'h0;	// src/main/scala/tile.scala:76:20, :156:28
      read_mem_counter <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/tile.scala:8:7
      s1_thresh_valid <= 1'h0;	// src/main/scala/tile.scala:76:20, :311:34
      s2_thresh_valid <= 1'h0;	// src/main/scala/tile.scala:76:20, :312:34
      s3_thresh_valid <= 1'h0;	// src/main/scala/tile.scala:76:20, :313:34
    end
    else begin	// src/main/scala/tile.scala:8:7
      automatic logic _GEN_18;	// src/main/scala/tile.scala:171:30
      _GEN_18 = io_rd_data_aeq_i[10] | ~(io_rd_data_aeq_i[0]);	// src/main/scala/tile.scala:148:{25,44}, :171:{30,33}
      if (io_rd_en_aeq_i_0) begin	// src/main/scala/tile.scala:142:36
        s1_valid <= _GEN_12;	// src/main/scala/tile.scala:123:27, :148:29
        if (_GEN_18)	// src/main/scala/tile.scala:171:30
          read_counter <= 8'h0;	// src/main/scala/tile.scala:84:38, :141:31
        else	// src/main/scala/tile.scala:171:30
          read_counter <= read_counter + 8'h1;	// src/main/scala/tile.scala:141:31, :170:38
      end
      s2_valid <= _GEN | s2_valid;	// src/main/scala/tile.scala:124:27, :178:{34,48}, :226:18
      s3_valid <= _GEN_15 | s3_valid;	// src/main/scala/tile.scala:125:27, :230:{19,34}, :234:18
      conv_done_reg <= io_rd_en_aeq_i_0 & _GEN_18 | conv_done_reg;	// src/main/scala/tile.scala:130:32, :142:{36,55}, :171:{30,50}, :173:27
      thresh_done_reg <= wrap;	// src/main/scala/chisel3/util/Counter.scala:117:24, :118:{16,23}, src/main/scala/tile.scala:131:34
      i <= i - 1'h1;	// src/main/scala/tile.scala:156:28, :165:28
      if (_GEN_5) begin	// src/main/scala/tile.scala:293:57
        if (wrap_wrap)	// src/main/scala/chisel3/util/Counter.scala:73:24
          read_mem_counter <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/tile.scala:8:7
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          read_mem_counter <= read_mem_counter + 5'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24, src/main/scala/tile.scala:8:7
      end
      s1_thresh_valid <= _GEN_6 | s1_thresh_valid;	// src/main/scala/tile.scala:311:34, :317:{23,32}, :348:25
      s2_thresh_valid <= _GEN_16 | s2_thresh_valid;	// src/main/scala/tile.scala:312:34, :352:{26,42}, :361:25
      s3_thresh_valid <= _GEN_17 | s3_thresh_valid;	// src/main/scala/tile.scala:313:34, :366:{26,42}, :381:25
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/tile.scala:8:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/tile.scala:8:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/tile.scala:8:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/tile.scala:8:7
      automatic logic [31:0] _RANDOM[0:19];	// src/main/scala/tile.scala:8:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/tile.scala:8:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/tile.scala:8:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/tile.scala:8:7
        for (logic [4:0] i_0 = 5'h0; i_0 < 5'h14; i_0 += 5'h1) begin
          _RANDOM[i_0] = `RANDOM;	// src/main/scala/tile.scala:8:7
        end	// src/main/scala/tile.scala:8:7
        s1_addr_calc_0 = _RANDOM[5'h2][16:8];	// src/main/scala/tile.scala:8:7, :119:27
        s1_addr_calc_1 = _RANDOM[5'h2][25:17];	// src/main/scala/tile.scala:8:7, :119:27
        s2_mempot_rd_0 = {_RANDOM[5'h4][31:25], _RANDOM[5'h5][1:0]};	// src/main/scala/tile.scala:8:7, :120:27
        s2_mempot_rd_1 = _RANDOM[5'h5][10:2];	// src/main/scala/tile.scala:8:7, :120:27
        s2_mempot_rd_2 = _RANDOM[5'h5][19:11];	// src/main/scala/tile.scala:8:7, :120:27
        s2_mempot_rd_3 = _RANDOM[5'h5][28:20];	// src/main/scala/tile.scala:8:7, :120:27
        s2_mempot_rd_4 = {_RANDOM[5'h5][31:29], _RANDOM[5'h6][5:0]};	// src/main/scala/tile.scala:8:7, :120:27
        s2_mempot_rd_5 = _RANDOM[5'h6][14:6];	// src/main/scala/tile.scala:8:7, :120:27
        s2_mempot_rd_6 = _RANDOM[5'h6][23:15];	// src/main/scala/tile.scala:8:7, :120:27
        s2_mempot_rd_7 = {_RANDOM[5'h6][31:24], _RANDOM[5'h7][0]};	// src/main/scala/tile.scala:8:7, :120:27
        s2_mempot_rd_8 = _RANDOM[5'h7][9:1];	// src/main/scala/tile.scala:8:7, :120:27
        s3_conv_0 = _RANDOM[5'h7][18:10];	// src/main/scala/tile.scala:8:7, :120:27, :121:22
        s3_conv_1 = _RANDOM[5'h7][27:19];	// src/main/scala/tile.scala:8:7, :120:27, :121:22
        s3_conv_2 = {_RANDOM[5'h7][31:28], _RANDOM[5'h8][4:0]};	// src/main/scala/tile.scala:8:7, :120:27, :121:22
        s3_conv_3 = _RANDOM[5'h8][13:5];	// src/main/scala/tile.scala:8:7, :121:22
        s3_conv_4 = _RANDOM[5'h8][22:14];	// src/main/scala/tile.scala:8:7, :121:22
        s3_conv_5 = _RANDOM[5'h8][31:23];	// src/main/scala/tile.scala:8:7, :121:22
        s3_conv_6 = _RANDOM[5'h9][8:0];	// src/main/scala/tile.scala:8:7, :121:22
        s3_conv_7 = _RANDOM[5'h9][17:9];	// src/main/scala/tile.scala:8:7, :121:22
        s3_conv_8 = _RANDOM[5'h9][26:18];	// src/main/scala/tile.scala:8:7, :121:22
        s1_valid = _RANDOM[5'h9][27];	// src/main/scala/tile.scala:8:7, :121:22, :123:27
        s2_valid = _RANDOM[5'h9][28];	// src/main/scala/tile.scala:8:7, :121:22, :124:27
        s3_valid = _RANDOM[5'h9][29];	// src/main/scala/tile.scala:8:7, :121:22, :125:27
        conv_done_reg = _RANDOM[5'h9][31];	// src/main/scala/tile.scala:8:7, :121:22, :130:32
        thresh_done_reg = _RANDOM[5'hA][0];	// src/main/scala/tile.scala:8:7, :131:34
        read_counter = _RANDOM[5'hA][8:1];	// src/main/scala/tile.scala:8:7, :131:34, :141:31
        i = _RANDOM[5'hA][9];	// src/main/scala/tile.scala:8:7, :131:34, :156:28
        read_mem_counter = _RANDOM[5'hA][14:10];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/tile.scala:8:7, :131:34
        thresh_blk_counter = _RANDOM[5'hA][19:15];	// src/main/scala/tile.scala:8:7, :131:34, :294:33
        s1_thresh_main_mem_rd_0 = _RANDOM[5'hA][28:20];	// src/main/scala/tile.scala:8:7, :131:34, :305:36
        s1_thresh_main_mem_rd_1 = {_RANDOM[5'hA][31:29], _RANDOM[5'hB][5:0]};	// src/main/scala/tile.scala:8:7, :131:34, :305:36
        s1_thresh_main_mem_rd_2 = _RANDOM[5'hB][14:6];	// src/main/scala/tile.scala:8:7, :305:36
        s1_thresh_main_mem_rd_3 = _RANDOM[5'hB][23:15];	// src/main/scala/tile.scala:8:7, :305:36
        s1_thresh_main_mem_rd_4 = {_RANDOM[5'hB][31:24], _RANDOM[5'hC][0]};	// src/main/scala/tile.scala:8:7, :305:36
        s1_thresh_main_mem_rd_5 = _RANDOM[5'hC][9:1];	// src/main/scala/tile.scala:8:7, :305:36
        s1_thresh_main_mem_rd_6 = _RANDOM[5'hC][18:10];	// src/main/scala/tile.scala:8:7, :305:36
        s1_thresh_main_mem_rd_7 = _RANDOM[5'hC][27:19];	// src/main/scala/tile.scala:8:7, :305:36
        s1_thresh_main_mem_rd_8 = {_RANDOM[5'hC][31:28], _RANDOM[5'hD][4:0]};	// src/main/scala/tile.scala:8:7, :305:36
        s1_thresh_local_mem_rd_0 = _RANDOM[5'hD][13:5];	// src/main/scala/tile.scala:8:7, :305:36, :306:37
        s1_thresh_local_mem_rd_1 = _RANDOM[5'hD][22:14];	// src/main/scala/tile.scala:8:7, :305:36, :306:37
        s1_thresh_local_mem_rd_2 = _RANDOM[5'hD][31:23];	// src/main/scala/tile.scala:8:7, :305:36, :306:37
        s2_thresh_bias_added_0 = _RANDOM[5'hE][8:0];	// src/main/scala/tile.scala:8:7, :307:35
        s2_thresh_bias_added_1 = _RANDOM[5'hE][17:9];	// src/main/scala/tile.scala:8:7, :307:35
        s2_thresh_bias_added_2 = _RANDOM[5'hE][26:18];	// src/main/scala/tile.scala:8:7, :307:35
        s2_thresh_bias_added_3 = {_RANDOM[5'hE][31:27], _RANDOM[5'hF][3:0]};	// src/main/scala/tile.scala:8:7, :307:35
        s2_thresh_bias_added_4 = _RANDOM[5'hF][12:4];	// src/main/scala/tile.scala:8:7, :307:35
        s2_thresh_bias_added_5 = _RANDOM[5'hF][21:13];	// src/main/scala/tile.scala:8:7, :307:35
        s2_thresh_bias_added_6 = _RANDOM[5'hF][30:22];	// src/main/scala/tile.scala:8:7, :307:35
        s2_thresh_bias_added_7 = {_RANDOM[5'hF][31], _RANDOM[5'h10][7:0]};	// src/main/scala/tile.scala:8:7, :307:35
        s2_thresh_bias_added_8 = _RANDOM[5'h10][16:8];	// src/main/scala/tile.scala:8:7, :307:35
        s3_thresh_aeq_out_data_0 = _RANDOM[5'h10][26:17];	// src/main/scala/tile.scala:8:7, :307:35, :308:37
        s3_thresh_aeq_out_data_1 = {_RANDOM[5'h10][31:27], _RANDOM[5'h11][4:0]};	// src/main/scala/tile.scala:8:7, :307:35, :308:37
        s3_thresh_aeq_out_data_2 = _RANDOM[5'h11][14:5];	// src/main/scala/tile.scala:8:7, :308:37
        s3_thresh_aeq_out_data_3 = _RANDOM[5'h11][24:15];	// src/main/scala/tile.scala:8:7, :308:37
        s3_thresh_aeq_out_data_4 = {_RANDOM[5'h11][31:25], _RANDOM[5'h12][2:0]};	// src/main/scala/tile.scala:8:7, :308:37
        s3_thresh_aeq_out_data_5 = _RANDOM[5'h12][12:3];	// src/main/scala/tile.scala:8:7, :308:37
        s3_thresh_aeq_out_data_6 = _RANDOM[5'h12][22:13];	// src/main/scala/tile.scala:8:7, :308:37
        s3_thresh_aeq_out_data_7 = {_RANDOM[5'h12][31:23], _RANDOM[5'h13][0]};	// src/main/scala/tile.scala:8:7, :308:37
        s3_thresh_aeq_out_data_8 = _RANDOM[5'h13][10:1];	// src/main/scala/tile.scala:8:7, :308:37
        s1_thresh_valid = _RANDOM[5'h13][11];	// src/main/scala/tile.scala:8:7, :308:37, :311:34
        s2_thresh_valid = _RANDOM[5'h13][12];	// src/main/scala/tile.scala:8:7, :308:37, :312:34
        s3_thresh_valid = _RANDOM[5'h13][13];	// src/main/scala/tile.scala:8:7, :308:37, :313:34
        s3_thresh_blk_counter = _RANDOM[5'h13][18:14];	// src/main/scala/tile.scala:8:7, :308:37, :365:36
        s4_thresh_aeq_counter = _RANDOM[5'h13][23:19];	// src/main/scala/tile.scala:8:7, :308:37, :385:36
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/tile.scala:8:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/tile.scala:8:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rd_en_aeq_i = io_rd_en_aeq_i_0;	// src/main/scala/tile.scala:8:7, :142:36
  assign io_rd_addr_aeq_i = io_rd_en_aeq_i_0 ? {1'h0, read_counter} : 9'h0;	// src/main/scala/tile.scala:8:7, :76:20, :77:22, :85:38, :141:31, :142:{36,55}, :144:26
  assign io_wr_en_aeq_o = io_wr_en_aeq_o_0;	// src/main/scala/tile.scala:8:7, :386:26
  assign io_wr_addr_aeq_o =
    io_wr_en_aeq_o_0
    & (s3_thresh_aeq_out_data_8[0] | s3_thresh_aeq_out_data_7[0]
       | s3_thresh_aeq_out_data_6[0] | s3_thresh_aeq_out_data_5[0]
       | s3_thresh_aeq_out_data_4[0] | s3_thresh_aeq_out_data_3[0]
       | s3_thresh_aeq_out_data_2[0] | s3_thresh_aeq_out_data_1[0]
       | s3_thresh_aeq_out_data_0[0])
      ? {4'h0, s4_thresh_aeq_counter}
      : 9'h0;	// src/main/scala/tile.scala:8:7, :80:22, :85:38, :154:25, :308:37, :385:36, :386:{26,42}, :390:{43,47}, :391:34
  assign io_wr_data_aeq_o =
    io_wr_en_aeq_o_0
      ? (s3_thresh_aeq_out_data_8[0]
           ? {1'h0, s3_thresh_aeq_out_data_8}
           : s3_thresh_aeq_out_data_7[0]
               ? {1'h0, s3_thresh_aeq_out_data_7}
               : s3_thresh_aeq_out_data_6[0]
                   ? {1'h0, s3_thresh_aeq_out_data_6}
                   : s3_thresh_aeq_out_data_5[0]
                       ? {1'h0, s3_thresh_aeq_out_data_5}
                       : s3_thresh_aeq_out_data_4[0]
                           ? {1'h0, s3_thresh_aeq_out_data_4}
                           : s3_thresh_aeq_out_data_3[0]
                               ? {1'h0, s3_thresh_aeq_out_data_3}
                               : s3_thresh_aeq_out_data_2[0]
                                   ? {1'h0, s3_thresh_aeq_out_data_2}
                                   : s3_thresh_aeq_out_data_1[0]
                                       ? {1'h0, s3_thresh_aeq_out_data_1}
                                       : s3_thresh_aeq_out_data_0[0]
                                           ? {1'h0, s3_thresh_aeq_out_data_0}
                                           : 11'h0)
      : 11'h0;	// src/main/scala/tile.scala:8:7, :76:20, :81:22, :308:37, :386:{26,42}, :390:{43,47}, :392:34
  assign io_wr_en_main_mempot_0 = io_wr_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :83:26, :239:34, :241:92
  assign io_wr_en_main_mempot_1 = io_wr_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :83:26, :239:34, :241:92
  assign io_wr_en_main_mempot_2 = io_wr_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :83:26, :239:34, :241:92
  assign io_wr_en_main_mempot_3 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :239:19
  assign io_wr_en_main_mempot_4 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :239:19
  assign io_wr_en_main_mempot_5 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :239:19
  assign io_wr_en_main_mempot_6 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :239:19
  assign io_wr_en_main_mempot_7 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :239:19
  assign io_wr_en_main_mempot_8 = io_wr_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :239:19
  assign io_wr_addr_main_mempot_0 = _GEN_4 ? 8'h0 : s1_addr_calc_0[7:0];	// src/main/scala/tile.scala:8:7, :84:{28,38}, :119:27, :184:43, :239:34, :241:92
  assign io_wr_addr_main_mempot_1 = _GEN_4 ? 8'h0 : s1_addr_calc_1[7:0];	// src/main/scala/tile.scala:8:7, :84:{28,38}, :119:27, :184:43, :239:34, :241:92
  assign io_wr_addr_main_mempot_2 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_addr_main_mempot_3 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_addr_main_mempot_4 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_addr_main_mempot_5 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_addr_main_mempot_6 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_addr_main_mempot_7 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_addr_main_mempot_8 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_data_main_mempot_0 = _GEN_4 ? 9'h0 : s3_conv_0;	// src/main/scala/tile.scala:8:7, :84:28, :85:{28,38}, :121:22, :239:34, :241:92
  assign io_wr_data_main_mempot_1 = _GEN_4 ? 9'h0 : s3_conv_1;	// src/main/scala/tile.scala:8:7, :84:28, :85:{28,38}, :121:22, :239:34, :241:92
  assign io_wr_data_main_mempot_2 = _GEN_4 ? 9'h0 : s3_conv_2;	// src/main/scala/tile.scala:8:7, :84:28, :85:{28,38}, :121:22, :239:34, :241:92
  assign io_wr_data_main_mempot_3 = io_wr_en_main_mempot_5_0 ? s3_conv_3 : 9'h0;	// src/main/scala/tile.scala:8:7, :85:{28,38}, :121:22, :239:{19,34}, :241:92
  assign io_wr_data_main_mempot_4 = io_wr_en_main_mempot_5_0 ? s3_conv_4 : 9'h0;	// src/main/scala/tile.scala:8:7, :85:{28,38}, :121:22, :239:{19,34}, :241:92
  assign io_wr_data_main_mempot_5 = io_wr_en_main_mempot_5_0 ? s3_conv_5 : 9'h0;	// src/main/scala/tile.scala:8:7, :85:{28,38}, :121:22, :239:{19,34}, :241:92
  assign io_wr_data_main_mempot_6 = io_wr_en_main_mempot_5_0 ? s3_conv_6 : 9'h0;	// src/main/scala/tile.scala:8:7, :85:{28,38}, :121:22, :239:{19,34}, :241:92
  assign io_wr_data_main_mempot_7 = io_wr_en_main_mempot_5_0 ? s3_conv_7 : 9'h0;	// src/main/scala/tile.scala:8:7, :85:{28,38}, :121:22, :239:{19,34}, :241:92
  assign io_wr_data_main_mempot_8 = io_wr_en_main_mempot_5_0 ? s3_conv_8 : 9'h0;	// src/main/scala/tile.scala:8:7, :85:{28,38}, :121:22, :239:{19,34}, :241:92
  assign io_rd_en_main_mempot_0 = io_rd_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :178:48, :317:32, :318:39, :327:41, :332:47, :341:41
  assign io_rd_en_main_mempot_1 = io_rd_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :178:48, :317:32, :318:39, :327:41, :332:47, :341:41
  assign io_rd_en_main_mempot_2 = io_rd_en_main_mempot_2_0;	// src/main/scala/tile.scala:8:7, :178:48, :317:32, :318:39, :327:41, :332:47, :341:41
  assign io_rd_en_main_mempot_3 = io_rd_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :178:48, :317:32, :318:39, :327:41, :332:47, :341:41
  assign io_rd_en_main_mempot_4 = io_rd_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :178:48, :317:32, :318:39, :327:41, :332:47, :341:41
  assign io_rd_en_main_mempot_5 = io_rd_en_main_mempot_5_0;	// src/main/scala/tile.scala:8:7, :178:48, :317:32, :318:39, :327:41, :332:47, :341:41
  assign io_rd_en_main_mempot_6 = io_rd_en_main_mempot_8_0;	// src/main/scala/tile.scala:8:7, :178:48, :317:32, :318:39, :327:41, :332:47, :341:41
  assign io_rd_en_main_mempot_7 = io_rd_en_main_mempot_8_0;	// src/main/scala/tile.scala:8:7, :178:48, :317:32, :318:39, :327:41, :332:47, :341:41
  assign io_rd_en_main_mempot_8 = io_rd_en_main_mempot_8_0;	// src/main/scala/tile.scala:8:7, :178:48, :317:32, :318:39, :327:41, :332:47, :341:41
  assign io_rd_addr_main_mempot_0 =
    _GEN_11 ? _GEN_8 : _GEN_2 ? 8'h0 : s1_addr_calc_0[7:0];	// src/main/scala/tile.scala:8:7, :84:38, :88:28, :119:27, :178:48, :180:92, :184:43, :317:32, :318:39, :322:36
  assign io_rd_addr_main_mempot_1 =
    _GEN_11 ? _GEN_8 : _GEN_2 ? 8'h0 : s1_addr_calc_1[7:0];	// src/main/scala/tile.scala:8:7, :84:38, :88:28, :119:27, :178:48, :180:92, :184:43, :317:32, :318:39, :322:36
  assign io_rd_addr_main_mempot_2 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :178:48, :317:32, :318:39, :322:36
  assign io_rd_addr_main_mempot_3 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :178:48, :317:32, :318:39, :322:36
  assign io_rd_addr_main_mempot_4 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :178:48, :317:32, :318:39, :322:36
  assign io_rd_addr_main_mempot_5 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :178:48, :317:32, :318:39, :322:36
  assign io_rd_addr_main_mempot_6 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :178:48, :317:32, :318:39, :322:36
  assign io_rd_addr_main_mempot_7 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :178:48, :317:32, :318:39, :322:36
  assign io_rd_addr_main_mempot_8 = _GEN_11 ? _GEN_8 : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :178:48, :317:32, :318:39, :322:36
  assign io_wr_en_L2_N_0 = 1'h0;	// src/main/scala/tile.scala:8:7, :76:20
  assign io_wr_en_L2_N_1 = 1'h0;	// src/main/scala/tile.scala:8:7, :76:20
  assign io_wr_en_L2_N_2 = 1'h0;	// src/main/scala/tile.scala:8:7, :76:20
  assign io_wr_addr_L2_N_0 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_addr_L2_N_1 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_addr_L2_N_2 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_data_L2_N_0 = 9'h0;	// src/main/scala/tile.scala:8:7, :85:38
  assign io_wr_data_L2_N_1 = 9'h0;	// src/main/scala/tile.scala:8:7, :85:38
  assign io_wr_data_L2_N_2 = 9'h0;	// src/main/scala/tile.scala:8:7, :85:38
  assign io_rd_en_L2_N_0 = io_rd_en_L2_N_2_0;	// src/main/scala/tile.scala:8:7, :93:19, :178:48, :180:92
  assign io_rd_en_L2_N_1 = io_rd_en_L2_N_2_0;	// src/main/scala/tile.scala:8:7, :93:19, :178:48, :180:92
  assign io_rd_en_L2_N_2 = io_rd_en_L2_N_2_0;	// src/main/scala/tile.scala:8:7, :93:19, :178:48, :180:92
  assign io_rd_addr_L2_N_0 = _GEN_1 ? s1_addr_calc_0[7:0] : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :94:21, :119:27, :178:48, :180:92, :184:43
  assign io_rd_addr_L2_N_1 = _GEN_1 ? s1_addr_calc_1[7:0] : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :94:21, :119:27, :178:48, :180:92, :184:43
  assign io_rd_addr_L2_N_2 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_en_L2_S_0 = io_wr_en_L2_S_2_0;	// src/main/scala/tile.scala:8:7, :96:19, :239:34, :241:92
  assign io_wr_en_L2_S_1 = io_wr_en_L2_S_2_0;	// src/main/scala/tile.scala:8:7, :96:19, :239:34, :241:92
  assign io_wr_en_L2_S_2 = io_wr_en_L2_S_2_0;	// src/main/scala/tile.scala:8:7, :96:19, :239:34, :241:92
  assign io_wr_addr_L2_S_0 = _GEN_3 ? s1_addr_calc_0[7:0] : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :97:21, :119:27, :184:43, :239:34, :241:92
  assign io_wr_addr_L2_S_1 = _GEN_3 ? s1_addr_calc_1[7:0] : 8'h0;	// src/main/scala/tile.scala:8:7, :84:38, :97:21, :119:27, :184:43, :239:34, :241:92
  assign io_wr_addr_L2_S_2 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_wr_data_L2_S_0 = _GEN_3 ? s3_conv_0 : 9'h0;	// src/main/scala/tile.scala:8:7, :85:38, :97:21, :98:21, :121:22, :239:34, :241:92
  assign io_wr_data_L2_S_1 = _GEN_3 ? s3_conv_1 : 9'h0;	// src/main/scala/tile.scala:8:7, :85:38, :97:21, :98:21, :121:22, :239:34, :241:92
  assign io_wr_data_L2_S_2 = _GEN_3 ? s3_conv_2 : 9'h0;	// src/main/scala/tile.scala:8:7, :85:38, :97:21, :98:21, :121:22, :239:34, :241:92
  assign io_rd_en_L2_S_0 = 1'h0;	// src/main/scala/tile.scala:8:7, :76:20
  assign io_rd_en_L2_S_1 = 1'h0;	// src/main/scala/tile.scala:8:7, :76:20
  assign io_rd_en_L2_S_2 = 1'h0;	// src/main/scala/tile.scala:8:7, :76:20
  assign io_rd_addr_L2_S_0 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_rd_addr_L2_S_1 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_rd_addr_L2_S_2 = 8'h0;	// src/main/scala/tile.scala:8:7, :84:38
  assign io_rd_en_L1_N = _GEN_6 & _GEN_7;	// src/main/scala/tile.scala:8:7, :102:19, :317:{23,32}, :318:{33,39}
  assign io_rd_addr_L1_N_0 = io_rd_addr_L1_N_2_0;	// src/main/scala/tile.scala:8:7, :103:21, :317:32, :318:39, :322:36
  assign io_rd_addr_L1_N_1 = io_rd_addr_L1_N_2_0;	// src/main/scala/tile.scala:8:7, :103:21, :317:32, :318:39, :322:36
  assign io_rd_addr_L1_N_2 = io_rd_addr_L1_N_2_0;	// src/main/scala/tile.scala:8:7, :103:21, :317:32, :318:39, :322:36
  assign io_rd_en_L1_S = _GEN_6 & ~_GEN_7 & _GEN_9;	// src/main/scala/tile.scala:8:7, :105:19, :317:{23,32}, :318:{33,39}, :332:{40,47}
  assign io_rd_addr_L1_S_0 = io_rd_addr_L1_S_2_0;	// src/main/scala/tile.scala:8:7, :106:21, :317:32, :318:39
  assign io_rd_addr_L1_S_1 = io_rd_addr_L1_S_2_0;	// src/main/scala/tile.scala:8:7, :106:21, :317:32, :318:39
  assign io_rd_addr_L1_S_2 = io_rd_addr_L1_S_2_0;	// src/main/scala/tile.scala:8:7, :106:21, :317:32, :318:39
  assign io_conv_done = conv_done_reg;	// src/main/scala/tile.scala:8:7, :130:32
  assign io_thresh_done = thresh_done_reg;	// src/main/scala/tile.scala:8:7, :131:34
endmodule

