// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module tu3(	// src/main/scala/tile/tu3.scala:10:7
  input        clock,	// src/main/scala/tile/tu3.scala:10:7
               reset,	// src/main/scala/tile/tu3.scala:10:7
  output [9:0] io_tu_io_mm_rdaddr_0,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rdaddr_1,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rdaddr_2,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rdaddr_3,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rdaddr_4,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rdaddr_5,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rdaddr_6,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rdaddr_7,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rdaddr_8,	// src/main/scala/tile/tu3.scala:11:16
  input  [7:0] io_tu_io_mm_rddata_0,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rddata_1,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rddata_2,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rddata_3,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rddata_4,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rddata_5,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rddata_6,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rddata_7,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_mm_rddata_8,	// src/main/scala/tile/tu3.scala:11:16
  output [9:0] io_tu_io_ln1_rdaddr_0,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ln1_rdaddr_1,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ln1_rdaddr_2,	// src/main/scala/tile/tu3.scala:11:16
  input  [7:0] io_tu_io_ln1_rddata_0,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ln1_rddata_1,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ln1_rddata_2,	// src/main/scala/tile/tu3.scala:11:16
  output [9:0] io_tu_io_ls1_rdaddr_0,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ls1_rdaddr_1,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ls1_rdaddr_2,	// src/main/scala/tile/tu3.scala:11:16
  input  [7:0] io_tu_io_ls1_rddata_0,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ls1_rddata_1,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ls1_rddata_2,	// src/main/scala/tile/tu3.scala:11:16
  output [9:0] io_tu_io_ao_wraddr_0,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wraddr_1,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wraddr_2,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wraddr_3,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wraddr_4,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wraddr_5,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wraddr_6,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wraddr_7,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wraddr_8,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wrdata_0,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wrdata_1,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wrdata_2,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wrdata_3,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wrdata_4,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wrdata_5,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wrdata_6,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wrdata_7,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_wrdata_8,	// src/main/scala/tile/tu3.scala:11:16
  output       io_tu_io_ao_we_0,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_we_1,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_we_2,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_we_3,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_we_4,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_we_5,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_we_6,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_we_7,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_ao_we_8,	// src/main/scala/tile/tu3.scala:11:16
  input        io_tu_io_thresh_en,	// src/main/scala/tile/tu3.scala:11:16
  input  [7:0] io_tu_io_bias,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_v_t,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_T,	// src/main/scala/tile/tu3.scala:11:16
               io_tu_io_N,	// src/main/scala/tile/tu3.scala:11:16
  input        io_tu_io_maxpool_en,	// src/main/scala/tile/tu3.scala:11:16
  output       io_tu_io_thresh_done	// src/main/scala/tile/tu3.scala:11:16
);

  wire [7:0] i_max = (io_tu_io_N - 8'h1) / 8'h3;	// src/main/scala/tile/tu3.scala:17:{29,35}
  wire [7:0] _se_col_T = io_tu_io_T - 8'h1;	// src/main/scala/tile/tu3.scala:18:29
  wire [7:0] j_max = _se_col_T / 8'h3;	// src/main/scala/tile/tu3.scala:17:35, :18:{29,35}
  reg  [1:0] i_cnt;	// src/main/scala/tile/tu3.scala:22:24
  reg  [1:0] j_cnt;	// src/main/scala/tile/tu3.scala:23:24
  reg  [7:0] addr_write;	// src/main/scala/tile/tu3.scala:24:25
  reg  [7:0] addr_write_s3_REG;	// src/main/scala/tile/tu3.scala:25:40
  reg  [7:0] addr_write_s3;	// src/main/scala/tile/tu3.scala:25:32
  reg  [1:0] i_cnt_s3_REG;	// src/main/scala/tile/tu3.scala:26:35
  reg  [1:0] i_cnt_s3;	// src/main/scala/tile/tu3.scala:26:27
  reg  [1:0] j_cnt_s3_REG;	// src/main/scala/tile/tu3.scala:27:35
  reg  [1:0] j_cnt_s3;	// src/main/scala/tile/tu3.scala:27:27
  reg  [7:0] mempot_rd_main_0;	// src/main/scala/tile/tu3.scala:31:29
  reg  [7:0] mempot_rd_main_1;	// src/main/scala/tile/tu3.scala:31:29
  reg  [7:0] mempot_rd_main_2;	// src/main/scala/tile/tu3.scala:31:29
  reg  [7:0] mempot_rd_main_3;	// src/main/scala/tile/tu3.scala:31:29
  reg  [7:0] mempot_rd_main_4;	// src/main/scala/tile/tu3.scala:31:29
  reg  [7:0] mempot_rd_main_5;	// src/main/scala/tile/tu3.scala:31:29
  reg  [7:0] mempot_rd_main_6;	// src/main/scala/tile/tu3.scala:31:29
  reg  [7:0] mempot_rd_main_7;	// src/main/scala/tile/tu3.scala:31:29
  reg  [7:0] mempot_rd_main_8;	// src/main/scala/tile/tu3.scala:31:29
  reg  [7:0] mempot_rd_local_0;	// src/main/scala/tile/tu3.scala:32:30
  reg  [7:0] mempot_rd_local_1;	// src/main/scala/tile/tu3.scala:32:30
  reg  [7:0] mempot_rd_local_2;	// src/main/scala/tile/tu3.scala:32:30
  reg        isNorth_s2;	// src/main/scala/tile/tu3.scala:42:29
  reg        isSouth_s2;	// src/main/scala/tile/tu3.scala:43:29
  reg        io_tu_io_thresh_done_REG;	// src/main/scala/tile/tu3.scala:47:60
  reg        io_tu_io_thresh_done_REG_1;	// src/main/scala/tile/tu3.scala:47:52
  reg        io_tu_io_thresh_done_REG_2;	// src/main/scala/tile/tu3.scala:47:44
  reg        io_tu_io_thresh_done_REG_3;	// src/main/scala/tile/tu3.scala:47:36
  wire [9:0] io_tu_io_ls1_rdaddr_2_0 = {8'h0, j_cnt};	// src/main/scala/tile/tu3.scala:23:24, :52:52, :72:36
  wire [9:0] _GEN = {2'h0, j_max};	// src/main/scala/tile/tu3.scala:18:35, :22:24, :52:52
  wire [9:0] _io_tu_io_mm_rdaddr_8_T = io_tu_io_ls1_rdaddr_2_0 * _GEN;	// src/main/scala/tile/tu3.scala:52:52
  wire [9:0] _GEN_0 = {8'h0, i_cnt};	// src/main/scala/tile/tu3.scala:22:24, :52:44, :72:36
  reg  [7:0] mempot_biased_0;	// src/main/scala/tile/tu3.scala:124:28
  reg  [7:0] mempot_biased_1;	// src/main/scala/tile/tu3.scala:124:28
  reg  [7:0] mempot_biased_2;	// src/main/scala/tile/tu3.scala:124:28
  reg  [7:0] mempot_biased_3;	// src/main/scala/tile/tu3.scala:124:28
  reg  [7:0] mempot_biased_4;	// src/main/scala/tile/tu3.scala:124:28
  reg  [7:0] mempot_biased_5;	// src/main/scala/tile/tu3.scala:124:28
  reg  [7:0] mempot_biased_6;	// src/main/scala/tile/tu3.scala:124:28
  reg  [7:0] mempot_biased_7;	// src/main/scala/tile/tu3.scala:124:28
  reg  [7:0] mempot_biased_8;	// src/main/scala/tile/tu3.scala:124:28
  reg        spike_out_0;	// src/main/scala/tile/tu3.scala:172:24
  reg        spike_out_1;	// src/main/scala/tile/tu3.scala:172:24
  reg        spike_out_2;	// src/main/scala/tile/tu3.scala:172:24
  reg        spike_out_3;	// src/main/scala/tile/tu3.scala:172:24
  reg        spike_out_4;	// src/main/scala/tile/tu3.scala:172:24
  reg        spike_out_5;	// src/main/scala/tile/tu3.scala:172:24
  reg        spike_out_6;	// src/main/scala/tile/tu3.scala:172:24
  reg        spike_out_7;	// src/main/scala/tile/tu3.scala:172:24
  reg        spike_out_8;	// src/main/scala/tile/tu3.scala:172:24
  reg        spike_or;	// src/main/scala/tile/tu3.scala:178:27
  wire [7:0] _GEN_1 = {6'h0, i_cnt_s3};	// src/main/scala/tile/tu3.scala:17:35, :26:27, :187:61
  wire [7:0] _GEN_2 = {6'h0, j_cnt_s3};	// src/main/scala/tile/tu3.scala:17:35, :27:27, :187:85
  wire       _io_tu_io_ao_wrdata_T_2 = _GEN_1 == i_max & _GEN_2 == j_max;	// src/main/scala/tile/tu3.scala:17:35, :18:35, :187:{61,72,85}
  wire [9:0] io_tu_io_ao_wraddr_8_0 =
    io_tu_io_maxpool_en
      ? {8'h0, i_cnt_s3} + _GEN * {8'h0, j_cnt_s3}
      : {2'h0, addr_write_s3};	// src/main/scala/tile/tu3.scala:22:24, :25:32, :26:27, :27:27, :52:52, :72:36, :183:31, :186:{44,56,64}, :192:35
  wire       _io_tu_io_ao_wrdata_8_T = _GEN_1 == i_max;	// src/main/scala/tile/tu3.scala:17:35, :187:61, :193:52
  wire       _io_tu_io_ao_wrdata_8_T_1 = _GEN_2 == j_max;	// src/main/scala/tile/tu3.scala:18:35, :187:85, :193:76
  always @(posedge clock) begin	// src/main/scala/tile/tu3.scala:10:7
    automatic logic       isNorth;	// src/main/scala/tile/tu3.scala:39:23
    automatic logic       isSouth;	// src/main/scala/tile/tu3.scala:40:23
    automatic logic [7:0] _GEN_3;	// src/main/scala/tile/tu3.scala:45:25
    automatic logic       _j_cnt_T;	// src/main/scala/tile/tu3.scala:45:25
    automatic logic       _GEN_4;	// src/main/scala/tile/tu3.scala:50:29
    isNorth = i_cnt == 2'h0;	// src/main/scala/tile/tu3.scala:22:24, :39:23
    isSouth = {6'h0, i_cnt} == i_max;	// src/main/scala/tile/tu3.scala:17:35, :22:24, :40:23
    _GEN_3 = {6'h0, j_cnt};	// src/main/scala/tile/tu3.scala:17:35, :23:24, :45:25
    _j_cnt_T = _GEN_3 <= j_max;	// src/main/scala/tile/tu3.scala:18:35, :45:25
    _GEN_4 = io_tu_io_thresh_en & _j_cnt_T;	// src/main/scala/tile/tu3.scala:45:25, :50:29
    if (reset) begin	// src/main/scala/tile/tu3.scala:10:7
      i_cnt <= 2'h0;	// src/main/scala/tile/tu3.scala:22:24
      j_cnt <= 2'h0;	// src/main/scala/tile/tu3.scala:22:24, :23:24
      spike_or <= 1'h0;	// src/main/scala/tile/tu3.scala:34:40, :178:27
    end
    else begin	// src/main/scala/tile/tu3.scala:10:7
      if (_GEN_4)	// src/main/scala/tile/tu3.scala:50:29
        i_cnt <= i_cnt + 2'h1;	// src/main/scala/tile/tu3.scala:22:24, :76:24, :143:27
      if (_j_cnt_T & isSouth)	// src/main/scala/tile/tu3.scala:40:23, :45:{25,35}
        j_cnt <= j_cnt + 2'h1;	// src/main/scala/tile/tu3.scala:23:24, :45:63, :143:27
      spike_or <=
        spike_out_0 | spike_out_1 | spike_out_2 | spike_out_3 | spike_out_4 | spike_out_5
        | spike_out_6 | spike_out_7 | spike_out_8;	// src/main/scala/tile/tu3.scala:172:24, :178:27, :179:36
    end
    addr_write <= {4'h0, i_cnt, j_cnt};	// src/main/scala/tile/tu3.scala:10:7, :22:24, :23:24, :24:25, :29:16
    addr_write_s3_REG <= addr_write;	// src/main/scala/tile/tu3.scala:24:25, :25:40
    addr_write_s3 <= addr_write_s3_REG;	// src/main/scala/tile/tu3.scala:25:{32,40}
    i_cnt_s3_REG <= i_cnt;	// src/main/scala/tile/tu3.scala:22:24, :26:35
    i_cnt_s3 <= i_cnt_s3_REG;	// src/main/scala/tile/tu3.scala:26:{27,35}
    j_cnt_s3_REG <= j_cnt;	// src/main/scala/tile/tu3.scala:23:24, :27:35
    j_cnt_s3 <= j_cnt_s3_REG;	// src/main/scala/tile/tu3.scala:27:{27,35}
    mempot_rd_main_0 <= _GEN_4 ? io_tu_io_mm_rddata_0 : 8'h0;	// src/main/scala/tile/tu3.scala:31:29, :50:{29,50}, :53:31, :72:36, :80:31
    mempot_rd_main_1 <= _GEN_4 ? io_tu_io_mm_rddata_1 : 8'h0;	// src/main/scala/tile/tu3.scala:31:29, :50:{29,50}, :53:31, :72:36, :80:31
    mempot_rd_main_2 <= _GEN_4 ? io_tu_io_mm_rddata_2 : 8'h0;	// src/main/scala/tile/tu3.scala:31:29, :50:{29,50}, :53:31, :72:36, :80:31
    mempot_rd_main_3 <= _GEN_4 ? io_tu_io_mm_rddata_3 : 8'h0;	// src/main/scala/tile/tu3.scala:31:29, :50:{29,50}, :53:31, :72:36, :80:31
    mempot_rd_main_4 <= _GEN_4 ? io_tu_io_mm_rddata_4 : 8'h0;	// src/main/scala/tile/tu3.scala:31:29, :50:{29,50}, :53:31, :72:36, :80:31
    mempot_rd_main_5 <= _GEN_4 ? io_tu_io_mm_rddata_5 : 8'h0;	// src/main/scala/tile/tu3.scala:31:29, :50:{29,50}, :53:31, :72:36, :80:31
    mempot_rd_main_6 <= _GEN_4 ? io_tu_io_mm_rddata_6 : 8'h0;	// src/main/scala/tile/tu3.scala:31:29, :50:{29,50}, :53:31, :72:36, :80:31
    mempot_rd_main_7 <= _GEN_4 ? io_tu_io_mm_rddata_7 : 8'h0;	// src/main/scala/tile/tu3.scala:31:29, :50:{29,50}, :53:31, :72:36, :80:31
    mempot_rd_main_8 <= _GEN_4 ? io_tu_io_mm_rddata_8 : 8'h0;	// src/main/scala/tile/tu3.scala:31:29, :50:{29,50}, :53:31, :72:36, :80:31
    mempot_rd_local_0 <=
      _GEN_4
        ? (isNorth ? io_tu_io_ln1_rddata_0 : isSouth ? io_tu_io_ls1_rddata_0 : 8'h0)
        : 8'h0;	// src/main/scala/tile/tu3.scala:32:30, :39:23, :40:23, :50:{29,50}, :56:23, :61:36, :63:28, :68:36, :72:36, :83:32
    mempot_rd_local_1 <=
      _GEN_4
        ? (isNorth ? io_tu_io_ln1_rddata_1 : isSouth ? io_tu_io_ls1_rddata_1 : 8'h0)
        : 8'h0;	// src/main/scala/tile/tu3.scala:32:30, :39:23, :40:23, :50:{29,50}, :56:23, :61:36, :63:28, :68:36, :72:36, :83:32
    mempot_rd_local_2 <=
      _GEN_4
        ? (isNorth ? io_tu_io_ln1_rddata_2 : isSouth ? io_tu_io_ls1_rddata_2 : 8'h0)
        : 8'h0;	// src/main/scala/tile/tu3.scala:32:30, :39:23, :40:23, :50:{29,50}, :56:23, :61:36, :63:28, :68:36, :72:36, :83:32
    isNorth_s2 <= isNorth;	// src/main/scala/tile/tu3.scala:39:23, :42:29
    isSouth_s2 <= isSouth;	// src/main/scala/tile/tu3.scala:40:23, :43:29
    io_tu_io_thresh_done_REG <= isSouth & _GEN_3 == j_max;	// src/main/scala/tile/tu3.scala:18:35, :40:23, :45:25, :47:{60,77,86}
    io_tu_io_thresh_done_REG_1 <= io_tu_io_thresh_done_REG;	// src/main/scala/tile/tu3.scala:47:{52,60}
    io_tu_io_thresh_done_REG_2 <= io_tu_io_thresh_done_REG_1;	// src/main/scala/tile/tu3.scala:47:{44,52}
    io_tu_io_thresh_done_REG_3 <= io_tu_io_thresh_done_REG_2;	// src/main/scala/tile/tu3.scala:47:{36,44}
    if (isNorth_s2) begin	// src/main/scala/tile/tu3.scala:42:29
      mempot_biased_0 <= mempot_rd_main_0 + mempot_rd_local_0 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :128:72
      mempot_biased_1 <= mempot_rd_main_1 + mempot_rd_local_1 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :128:72
      mempot_biased_2 <= mempot_rd_main_2 + mempot_rd_local_2 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :128:72
      mempot_biased_3 <= mempot_rd_main_3 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :124:28, :132:51
      mempot_biased_4 <= mempot_rd_main_4 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :124:28, :132:51
      mempot_biased_5 <= mempot_rd_main_5 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :124:28, :132:51
      mempot_biased_6 <= mempot_rd_main_6 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :124:28, :132:51
      mempot_biased_7 <= mempot_rd_main_7 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :124:28, :132:51
      mempot_biased_8 <= mempot_rd_main_8 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :124:28, :132:51
    end
    else if (isSouth_s2) begin	// src/main/scala/tile/tu3.scala:43:29
      automatic logic [7:0] se_col = _se_col_T % 8'h3;	// src/main/scala/tile/tu3.scala:17:35, :18:29, :19:37
      automatic logic       _GEN_5 = se_col[1:0] == 2'h0;	// src/main/scala/tile/tu3.scala:19:37, :22:24, :135:21
      automatic logic       _GEN_6 = se_col[1:0] == 2'h1;	// src/main/scala/tile/tu3.scala:19:37, :143:27
      mempot_biased_0 <=
        _GEN_5
          ? mempot_rd_main_0 + mempot_rd_local_0 + io_tu_io_bias
          : _GEN_6 ? mempot_rd_main_0 + io_tu_io_bias : mempot_rd_main_0 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :135:{21,29}, :137:{34,76}, :143:{27,35}, :145:{34,55}, :157:{34,55}
      mempot_biased_1 <=
        _GEN_5
          ? mempot_rd_main_1 + mempot_rd_local_1 + io_tu_io_bias
          : _GEN_6 ? mempot_rd_main_1 + io_tu_io_bias : mempot_rd_main_1 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :135:{21,29}, :137:{34,76}, :143:{27,35}, :145:{34,55}, :157:{34,55}
      mempot_biased_2 <=
        _GEN_5
          ? mempot_rd_main_2 + mempot_rd_local_2 + io_tu_io_bias
          : _GEN_6 ? mempot_rd_main_2 + io_tu_io_bias : mempot_rd_main_2 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :135:{21,29}, :137:{34,76}, :143:{27,35}, :145:{34,55}, :157:{34,55}
      mempot_biased_3 <=
        _GEN_5
          ? mempot_rd_main_3 + io_tu_io_bias
          : _GEN_6
              ? mempot_rd_main_3 + mempot_rd_local_0 + io_tu_io_bias
              : mempot_rd_main_3 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :135:{21,29}, :141:{34,55}, :143:{27,35}, :149:{34,80}, :161:{34,55}
      mempot_biased_4 <=
        _GEN_5
          ? mempot_rd_main_4 + io_tu_io_bias
          : _GEN_6
              ? mempot_rd_main_4 + mempot_rd_local_1 + io_tu_io_bias
              : mempot_rd_main_4 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :135:{21,29}, :141:{34,55}, :143:{27,35}, :149:{34,80}, :161:{34,55}
      mempot_biased_5 <=
        _GEN_5
          ? mempot_rd_main_5 + io_tu_io_bias
          : _GEN_6
              ? mempot_rd_main_5 + mempot_rd_local_2 + io_tu_io_bias
              : mempot_rd_main_5 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :135:{21,29}, :141:{34,55}, :143:{27,35}, :149:{34,80}, :161:{34,55}
      mempot_biased_6 <=
        _GEN_5
          ? mempot_rd_main_6 + io_tu_io_bias
          : _GEN_6
              ? mempot_rd_main_6 + io_tu_io_bias
              : mempot_rd_main_6 + mempot_rd_local_0 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :135:{21,29}, :141:{34,55}, :143:{27,35}, :153:{34,55}, :165:{34,80}
      mempot_biased_7 <=
        _GEN_5
          ? mempot_rd_main_7 + io_tu_io_bias
          : _GEN_6
              ? mempot_rd_main_7 + io_tu_io_bias
              : mempot_rd_main_7 + mempot_rd_local_1 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :135:{21,29}, :141:{34,55}, :143:{27,35}, :153:{34,55}, :165:{34,80}
      mempot_biased_8 <=
        _GEN_5
          ? mempot_rd_main_8 + io_tu_io_bias
          : _GEN_6
              ? mempot_rd_main_8 + io_tu_io_bias
              : mempot_rd_main_8 + mempot_rd_local_2 + io_tu_io_bias;	// src/main/scala/tile/tu3.scala:31:29, :32:30, :124:28, :135:{21,29}, :141:{34,55}, :143:{27,35}, :153:{34,55}, :165:{34,80}
    end
    spike_out_0 <= mempot_biased_0 >= io_tu_io_v_t;	// src/main/scala/tile/tu3.scala:124:28, :172:24, :175:46
    spike_out_1 <= mempot_biased_1 >= io_tu_io_v_t;	// src/main/scala/tile/tu3.scala:124:28, :172:24, :175:46
    spike_out_2 <= mempot_biased_2 >= io_tu_io_v_t;	// src/main/scala/tile/tu3.scala:124:28, :172:24, :175:46
    spike_out_3 <= mempot_biased_3 >= io_tu_io_v_t;	// src/main/scala/tile/tu3.scala:124:28, :172:24, :175:46
    spike_out_4 <= mempot_biased_4 >= io_tu_io_v_t;	// src/main/scala/tile/tu3.scala:124:28, :172:24, :175:46
    spike_out_5 <= mempot_biased_5 >= io_tu_io_v_t;	// src/main/scala/tile/tu3.scala:124:28, :172:24, :175:46
    spike_out_6 <= mempot_biased_6 >= io_tu_io_v_t;	// src/main/scala/tile/tu3.scala:124:28, :172:24, :175:46
    spike_out_7 <= mempot_biased_7 >= io_tu_io_v_t;	// src/main/scala/tile/tu3.scala:124:28, :172:24, :175:46
    spike_out_8 <= mempot_biased_8 >= io_tu_io_v_t;	// src/main/scala/tile/tu3.scala:124:28, :172:24, :175:46
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/tile/tu3.scala:10:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/tile/tu3.scala:10:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/tile/tu3.scala:10:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/tile/tu3.scala:10:7
      automatic logic [31:0] _RANDOM[0:7];	// src/main/scala/tile/tu3.scala:10:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/tile/tu3.scala:10:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/tile/tu3.scala:10:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/tile/tu3.scala:10:7
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;	// src/main/scala/tile/tu3.scala:10:7
        end	// src/main/scala/tile/tu3.scala:10:7
        i_cnt = _RANDOM[3'h0][1:0];	// src/main/scala/tile/tu3.scala:10:7, :22:24
        j_cnt = _RANDOM[3'h0][3:2];	// src/main/scala/tile/tu3.scala:10:7, :22:24, :23:24
        addr_write = _RANDOM[3'h0][11:4];	// src/main/scala/tile/tu3.scala:10:7, :22:24, :24:25
        addr_write_s3_REG = _RANDOM[3'h0][19:12];	// src/main/scala/tile/tu3.scala:10:7, :22:24, :25:40
        addr_write_s3 = _RANDOM[3'h0][27:20];	// src/main/scala/tile/tu3.scala:10:7, :22:24, :25:32
        i_cnt_s3_REG = _RANDOM[3'h0][29:28];	// src/main/scala/tile/tu3.scala:10:7, :22:24, :26:35
        i_cnt_s3 = _RANDOM[3'h0][31:30];	// src/main/scala/tile/tu3.scala:10:7, :22:24, :26:27
        j_cnt_s3_REG = _RANDOM[3'h1][1:0];	// src/main/scala/tile/tu3.scala:10:7, :27:35
        j_cnt_s3 = _RANDOM[3'h1][3:2];	// src/main/scala/tile/tu3.scala:10:7, :27:{27,35}
        mempot_rd_main_0 = _RANDOM[3'h1][11:4];	// src/main/scala/tile/tu3.scala:10:7, :27:35, :31:29
        mempot_rd_main_1 = _RANDOM[3'h1][19:12];	// src/main/scala/tile/tu3.scala:10:7, :27:35, :31:29
        mempot_rd_main_2 = _RANDOM[3'h1][27:20];	// src/main/scala/tile/tu3.scala:10:7, :27:35, :31:29
        mempot_rd_main_3 = {_RANDOM[3'h1][31:28], _RANDOM[3'h2][3:0]};	// src/main/scala/tile/tu3.scala:10:7, :27:35, :31:29
        mempot_rd_main_4 = _RANDOM[3'h2][11:4];	// src/main/scala/tile/tu3.scala:10:7, :31:29
        mempot_rd_main_5 = _RANDOM[3'h2][19:12];	// src/main/scala/tile/tu3.scala:10:7, :31:29
        mempot_rd_main_6 = _RANDOM[3'h2][27:20];	// src/main/scala/tile/tu3.scala:10:7, :31:29
        mempot_rd_main_7 = {_RANDOM[3'h2][31:28], _RANDOM[3'h3][3:0]};	// src/main/scala/tile/tu3.scala:10:7, :31:29
        mempot_rd_main_8 = _RANDOM[3'h3][11:4];	// src/main/scala/tile/tu3.scala:10:7, :31:29
        mempot_rd_local_0 = _RANDOM[3'h3][19:12];	// src/main/scala/tile/tu3.scala:10:7, :31:29, :32:30
        mempot_rd_local_1 = _RANDOM[3'h3][27:20];	// src/main/scala/tile/tu3.scala:10:7, :31:29, :32:30
        mempot_rd_local_2 = {_RANDOM[3'h3][31:28], _RANDOM[3'h4][3:0]};	// src/main/scala/tile/tu3.scala:10:7, :31:29, :32:30
        isNorth_s2 = _RANDOM[3'h4][5];	// src/main/scala/tile/tu3.scala:10:7, :32:30, :42:29
        isSouth_s2 = _RANDOM[3'h4][6];	// src/main/scala/tile/tu3.scala:10:7, :32:30, :43:29
        io_tu_io_thresh_done_REG = _RANDOM[3'h4][7];	// src/main/scala/tile/tu3.scala:10:7, :32:30, :47:60
        io_tu_io_thresh_done_REG_1 = _RANDOM[3'h4][8];	// src/main/scala/tile/tu3.scala:10:7, :32:30, :47:52
        io_tu_io_thresh_done_REG_2 = _RANDOM[3'h4][9];	// src/main/scala/tile/tu3.scala:10:7, :32:30, :47:44
        io_tu_io_thresh_done_REG_3 = _RANDOM[3'h4][10];	// src/main/scala/tile/tu3.scala:10:7, :32:30, :47:36
        mempot_biased_0 = _RANDOM[3'h5][7:0];	// src/main/scala/tile/tu3.scala:10:7, :124:28
        mempot_biased_1 = _RANDOM[3'h5][15:8];	// src/main/scala/tile/tu3.scala:10:7, :124:28
        mempot_biased_2 = _RANDOM[3'h5][23:16];	// src/main/scala/tile/tu3.scala:10:7, :124:28
        mempot_biased_3 = _RANDOM[3'h5][31:24];	// src/main/scala/tile/tu3.scala:10:7, :124:28
        mempot_biased_4 = _RANDOM[3'h6][7:0];	// src/main/scala/tile/tu3.scala:10:7, :124:28
        mempot_biased_5 = _RANDOM[3'h6][15:8];	// src/main/scala/tile/tu3.scala:10:7, :124:28
        mempot_biased_6 = _RANDOM[3'h6][23:16];	// src/main/scala/tile/tu3.scala:10:7, :124:28
        mempot_biased_7 = _RANDOM[3'h6][31:24];	// src/main/scala/tile/tu3.scala:10:7, :124:28
        mempot_biased_8 = _RANDOM[3'h7][7:0];	// src/main/scala/tile/tu3.scala:10:7, :124:28
        spike_out_0 = _RANDOM[3'h7][8];	// src/main/scala/tile/tu3.scala:10:7, :124:28, :172:24
        spike_out_1 = _RANDOM[3'h7][9];	// src/main/scala/tile/tu3.scala:10:7, :124:28, :172:24
        spike_out_2 = _RANDOM[3'h7][10];	// src/main/scala/tile/tu3.scala:10:7, :124:28, :172:24
        spike_out_3 = _RANDOM[3'h7][11];	// src/main/scala/tile/tu3.scala:10:7, :124:28, :172:24
        spike_out_4 = _RANDOM[3'h7][12];	// src/main/scala/tile/tu3.scala:10:7, :124:28, :172:24
        spike_out_5 = _RANDOM[3'h7][13];	// src/main/scala/tile/tu3.scala:10:7, :124:28, :172:24
        spike_out_6 = _RANDOM[3'h7][14];	// src/main/scala/tile/tu3.scala:10:7, :124:28, :172:24
        spike_out_7 = _RANDOM[3'h7][15];	// src/main/scala/tile/tu3.scala:10:7, :124:28, :172:24
        spike_out_8 = _RANDOM[3'h7][16];	// src/main/scala/tile/tu3.scala:10:7, :124:28, :172:24
        spike_or = _RANDOM[3'h7][17];	// src/main/scala/tile/tu3.scala:10:7, :124:28, :178:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/tile/tu3.scala:10:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/tile/tu3.scala:10:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_tu_io_mm_rdaddr_0 = _GEN_0 + _io_tu_io_mm_rdaddr_8_T;	// src/main/scala/tile/tu3.scala:10:7, :52:{44,52}
  assign io_tu_io_mm_rdaddr_1 = _GEN_0 + _io_tu_io_mm_rdaddr_8_T;	// src/main/scala/tile/tu3.scala:10:7, :52:{44,52}
  assign io_tu_io_mm_rdaddr_2 = _GEN_0 + _io_tu_io_mm_rdaddr_8_T;	// src/main/scala/tile/tu3.scala:10:7, :52:{44,52}
  assign io_tu_io_mm_rdaddr_3 = _GEN_0 + _io_tu_io_mm_rdaddr_8_T;	// src/main/scala/tile/tu3.scala:10:7, :52:{44,52}
  assign io_tu_io_mm_rdaddr_4 = _GEN_0 + _io_tu_io_mm_rdaddr_8_T;	// src/main/scala/tile/tu3.scala:10:7, :52:{44,52}
  assign io_tu_io_mm_rdaddr_5 = _GEN_0 + _io_tu_io_mm_rdaddr_8_T;	// src/main/scala/tile/tu3.scala:10:7, :52:{44,52}
  assign io_tu_io_mm_rdaddr_6 = _GEN_0 + _io_tu_io_mm_rdaddr_8_T;	// src/main/scala/tile/tu3.scala:10:7, :52:{44,52}
  assign io_tu_io_mm_rdaddr_7 = _GEN_0 + _io_tu_io_mm_rdaddr_8_T;	// src/main/scala/tile/tu3.scala:10:7, :52:{44,52}
  assign io_tu_io_mm_rdaddr_8 = _GEN_0 + _io_tu_io_mm_rdaddr_8_T;	// src/main/scala/tile/tu3.scala:10:7, :52:{44,52}
  assign io_tu_io_ln1_rdaddr_0 = io_tu_io_ls1_rdaddr_2_0;	// src/main/scala/tile/tu3.scala:10:7, :52:52
  assign io_tu_io_ln1_rdaddr_1 = io_tu_io_ls1_rdaddr_2_0;	// src/main/scala/tile/tu3.scala:10:7, :52:52
  assign io_tu_io_ln1_rdaddr_2 = io_tu_io_ls1_rdaddr_2_0;	// src/main/scala/tile/tu3.scala:10:7, :52:52
  assign io_tu_io_ls1_rdaddr_0 = io_tu_io_ls1_rdaddr_2_0;	// src/main/scala/tile/tu3.scala:10:7, :52:52
  assign io_tu_io_ls1_rdaddr_1 = io_tu_io_ls1_rdaddr_2_0;	// src/main/scala/tile/tu3.scala:10:7, :52:52
  assign io_tu_io_ls1_rdaddr_2 = io_tu_io_ls1_rdaddr_2_0;	// src/main/scala/tile/tu3.scala:10:7, :52:52
  assign io_tu_io_ao_wraddr_0 = io_tu_io_ao_wraddr_8_0;	// src/main/scala/tile/tu3.scala:10:7, :183:31, :186:44, :192:35
  assign io_tu_io_ao_wraddr_1 = io_tu_io_ao_wraddr_8_0;	// src/main/scala/tile/tu3.scala:10:7, :183:31, :186:44, :192:35
  assign io_tu_io_ao_wraddr_2 = io_tu_io_ao_wraddr_8_0;	// src/main/scala/tile/tu3.scala:10:7, :183:31, :186:44, :192:35
  assign io_tu_io_ao_wraddr_3 = io_tu_io_ao_wraddr_8_0;	// src/main/scala/tile/tu3.scala:10:7, :183:31, :186:44, :192:35
  assign io_tu_io_ao_wraddr_4 = io_tu_io_ao_wraddr_8_0;	// src/main/scala/tile/tu3.scala:10:7, :183:31, :186:44, :192:35
  assign io_tu_io_ao_wraddr_5 = io_tu_io_ao_wraddr_8_0;	// src/main/scala/tile/tu3.scala:10:7, :183:31, :186:44, :192:35
  assign io_tu_io_ao_wraddr_6 = io_tu_io_ao_wraddr_8_0;	// src/main/scala/tile/tu3.scala:10:7, :183:31, :186:44, :192:35
  assign io_tu_io_ao_wraddr_7 = io_tu_io_ao_wraddr_8_0;	// src/main/scala/tile/tu3.scala:10:7, :183:31, :186:44, :192:35
  assign io_tu_io_ao_wraddr_8 = io_tu_io_ao_wraddr_8_0;	// src/main/scala/tile/tu3.scala:10:7, :183:31, :186:44, :192:35
  assign io_tu_io_ao_wrdata_0 =
    {io_tu_io_maxpool_en
       ? _io_tu_io_ao_wrdata_T_2
       : _io_tu_io_ao_wrdata_8_T & _io_tu_io_ao_wrdata_8_T_1,
     addr_write_s3,
     1'h1};	// src/main/scala/tile/tu3.scala:10:7, :17:29, :25:32, :183:31, :187:{44,50,72}, :193:{35,41,52,63,76}
  assign io_tu_io_ao_wrdata_1 =
    {io_tu_io_maxpool_en
       ? _io_tu_io_ao_wrdata_T_2
       : _io_tu_io_ao_wrdata_8_T & _io_tu_io_ao_wrdata_8_T_1,
     addr_write_s3,
     1'h1};	// src/main/scala/tile/tu3.scala:10:7, :17:29, :25:32, :183:31, :187:{44,50,72}, :193:{35,41,52,63,76}
  assign io_tu_io_ao_wrdata_2 =
    {io_tu_io_maxpool_en
       ? _io_tu_io_ao_wrdata_T_2
       : _io_tu_io_ao_wrdata_8_T & _io_tu_io_ao_wrdata_8_T_1,
     addr_write_s3,
     1'h1};	// src/main/scala/tile/tu3.scala:10:7, :17:29, :25:32, :183:31, :187:{44,50,72}, :193:{35,41,52,63,76}
  assign io_tu_io_ao_wrdata_3 =
    {io_tu_io_maxpool_en
       ? _io_tu_io_ao_wrdata_T_2
       : _io_tu_io_ao_wrdata_8_T & _io_tu_io_ao_wrdata_8_T_1,
     addr_write_s3,
     1'h1};	// src/main/scala/tile/tu3.scala:10:7, :17:29, :25:32, :183:31, :187:{44,50,72}, :193:{35,41,52,63,76}
  assign io_tu_io_ao_wrdata_4 =
    {io_tu_io_maxpool_en
       ? _io_tu_io_ao_wrdata_T_2
       : _io_tu_io_ao_wrdata_8_T & _io_tu_io_ao_wrdata_8_T_1,
     addr_write_s3,
     1'h1};	// src/main/scala/tile/tu3.scala:10:7, :17:29, :25:32, :183:31, :187:{44,50,72}, :193:{35,41,52,63,76}
  assign io_tu_io_ao_wrdata_5 =
    {io_tu_io_maxpool_en
       ? _io_tu_io_ao_wrdata_T_2
       : _io_tu_io_ao_wrdata_8_T & _io_tu_io_ao_wrdata_8_T_1,
     addr_write_s3,
     1'h1};	// src/main/scala/tile/tu3.scala:10:7, :17:29, :25:32, :183:31, :187:{44,50,72}, :193:{35,41,52,63,76}
  assign io_tu_io_ao_wrdata_6 =
    {io_tu_io_maxpool_en
       ? _io_tu_io_ao_wrdata_T_2
       : _io_tu_io_ao_wrdata_8_T & _io_tu_io_ao_wrdata_8_T_1,
     addr_write_s3,
     1'h1};	// src/main/scala/tile/tu3.scala:10:7, :17:29, :25:32, :183:31, :187:{44,50,72}, :193:{35,41,52,63,76}
  assign io_tu_io_ao_wrdata_7 =
    {io_tu_io_maxpool_en
       ? _io_tu_io_ao_wrdata_T_2
       : _io_tu_io_ao_wrdata_8_T & _io_tu_io_ao_wrdata_8_T_1,
     addr_write_s3,
     1'h1};	// src/main/scala/tile/tu3.scala:10:7, :17:29, :25:32, :183:31, :187:{44,50,72}, :193:{35,41,52,63,76}
  assign io_tu_io_ao_wrdata_8 =
    {io_tu_io_maxpool_en
       ? _io_tu_io_ao_wrdata_T_2
       : _io_tu_io_ao_wrdata_8_T & _io_tu_io_ao_wrdata_8_T_1,
     addr_write_s3,
     1'h1};	// src/main/scala/tile/tu3.scala:10:7, :17:29, :25:32, :183:31, :187:{44,50,72}, :193:{35,41,52,63,76}
  assign io_tu_io_ao_we_0 = io_tu_io_maxpool_en ? spike_or : spike_out_0;	// src/main/scala/tile/tu3.scala:10:7, :172:24, :178:27, :183:31, :185:40, :191:31
  assign io_tu_io_ao_we_1 = io_tu_io_maxpool_en ? spike_or : spike_out_1;	// src/main/scala/tile/tu3.scala:10:7, :172:24, :178:27, :183:31, :185:40, :191:31
  assign io_tu_io_ao_we_2 = io_tu_io_maxpool_en ? spike_or : spike_out_2;	// src/main/scala/tile/tu3.scala:10:7, :172:24, :178:27, :183:31, :185:40, :191:31
  assign io_tu_io_ao_we_3 = io_tu_io_maxpool_en ? spike_or : spike_out_3;	// src/main/scala/tile/tu3.scala:10:7, :172:24, :178:27, :183:31, :185:40, :191:31
  assign io_tu_io_ao_we_4 = io_tu_io_maxpool_en ? spike_or : spike_out_4;	// src/main/scala/tile/tu3.scala:10:7, :172:24, :178:27, :183:31, :185:40, :191:31
  assign io_tu_io_ao_we_5 = io_tu_io_maxpool_en ? spike_or : spike_out_5;	// src/main/scala/tile/tu3.scala:10:7, :172:24, :178:27, :183:31, :185:40, :191:31
  assign io_tu_io_ao_we_6 = io_tu_io_maxpool_en ? spike_or : spike_out_6;	// src/main/scala/tile/tu3.scala:10:7, :172:24, :178:27, :183:31, :185:40, :191:31
  assign io_tu_io_ao_we_7 = io_tu_io_maxpool_en ? spike_or : spike_out_7;	// src/main/scala/tile/tu3.scala:10:7, :172:24, :178:27, :183:31, :185:40, :191:31
  assign io_tu_io_ao_we_8 = io_tu_io_maxpool_en ? spike_or : spike_out_8;	// src/main/scala/tile/tu3.scala:10:7, :172:24, :178:27, :183:31, :185:40, :191:31
  assign io_tu_io_thresh_done = io_tu_io_thresh_done_REG_3;	// src/main/scala/tile/tu3.scala:10:7, :47:36
endmodule

