// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"

class Vtop__Syms;

class Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_wr_enable_aeq_0,0,0);
        VL_IN8(io_wr_enable_aeq_1,0,0);
        VL_IN8(io_wr_enable_aeq_2,0,0);
        VL_IN8(io_wr_enable_aeq_3,0,0);
        VL_IN8(io_wr_enable_aeq_4,0,0);
        VL_IN8(io_wr_enable_aeq_5,0,0);
        VL_IN8(io_wr_enable_aeq_6,0,0);
        VL_IN8(io_wr_enable_aeq_7,0,0);
        VL_IN8(io_wr_enable_aeq_8,0,0);
        VL_IN8(io_rd_enable_aeq,0,0);
        VL_IN8(io_wr_enable_mempot_0,0,0);
        VL_IN8(io_wr_enable_mempot_1,0,0);
        VL_IN8(io_wr_enable_mempot_2,0,0);
        VL_IN8(io_wr_enable_mempot_3,0,0);
        VL_IN8(io_wr_enable_mempot_4,0,0);
        VL_IN8(io_wr_enable_mempot_5,0,0);
        VL_IN8(io_wr_enable_mempot_6,0,0);
        VL_IN8(io_wr_enable_mempot_7,0,0);
        VL_IN8(io_wr_enable_mempot_8,0,0);
        VL_IN8(io_rd_enable_mempot_0,0,0);
        VL_IN8(io_rd_enable_mempot_1,0,0);
        VL_IN8(io_rd_enable_mempot_2,0,0);
        VL_IN8(io_rd_enable_mempot_3,0,0);
        VL_IN8(io_rd_enable_mempot_4,0,0);
        VL_IN8(io_rd_enable_mempot_5,0,0);
        VL_IN8(io_rd_enable_mempot_6,0,0);
        VL_IN8(io_rd_enable_mempot_7,0,0);
        VL_IN8(io_rd_enable_mempot_8,0,0);
        VL_IN8(io_addr_r_mempot_0,7,0);
        VL_IN8(io_addr_r_mempot_1,7,0);
        VL_IN8(io_addr_r_mempot_2,7,0);
        VL_IN8(io_addr_r_mempot_3,7,0);
        VL_IN8(io_addr_r_mempot_4,7,0);
        VL_IN8(io_addr_r_mempot_5,7,0);
        VL_IN8(io_addr_r_mempot_6,7,0);
        VL_IN8(io_addr_r_mempot_7,7,0);
        VL_IN8(io_addr_r_mempot_8,7,0);
        VL_IN8(io_addr_w_mempot_0,7,0);
        VL_IN8(io_addr_w_mempot_1,7,0);
        VL_IN8(io_addr_w_mempot_2,7,0);
        VL_IN8(io_addr_w_mempot_3,7,0);
        VL_IN8(io_addr_w_mempot_4,7,0);
        VL_IN8(io_addr_w_mempot_5,7,0);
        VL_IN8(io_addr_w_mempot_6,7,0);
        VL_IN8(io_addr_w_mempot_7,7,0);
        VL_IN8(io_addr_w_mempot_8,7,0);
        VL_IN8(io_bias_0,7,0);
        VL_IN8(io_bias_1,7,0);
        VL_IN8(io_bias_2,7,0);
        VL_IN8(io_bias_3,7,0);
        VL_IN8(io_bias_4,7,0);
        VL_IN8(io_bias_5,7,0);
        VL_IN8(io_bias_6,7,0);
        VL_IN8(io_bias_7,7,0);
        VL_IN8(io_bias_8,7,0);
        VL_IN8(io_V_t,7,0);
        VL_IN8(io_thresh_enab,0,0);
        VL_IN8(io_conv_enab,0,0);
        VL_IN8(io_kernel_0,7,0);
        VL_IN8(io_kernel_1,7,0);
        VL_IN8(io_kernel_2,7,0);
        VL_IN8(io_kernel_3,7,0);
    };
    struct {
        VL_IN8(io_kernel_4,7,0);
        VL_IN8(io_kernel_5,7,0);
        VL_IN8(io_kernel_6,7,0);
        VL_IN8(io_kernel_7,7,0);
        VL_IN8(io_kernel_8,7,0);
        CData/*0:0*/ pe__DOT__clock;
        CData/*0:0*/ pe__DOT__reset;
        CData/*0:0*/ pe__DOT__io_wr_enable_aeq_0;
        CData/*0:0*/ pe__DOT__io_wr_enable_aeq_1;
        CData/*0:0*/ pe__DOT__io_wr_enable_aeq_2;
        CData/*0:0*/ pe__DOT__io_wr_enable_aeq_3;
        CData/*0:0*/ pe__DOT__io_wr_enable_aeq_4;
        CData/*0:0*/ pe__DOT__io_wr_enable_aeq_5;
        CData/*0:0*/ pe__DOT__io_wr_enable_aeq_6;
        CData/*0:0*/ pe__DOT__io_wr_enable_aeq_7;
        CData/*0:0*/ pe__DOT__io_wr_enable_aeq_8;
        CData/*0:0*/ pe__DOT__io_rd_enable_aeq;
        CData/*0:0*/ pe__DOT__io_wr_enable_mempot_0;
        CData/*0:0*/ pe__DOT__io_wr_enable_mempot_1;
        CData/*0:0*/ pe__DOT__io_wr_enable_mempot_2;
        CData/*0:0*/ pe__DOT__io_wr_enable_mempot_3;
        CData/*0:0*/ pe__DOT__io_wr_enable_mempot_4;
        CData/*0:0*/ pe__DOT__io_wr_enable_mempot_5;
        CData/*0:0*/ pe__DOT__io_wr_enable_mempot_6;
        CData/*0:0*/ pe__DOT__io_wr_enable_mempot_7;
        CData/*0:0*/ pe__DOT__io_wr_enable_mempot_8;
        CData/*0:0*/ pe__DOT__io_rd_enable_mempot_0;
        CData/*0:0*/ pe__DOT__io_rd_enable_mempot_1;
        CData/*0:0*/ pe__DOT__io_rd_enable_mempot_2;
        CData/*0:0*/ pe__DOT__io_rd_enable_mempot_3;
        CData/*0:0*/ pe__DOT__io_rd_enable_mempot_4;
        CData/*0:0*/ pe__DOT__io_rd_enable_mempot_5;
        CData/*0:0*/ pe__DOT__io_rd_enable_mempot_6;
        CData/*0:0*/ pe__DOT__io_rd_enable_mempot_7;
        CData/*0:0*/ pe__DOT__io_rd_enable_mempot_8;
        CData/*7:0*/ pe__DOT__io_addr_r_mempot_0;
        CData/*7:0*/ pe__DOT__io_addr_r_mempot_1;
        CData/*7:0*/ pe__DOT__io_addr_r_mempot_2;
        CData/*7:0*/ pe__DOT__io_addr_r_mempot_3;
        CData/*7:0*/ pe__DOT__io_addr_r_mempot_4;
        CData/*7:0*/ pe__DOT__io_addr_r_mempot_5;
        CData/*7:0*/ pe__DOT__io_addr_r_mempot_6;
        CData/*7:0*/ pe__DOT__io_addr_r_mempot_7;
        CData/*7:0*/ pe__DOT__io_addr_r_mempot_8;
        CData/*7:0*/ pe__DOT__io_addr_w_mempot_0;
        CData/*7:0*/ pe__DOT__io_addr_w_mempot_1;
        CData/*7:0*/ pe__DOT__io_addr_w_mempot_2;
        CData/*7:0*/ pe__DOT__io_addr_w_mempot_3;
        CData/*7:0*/ pe__DOT__io_addr_w_mempot_4;
        CData/*7:0*/ pe__DOT__io_addr_w_mempot_5;
        CData/*7:0*/ pe__DOT__io_addr_w_mempot_6;
        CData/*7:0*/ pe__DOT__io_addr_w_mempot_7;
        CData/*7:0*/ pe__DOT__io_addr_w_mempot_8;
        CData/*7:0*/ pe__DOT__io_bias_0;
        CData/*7:0*/ pe__DOT__io_bias_1;
        CData/*7:0*/ pe__DOT__io_bias_2;
        CData/*7:0*/ pe__DOT__io_bias_3;
        CData/*7:0*/ pe__DOT__io_bias_4;
        CData/*7:0*/ pe__DOT__io_bias_5;
        CData/*7:0*/ pe__DOT__io_bias_6;
        CData/*7:0*/ pe__DOT__io_bias_7;
        CData/*7:0*/ pe__DOT__io_bias_8;
        CData/*7:0*/ pe__DOT__io_V_t;
        CData/*0:0*/ pe__DOT__io_thresh_enab;
    };
    struct {
        CData/*0:0*/ pe__DOT__io_conv_enab;
        CData/*7:0*/ pe__DOT__io_kernel_0;
        CData/*7:0*/ pe__DOT__io_kernel_1;
        CData/*7:0*/ pe__DOT__io_kernel_2;
        CData/*7:0*/ pe__DOT__io_kernel_3;
        CData/*7:0*/ pe__DOT__io_kernel_4;
        CData/*7:0*/ pe__DOT__io_kernel_5;
        CData/*7:0*/ pe__DOT__io_kernel_6;
        CData/*7:0*/ pe__DOT__io_kernel_7;
        CData/*7:0*/ pe__DOT__io_kernel_8;
        CData/*0:0*/ pe__DOT__validS1;
        CData/*0:0*/ pe__DOT__validS2;
        CData/*0:0*/ pe__DOT__validS3;
        CData/*0:0*/ pe__DOT__validS4;
        CData/*0:0*/ pe__DOT__unnamedblk1__DOT___GEN;
        CData/*0:0*/ pe__DOT__unnamedblk1__DOT___GEN_0;
        CData/*0:0*/ pe__DOT__unnamedblk1__DOT___GEN_1;
        CData/*0:0*/ pe__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_2;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__clock;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__reset;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__io_writeEnable_0;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__io_writeEnable_1;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__io_writeEnable_2;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__io_writeEnable_3;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__io_writeEnable_4;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__io_writeEnable_5;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__io_writeEnable_6;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__io_writeEnable_7;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__io_writeEnable_8;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__io_readEnable;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__writeCounters_0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__writeCounters_1;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__writeCounters_2;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__writeCounters_3;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__writeCounters_4;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__writeCounters_5;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__writeCounters_6;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__writeCounters_7;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__writeCounters_8;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__readCounter;
        CData/*7:0*/ pe__DOT__aeqMem__DOT___GEN;
        CData/*7:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrAddr_8;
        CData/*7:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrAddr_7;
        CData/*7:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrAddr_6;
        CData/*7:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrAddr_5;
        CData/*7:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrAddr_4;
        CData/*7:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrAddr_3;
        CData/*7:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrAddr_2;
        CData/*7:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrAddr_1;
        CData/*7:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrAddr_0;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__clock;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdAddr_0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdAddr_1;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdAddr_2;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdAddr_3;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdAddr_4;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdAddr_5;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdAddr_6;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdAddr_7;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdAddr_8;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrAddr_0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrAddr_1;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrAddr_2;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrAddr_3;
    };
    struct {
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrAddr_4;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrAddr_5;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrAddr_6;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrAddr_7;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrAddr_8;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrEna_0;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrEna_1;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrEna_2;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrEna_3;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrEna_4;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrEna_5;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrEna_6;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrEna_7;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrEna_8;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdEna_0;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdEna_1;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdEna_2;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdEna_3;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdEna_4;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdEna_5;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdEna_6;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdEna_7;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdEna_8;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT__R0_addr;
    };
    struct {
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT___R0_addr_d0;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__clock;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_wr_enable_0;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_wr_enable_1;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_wr_enable_2;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_wr_enable_3;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_wr_enable_4;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_wr_enable_5;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_wr_enable_6;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_wr_enable_7;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_wr_enable_8;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_rd_enable_0;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_rd_enable_1;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_rd_enable_2;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_rd_enable_3;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_rd_enable_4;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_rd_enable_5;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_rd_enable_6;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_rd_enable_7;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__io_rd_enable_8;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_r_0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_r_1;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_r_2;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_r_3;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_r_4;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_r_5;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_r_6;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_r_7;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_r_8;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_w_0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_w_1;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_w_2;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_w_3;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_w_4;
    };
    struct {
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_w_5;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_w_6;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_w_7;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__io_addr_w_8;
        CData/*0:0*/ pe__DOT__mempotMem__DOT___GEN;
        CData/*0:0*/ pe__DOT__mempotMem__DOT___GEN_0;
        CData/*0:0*/ pe__DOT__mempotMem__DOT___GEN_1;
        CData/*0:0*/ pe__DOT__mempotMem__DOT___GEN_2;
        CData/*0:0*/ pe__DOT__mempotMem__DOT___GEN_3;
        CData/*0:0*/ pe__DOT__mempotMem__DOT___GEN_4;
        CData/*0:0*/ pe__DOT__mempotMem__DOT___GEN_5;
        CData/*0:0*/ pe__DOT__mempotMem__DOT___GEN_6;
        CData/*0:0*/ pe__DOT__mempotMem__DOT___GEN_7;
        CData/*0:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrEna_8;
        CData/*0:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrEna_7;
        CData/*0:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrEna_6;
        CData/*0:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrEna_5;
        CData/*0:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrEna_4;
        CData/*0:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrEna_3;
        CData/*0:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrEna_2;
        CData/*0:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrEna_1;
        CData/*0:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrEna_0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrAddr_8;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrAddr_7;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrAddr_6;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrAddr_5;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrAddr_4;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrAddr_3;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrAddr_2;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrAddr_1;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrAddr_0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_rdAddr_8;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_rdAddr_7;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_rdAddr_6;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_rdAddr_5;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_rdAddr_4;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_rdAddr_3;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_rdAddr_2;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_rdAddr_1;
        CData/*7:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_rdAddr_0;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__clock;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdAddr_0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdAddr_1;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdAddr_2;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdAddr_3;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdAddr_4;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdAddr_5;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdAddr_6;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdAddr_7;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdAddr_8;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrAddr_0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrAddr_1;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrAddr_2;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrAddr_3;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrAddr_4;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrAddr_5;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrAddr_6;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrAddr_7;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrAddr_8;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrEna_0;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrEna_1;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrEna_2;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrEna_3;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrEna_4;
    };
    struct {
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrEna_5;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrEna_6;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrEna_7;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrEna_8;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdEna_0;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdEna_1;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdEna_2;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdEna_3;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdEna_4;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdEna_5;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdEna_6;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdEna_7;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdEna_8;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT__R0_clk;
    };
    struct {
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT___R0_addr_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT__R0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT__R0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT__R0_clk;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT__W0_addr;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT__W0_en;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT__W0_clk;
        CData/*0:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT___R0_en_d0;
        CData/*7:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT___R0_addr_d0;
        CData/*0:0*/ __Vtrigrprev__TOP__clock;
        CData/*0:0*/ __VactContinue;
        VL_IN16(io_writeData_aeq_0,8,0);
        VL_IN16(io_writeData_aeq_1,8,0);
        VL_IN16(io_writeData_aeq_2,8,0);
        VL_IN16(io_writeData_aeq_3,8,0);
        VL_IN16(io_writeData_aeq_4,8,0);
        VL_IN16(io_writeData_aeq_5,8,0);
        VL_IN16(io_writeData_aeq_6,8,0);
        VL_IN16(io_writeData_aeq_7,8,0);
        VL_IN16(io_writeData_aeq_8,8,0);
        VL_OUT16(io_readData_aeq_0,8,0);
        VL_OUT16(io_readData_aeq_1,8,0);
        VL_OUT16(io_readData_aeq_2,8,0);
        VL_OUT16(io_readData_aeq_3,8,0);
        VL_OUT16(io_readData_aeq_4,8,0);
        VL_OUT16(io_readData_aeq_5,8,0);
        VL_OUT16(io_readData_aeq_6,8,0);
        VL_OUT16(io_readData_aeq_7,8,0);
        VL_OUT16(io_readData_aeq_8,8,0);
        VL_IN16(io_din_mempot_0,8,0);
        VL_IN16(io_din_mempot_1,8,0);
        VL_IN16(io_din_mempot_2,8,0);
        VL_IN16(io_din_mempot_3,8,0);
        VL_IN16(io_din_mempot_4,8,0);
        VL_IN16(io_din_mempot_5,8,0);
        VL_IN16(io_din_mempot_6,8,0);
        VL_IN16(io_din_mempot_7,8,0);
        VL_IN16(io_din_mempot_8,8,0);
        VL_OUT16(io_dout_mempot_0,8,0);
        VL_OUT16(io_dout_mempot_1,8,0);
        VL_OUT16(io_dout_mempot_2,8,0);
        VL_OUT16(io_dout_mempot_3,8,0);
        VL_OUT16(io_dout_mempot_4,8,0);
        VL_OUT16(io_dout_mempot_5,8,0);
        VL_OUT16(io_dout_mempot_6,8,0);
        VL_OUT16(io_dout_mempot_7,8,0);
        VL_OUT16(io_dout_mempot_8,8,0);
        SData/*8:0*/ pe__DOT__io_writeData_aeq_0;
        SData/*8:0*/ pe__DOT__io_writeData_aeq_1;
        SData/*8:0*/ pe__DOT__io_writeData_aeq_2;
        SData/*8:0*/ pe__DOT__io_writeData_aeq_3;
        SData/*8:0*/ pe__DOT__io_writeData_aeq_4;
    };
    struct {
        SData/*8:0*/ pe__DOT__io_writeData_aeq_5;
        SData/*8:0*/ pe__DOT__io_writeData_aeq_6;
        SData/*8:0*/ pe__DOT__io_writeData_aeq_7;
        SData/*8:0*/ pe__DOT__io_writeData_aeq_8;
        SData/*8:0*/ pe__DOT__io_readData_aeq_0;
        SData/*8:0*/ pe__DOT__io_readData_aeq_1;
        SData/*8:0*/ pe__DOT__io_readData_aeq_2;
        SData/*8:0*/ pe__DOT__io_readData_aeq_3;
        SData/*8:0*/ pe__DOT__io_readData_aeq_4;
        SData/*8:0*/ pe__DOT__io_readData_aeq_5;
        SData/*8:0*/ pe__DOT__io_readData_aeq_6;
        SData/*8:0*/ pe__DOT__io_readData_aeq_7;
        SData/*8:0*/ pe__DOT__io_readData_aeq_8;
        SData/*8:0*/ pe__DOT__io_din_mempot_0;
        SData/*8:0*/ pe__DOT__io_din_mempot_1;
        SData/*8:0*/ pe__DOT__io_din_mempot_2;
        SData/*8:0*/ pe__DOT__io_din_mempot_3;
        SData/*8:0*/ pe__DOT__io_din_mempot_4;
        SData/*8:0*/ pe__DOT__io_din_mempot_5;
        SData/*8:0*/ pe__DOT__io_din_mempot_6;
        SData/*8:0*/ pe__DOT__io_din_mempot_7;
        SData/*8:0*/ pe__DOT__io_din_mempot_8;
        SData/*8:0*/ pe__DOT__io_dout_mempot_0;
        SData/*8:0*/ pe__DOT__io_dout_mempot_1;
        SData/*8:0*/ pe__DOT__io_dout_mempot_2;
        SData/*8:0*/ pe__DOT__io_dout_mempot_3;
        SData/*8:0*/ pe__DOT__io_dout_mempot_4;
        SData/*8:0*/ pe__DOT__io_dout_mempot_5;
        SData/*8:0*/ pe__DOT__io_dout_mempot_6;
        SData/*8:0*/ pe__DOT__io_dout_mempot_7;
        SData/*8:0*/ pe__DOT__io_dout_mempot_8;
        SData/*8:0*/ pe__DOT___mempotMem_io_dout_0;
        SData/*8:0*/ pe__DOT___mempotMem_io_dout_1;
        SData/*8:0*/ pe__DOT___mempotMem_io_dout_2;
        SData/*8:0*/ pe__DOT___mempotMem_io_dout_3;
        SData/*8:0*/ pe__DOT___mempotMem_io_dout_4;
        SData/*8:0*/ pe__DOT___mempotMem_io_dout_5;
        SData/*8:0*/ pe__DOT___mempotMem_io_dout_6;
        SData/*8:0*/ pe__DOT___mempotMem_io_dout_7;
        SData/*8:0*/ pe__DOT___mempotMem_io_dout_8;
        SData/*8:0*/ pe__DOT__s2_memRead_0;
        SData/*8:0*/ pe__DOT__s2_memRead_1;
        SData/*8:0*/ pe__DOT__s2_memRead_2;
        SData/*8:0*/ pe__DOT__s2_memRead_3;
        SData/*8:0*/ pe__DOT__s2_memRead_4;
        SData/*8:0*/ pe__DOT__s2_memRead_5;
        SData/*8:0*/ pe__DOT__s2_memRead_6;
        SData/*8:0*/ pe__DOT__s2_memRead_7;
        SData/*8:0*/ pe__DOT__s2_memRead_8;
        SData/*8:0*/ pe__DOT__s3_updates_0;
        SData/*8:0*/ pe__DOT__s3_updates_1;
        SData/*8:0*/ pe__DOT__s3_updates_2;
        SData/*8:0*/ pe__DOT__s3_updates_3;
        SData/*8:0*/ pe__DOT__s3_updates_4;
        SData/*8:0*/ pe__DOT__s3_updates_5;
        SData/*8:0*/ pe__DOT__s3_updates_6;
        SData/*8:0*/ pe__DOT__s3_updates_7;
        SData/*8:0*/ pe__DOT__s3_updates_8;
        SData/*8:0*/ pe__DOT__unnamedblk1__DOT__unnamedblk2__DOT___update_T;
        SData/*8:0*/ pe__DOT__unnamedblk1__DOT__unnamedblk2__DOT___update_T_1;
        SData/*8:0*/ pe__DOT__unnamedblk1__DOT__unnamedblk2__DOT___update_T_2;
        SData/*8:0*/ pe__DOT__unnamedblk1__DOT__unnamedblk2__DOT___update_T_3;
        SData/*8:0*/ pe__DOT__unnamedblk1__DOT__unnamedblk2__DOT___update_T_4;
        SData/*8:0*/ pe__DOT__unnamedblk1__DOT__unnamedblk2__DOT___update_T_5;
    };
    struct {
        SData/*8:0*/ pe__DOT__unnamedblk1__DOT__unnamedblk2__DOT___update_T_6;
        SData/*8:0*/ pe__DOT__unnamedblk1__DOT__unnamedblk2__DOT___update_T_7;
        SData/*8:0*/ pe__DOT__unnamedblk1__DOT__unnamedblk2__DOT___update_T_8;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_writeData_0;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_writeData_1;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_writeData_2;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_writeData_3;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_writeData_4;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_writeData_5;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_writeData_6;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_writeData_7;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_writeData_8;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_readData_0;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_readData_1;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_readData_2;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_readData_3;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_readData_4;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_readData_5;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_readData_6;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_readData_7;
        SData/*8:0*/ pe__DOT__aeqMem__DOT__io_readData_8;
        SData/*10:0*/ pe__DOT__aeqMem__DOT___multiMem_io_rdData_0;
        SData/*10:0*/ pe__DOT__aeqMem__DOT___multiMem_io_rdData_1;
        SData/*10:0*/ pe__DOT__aeqMem__DOT___multiMem_io_rdData_2;
        SData/*10:0*/ pe__DOT__aeqMem__DOT___multiMem_io_rdData_3;
        SData/*10:0*/ pe__DOT__aeqMem__DOT___multiMem_io_rdData_4;
        SData/*10:0*/ pe__DOT__aeqMem__DOT___multiMem_io_rdData_5;
        SData/*10:0*/ pe__DOT__aeqMem__DOT___multiMem_io_rdData_6;
        SData/*10:0*/ pe__DOT__aeqMem__DOT___multiMem_io_rdData_7;
        SData/*10:0*/ pe__DOT__aeqMem__DOT___multiMem_io_rdData_8;
        SData/*10:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrData_8;
        SData/*10:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrData_7;
        SData/*10:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrData_6;
        SData/*10:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrData_5;
        SData/*10:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrData_4;
        SData/*10:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrData_3;
        SData/*10:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrData_2;
        SData/*10:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrData_1;
        SData/*10:0*/ pe__DOT__aeqMem__DOT____Vcellinp__multiMem__io_wrData_0;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdData_0;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdData_1;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdData_2;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdData_3;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdData_4;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdData_5;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdData_6;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdData_7;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_rdData_8;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrData_0;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrData_1;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrData_2;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrData_3;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrData_4;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrData_5;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrData_6;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrData_7;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__io_wrData_8;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT__R0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT__W0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT__R0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT__W0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT__R0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT__W0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT__R0_data;
    };
    struct {
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT__W0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT__R0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT__W0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT__R0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT__W0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT__R0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT__W0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT__R0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT__W0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT__R0_data;
        SData/*10:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT__W0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_din_0;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_din_1;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_din_2;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_din_3;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_din_4;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_din_5;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_din_6;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_din_7;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_din_8;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_dout_0;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_dout_1;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_dout_2;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_dout_3;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_dout_4;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_dout_5;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_dout_6;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_dout_7;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__io_dout_8;
        SData/*8:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrData_8;
        SData/*8:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrData_7;
        SData/*8:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrData_6;
        SData/*8:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrData_5;
        SData/*8:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrData_4;
        SData/*8:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrData_3;
        SData/*8:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrData_2;
        SData/*8:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrData_1;
        SData/*8:0*/ pe__DOT__mempotMem__DOT____Vcellinp__multiMem__io_wrData_0;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdData_0;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdData_1;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdData_2;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdData_3;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdData_4;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdData_5;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdData_6;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdData_7;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_rdData_8;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrData_0;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrData_1;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrData_2;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrData_3;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrData_4;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrData_5;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrData_6;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrData_7;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__io_wrData_8;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT__R0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT__W0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT__R0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT__W0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT__R0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT__W0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT__R0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT__W0_data;
    };
    struct {
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT__R0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT__W0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT__R0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT__W0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT__R0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT__W0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT__R0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT__W0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT__R0_data;
        SData/*8:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT__W0_data;
        IData/*31:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT___RANDOM_MEM;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VicoIterCount;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<IData/*31:0*/, 8> pe__DOT__unnamedblk4__DOT___RANDOM;
        VlUnpacked<IData/*31:0*/, 3> pe__DOT__aeqMem__DOT__unnamedblk1__DOT___RANDOM;
        VlUnpacked<SData/*10:0*/, 256> pe__DOT__aeqMem__DOT__multiMem__DOT__mems_0_ext__DOT__Memory;
        VlUnpacked<SData/*10:0*/, 256> pe__DOT__aeqMem__DOT__multiMem__DOT__mems_1_ext__DOT__Memory;
        VlUnpacked<SData/*10:0*/, 256> pe__DOT__aeqMem__DOT__multiMem__DOT__mems_2_ext__DOT__Memory;
        VlUnpacked<SData/*10:0*/, 256> pe__DOT__aeqMem__DOT__multiMem__DOT__mems_3_ext__DOT__Memory;
        VlUnpacked<SData/*10:0*/, 256> pe__DOT__aeqMem__DOT__multiMem__DOT__mems_4_ext__DOT__Memory;
        VlUnpacked<SData/*10:0*/, 256> pe__DOT__aeqMem__DOT__multiMem__DOT__mems_5_ext__DOT__Memory;
        VlUnpacked<SData/*10:0*/, 256> pe__DOT__aeqMem__DOT__multiMem__DOT__mems_6_ext__DOT__Memory;
        VlUnpacked<SData/*10:0*/, 256> pe__DOT__aeqMem__DOT__multiMem__DOT__mems_7_ext__DOT__Memory;
        VlUnpacked<SData/*10:0*/, 256> pe__DOT__aeqMem__DOT__multiMem__DOT__mems_8_ext__DOT__Memory;
        VlUnpacked<SData/*8:0*/, 256> pe__DOT__mempotMem__DOT__multiMem__DOT__mems_0_ext__DOT__Memory;
        VlUnpacked<SData/*8:0*/, 256> pe__DOT__mempotMem__DOT__multiMem__DOT__mems_1_ext__DOT__Memory;
        VlUnpacked<SData/*8:0*/, 256> pe__DOT__mempotMem__DOT__multiMem__DOT__mems_2_ext__DOT__Memory;
        VlUnpacked<SData/*8:0*/, 256> pe__DOT__mempotMem__DOT__multiMem__DOT__mems_3_ext__DOT__Memory;
        VlUnpacked<SData/*8:0*/, 256> pe__DOT__mempotMem__DOT__multiMem__DOT__mems_4_ext__DOT__Memory;
        VlUnpacked<SData/*8:0*/, 256> pe__DOT__mempotMem__DOT__multiMem__DOT__mems_5_ext__DOT__Memory;
        VlUnpacked<SData/*8:0*/, 256> pe__DOT__mempotMem__DOT__multiMem__DOT__mems_6_ext__DOT__Memory;
        VlUnpacked<SData/*8:0*/, 256> pe__DOT__mempotMem__DOT__multiMem__DOT__mems_7_ext__DOT__Memory;
        VlUnpacked<SData/*8:0*/, 256> pe__DOT__mempotMem__DOT__multiMem__DOT__mems_8_ext__DOT__Memory;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
